#!/usr/bin/perl -w
# This script is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

use strict;

############################################################
# Program
############################################################

my $infile="./firstnames.UTF8.txt";
my $outfile="firstnames.UTF8.txt.no-ascii-lines";

my %seen=();

open(IN, "$infile") || 
     die "Error: $! $infile not found!"; 
open(OUT, ">$outfile"); 


while (<IN>){
    #print $_;
    my $line=$_;
    chomp($line);
    #$line=~s/ //g;
    $line=~s/^\s*//; 
    $line=~s/\s*$//;

    if ($line=~/[^a-zA-Z\-]/) { 
        # continue with non-standard(~non-ascii) chars
        print OUT "$line\n";
        if (exists ${seen}{$line}){
            print "Multiple entries: $line\n";
        }
        ${seen}{$line}="seen";
    }
}





close(IN);
close(OUT);


