#!/usr/bin/perl -w
# This script (sophomorix-test-5) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 time_stamp_AD 
                                 get_passwd_charlist
                                 get_plain_password
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_school_create
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_group_create
                                 AD_group_addmember
                                 AD_user_kill
                                 AD_dns_get
                                 AD_object_search
                                 AD_debug_logdump
                                 AD_get_name_tokened
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_object_nonexist
                                 AD_test_object
                                 directory_tree_test
                                 run_command
                                 );

$Conf::log_level=1;
my $help=0;
my $full=0;



my $add_admin=0;
my $test_add_admin=0;

my $mod_admin=0;
my $test_mod_admin=0;

my $kill_admin=0;
my $test_kill_admin=0;

my $all_options="";
my $json=0;

my $testopt=GetOptions(
           "help|h" => \$help,
           "full|f" => \$full,
           "verbose|v+" => \$Conf::log_level,
           "json|j+" => \$json,
           "add-admin" => \$add_admin,
           "test-add-admin" => \$test_add_admin,
           "mod-admin" => \$mod_admin,
           "test-mod-admin" => \$test_mod_admin,
           "kill-admin" => \$kill_admin,
           "test-kill-admin" => \$test_kill_admin,
  );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);

if ($Conf::log_level==1){
    $all_options="";
} elsif ($Conf::log_level==2){
    $all_options="-v";
} elsif ($Conf::log_level==3){
    $all_options="-vv";
}

if ($json==0){
    # nothing to do
} elsif ($json==1){
    $all_options=$all_options." -j";
} elsif ($json==2){
    $all_options=$all_options." -jj";
} elsif ($json==3){
    $all_options=$all_options." -jjj";
} 

my ($ldap,$root_dse) = &AD_bind_admin();
my $root_dns=&AD_dns_get($root_dse);

my $testdata="/usr/share/sophomorix-developer/testdata";

# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-test-5 tests the addition of admins.

Options
  -h  / --help

  Admins:
  sophomorix-test-5 --add-admin  
    add some admins
  sophomorix-test-5 --test-add-admin
    test the added admins

  sophomorix-test-5 --mod-admin
    modify added admins
  sophomorix-test-5 --test-mod-admin
    test modified admins

  sophomorix-test-5 --kill-admin
    kill all added admins
  sophomorix-test-5 --test-kill-admin
    test killed admins

');
   print "\n";
   exit;
}





############################################################
# Check preliminaries
############################################################

# --full
if ($full==1){
    $add_admin=1;
    $mod_admin=1;
    $kill_admin=1;
    $test_add_admin=1;
    $test_mod_admin=1;
    $test_kill_admin=1;
}

############################################################
# Add admins
############################################################
# --add-admin  
if ($add_admin==1){
    # schooladmin in OU=bsz and OU=abc
    &run_command("sophomorix-admin $all_options --create-school-admin admin-bsz-66 --school bsz --password 'Muster!'");
    &run_command("sophomorix-admin $all_options --create-school-admin admin-abc-666 --school abc --password 'Muster!'");
    # schooladmin in OU=default-school
    &run_command("sophomorix-admin $all_options --create-school-admin admin-66 --school default-school --password 'Muster!'");
    &run_command("sophomorix-admin $all_options --create-school-admin admin-666 --school default-school --password 'Muster!'");
    # alladmin in OU=GLOBAL
    &run_command("sophomorix-admin $all_options --create-all-admin all-admin-66 --password 'Muster!'");
    &run_command("sophomorix-admin $all_options --create-all-admin all-admin-666 --password 'Muster!'");
    # globaladmin in OU=GLOBAL
    &run_command("sophomorix-admin $all_options --create-global-admin global-admin-66 --password 'Muster!'");
    &run_command("sophomorix-admin $all_options --create-global-admin global-admin-666 --password 'Muster!'");

}

############################################################
# Test added admins
############################################################
# --test-add-admin  
if ($test_add_admin==1){
    ##### Testing the users
    # admin-bsz-66
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=admin-bsz-66,OU=Management,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"bsz Admin",
                   givenName=>"bsz",
                   name=>"admin-bsz-66",
                   sAMAccountname=>"admin-bsz-66",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\bsz\\management\\admin-bsz-66",
                   unixHomeDirectory=>"/srv/samba/schools/bsz/management/admin-bsz-66",
                   sn=>"Admin",
                   userPrincipalName => "admin-bsz-66@".$root_dns,
                   sophomorixAdminClass => "bsz-admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "bsz",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "schooladministrator",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "bsz-admins|bsz-wifi|bsz-internet|bsz-webfilter|bsz-intranet|bsz-printing",
                  });
    ##### Testing the users group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-admins,OU=Management,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-admins",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"admins",
                   sophomorixHidden=>"FALSE",
                   sophomorixSchoolname => "bsz",
                   memberOf => "bsz|all-admins",
                   member => "admin-bsz-66|newglobal-admins",
                  });


    # admin-abc-666
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=admin-abc-666,OU=Management,OU=abc,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"abc Admin",
                   givenName=>"abc",
                   name=>"admin-abc-666",
                   sAMAccountname=>"admin-abc-666",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\abc\\management\\admin-abc-666",
                   unixHomeDirectory=>"/srv/samba/schools/abc/management/admin-abc-666",
                   sn=>"Admin",
                   userPrincipalName => "admin-abc-666@".$root_dns,
                   sophomorixAdminClass => "abc-admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "abc",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "schooladministrator",
                   sophomorixSchoolPrefix => "abc",
                   sophomorixSchoolname => "abc",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "abc-admins|abc-wifi|abc-internet|abc-webfilter|abc-intranet|abc-printing",
                  });
    ##### Testing the users group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=abc-admins,OU=Management,OU=abc,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"abc-admins",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"admins",
                   sophomorixHidden=>"FALSE",
                   sophomorixSchoolname => "abc",
                   memberOf => "abc|all-admins",
                   member => "admin-abc-666|newglobal-admins",
                  });

    # admin-66
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=admin-66,OU=Management,OU=default-school,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"default-school Admin",
                   givenName=>"default-school",
                   name=>"admin-66",
                   sAMAccountname=>"admin-66",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\default-school\\management\\admin-66",
                   unixHomeDirectory=>"/srv/samba/schools/default-school/management/admin-66",
                   sn=>"Admin",
                   userPrincipalName => "admin-66@".$root_dns,
                   sophomorixAdminClass => "admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "default-school",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "schooladministrator",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "default-school",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "admins|wifi|internet|webfilter|intranet|printing",
                  });
    # admin-666
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=admin-666,OU=Management,OU=default-school,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"default-school Admin",
                   givenName=>"default-school",
                   name=>"admin-666",
                   sAMAccountname=>"admin-666",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\default-school\\management\\admin-666",
                   unixHomeDirectory=>"/srv/samba/schools/default-school/management/admin-666",
                   sn=>"Admin",
                   userPrincipalName => "admin-666@".$root_dns,
                   sophomorixAdminClass => "admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "default-school",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "schooladministrator",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "default-school",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "admins|wifi|internet|webfilter|intranet|printing",
                  });
    ##### Testing the users group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=admins,OU=Management,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"admins",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"admins",
                   sophomorixHidden=>"FALSE",
                   sophomorixSchoolname => "default-school",
                   memberOf => "default-school|all-admins",
                   member => "admin-66|admin-666|newglobal-admins",
                  });





    # all-admin-66
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=all-admin-66,OU=Management,OU=GLOBAL,".$root_dse,
                   #####
                   displayName=>"All Admin",
                   givenName=>"All",
                   name=>"all-admin-66",
                   sAMAccountname=>"all-admin-66",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\linuxmuster-global\\management\\all-admin-66",
                   unixHomeDirectory=>"/srv/samba/schools/global/management/all-admin-66",
                   sn=>"Admin",
                   userPrincipalName => "all-admin-66@".$root_dns,
                   sophomorixAdminClass => "all-admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "All",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "alladministrator",
                   sophomorixSchoolPrefix => "global",
                   sophomorixSchoolname => "global",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "all-admins|all-wifi|all-internet|all-webfilter|all-intranet|all-printing|Domain Admins",
                  });
    # all-admin-666
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=all-admin-666,OU=Management,OU=GLOBAL,".$root_dse,
                   #####
                   displayName=>"All Admin",
                   givenName=>"All",
                   name=>"all-admin-666",
                   sAMAccountname=>"all-admin-666",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\linuxmuster-global\\management\\all-admin-666",
                   unixHomeDirectory=>"/srv/samba/schools/global/management/all-admin-666",
                   sn=>"Admin",
                   userPrincipalName => "all-admin-666@".$root_dns,
                   sophomorixAdminClass => "all-admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "All",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "alladministrator",
                   sophomorixSchoolPrefix => "global",
                   sophomorixSchoolname => "global",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "all-admins|all-wifi|all-internet|all-webfilter|all-intranet|all-printing|Domain Admins",
                  });
    ##### Testing the users group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=all-admins,OU=Management,OU=GLOBAL,".$root_dse,
                   sAMAccountname=>"all-admins",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"alladmins",
                   sophomorixHidden=>"FALSE",
                   sophomorixSchoolname => "global",
                   memberOf => "",
                   member => "bsz-admins|abc-admins|admins|all-admin-66|all-admin-666",
                  });



    # global-admin-66
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-admin-66,OU=Management,OU=GLOBAL,".$root_dse,
                   #####
                   displayName=>"Global Admin",
                   givenName=>"Global",
                   name=>"global-admin-66",
                   sAMAccountname=>"global-admin-66",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\linuxmuster-global\\management\\global-admin-66",
                   unixHomeDirectory=>"/srv/samba/schools/global/management/global-admin-66",
                   sn=>"Admin",
                   userPrincipalName => "global-admin-66@".$root_dns,
                   sophomorixAdminClass => "newglobal-admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Global",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "globaladministrator",
                   sophomorixSchoolPrefix => "global",
                   sophomorixSchoolname => "global",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "newglobal-admins|all-wifi|all-internet|all-webfilter|all-intranet|all-printing|Domain Admins",
                  });
    # global-admin-666
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-admin-666,OU=Management,OU=GLOBAL,".$root_dse,
                   #####
                   displayName=>"Global Admin",
                   givenName=>"Global",
                   name=>"global-admin-666",
                   sAMAccountname=>"global-admin-666",
                   uidNumber=>"-1",
                   homeDrive=>"H:",
                   homeDirectory=>"\\\\linuxmuster.local\\linuxmuster-global\\management\\global-admin-666",
                   unixHomeDirectory=>"/srv/samba/schools/global/management/global-admin-666",
                   sn=>"Admin",
                   userPrincipalName => "global-admin-666@".$root_dns,
                   sophomorixAdminClass => "newglobal-admins",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Global",
                   sophomorixSurnameASCII  => "Admin",
                   sophomorixRole => "globaladministrator",
                   sophomorixSchoolPrefix => "global",
                   sophomorixSchoolname => "global",
                   sophomorixAdminFile => "none",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   sophomorixComment => "created by sophomorix",
                   sophomorixExamMode => "---",
                   sophomorixStatus=>"P",
                   sophomorixUnid => "---",
                   userAccountControl => "512",
                   memberOf => "newglobal-admins|all-wifi|all-internet|all-webfilter|all-intranet|all-printing|Domain Admins",
                  });
    ##### Testing the users group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=newglobal-admins,OU=Management,OU=GLOBAL,".$root_dse,
                   sAMAccountname=>"newglobal-admins",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"powergroup",
                   sophomorixHidden=>"FALSE",
                   sophomorixSchoolname => "global",
                   memberOf => "admins|bsz-admins|bsz-admins",
                   member => "global-admin-66|global-admin-666",
                  });

    &directory_tree_test("/srv/samba/schools",
                         "/srv/samba/schools",
                         "/srv/samba/schools/abc",
                         "/srv/samba/schools/abc/management",
                         "/srv/samba/schools/abc/management/admin-abc-666",
                         "/srv/samba/schools/abc/management/admin-abc-666/schooladmindir1",
                         "/srv/samba/schools/abc/management/admin-abc-666/schooladmindir2",
                         "/srv/samba/schools/abc/projects",
                         "/srv/samba/schools/abc/students",
                         "/srv/samba/schools/abc/teachers",
                         "/srv/samba/schools/abc/teachers/share",
                         "/srv/samba/schools/abc/teachers/homes",
                         "/srv/samba/schools/bsz",
                         "/srv/samba/schools/bsz/management",
                         "/srv/samba/schools/bsz/management/admin-bsz-66",
                         "/srv/samba/schools/bsz/management/admin-bsz-66/schooladmindir1",
                         "/srv/samba/schools/bsz/management/admin-bsz-66/schooladmindir2",
                         "/srv/samba/schools/bsz/projects",
                         "/srv/samba/schools/bsz/students",
                         "/srv/samba/schools/bsz/teachers",
                         "/srv/samba/schools/bsz/teachers/share",
                         "/srv/samba/schools/bsz/teachers/homes",
                         "/srv/samba/schools/default-school",
                         "/srv/samba/schools/default-school/management",
                         "/srv/samba/schools/default-school/management/admin-66",
                         "/srv/samba/schools/default-school/management/admin-66/schooladmindir1",
                         "/srv/samba/schools/default-school/management/admin-66/schooladmindir2",
                         "/srv/samba/schools/default-school/management/admin-666",
                         "/srv/samba/schools/default-school/management/admin-666/schooladmindir1",
                         "/srv/samba/schools/default-school/management/admin-666/schooladmindir2",
                         "/srv/samba/schools/default-school/projects",
                         "/srv/samba/schools/default-school/students",
                         "/srv/samba/schools/default-school/teachers",
                         "/srv/samba/schools/default-school/teachers/share",
                         "/srv/samba/schools/default-school/teachers/homes",
                        ); 
    &directory_tree_test("/srv/samba/global",
                         "/srv/samba/global",
                         "/srv/samba/global/management",
                         "/srv/samba/global/management/all-admin-66",
                         "/srv/samba/global/management/all-admin-66/alladmindir1",
                         "/srv/samba/global/management/all-admin-66/alladmindir2",
                         "/srv/samba/global/management/all-admin-666",
                         "/srv/samba/global/management/all-admin-666/alladmindir1",
                         "/srv/samba/global/management/all-admin-666/alladmindir2",
                         "/srv/samba/global/management/global-admin-66",
                         "/srv/samba/global/management/global-admin-66/globaladmindir1",
                         "/srv/samba/global/management/global-admin-66/globaladmindir2",
                         "/srv/samba/global/management/global-admin-666",
                         "/srv/samba/global/management/global-admin-666/globaladmindir1",
                         "/srv/samba/global/management/global-admin-666/globaladmindir2",
                         "/srv/samba/global/projects",
                         "/srv/samba/global/students",
                         "/srv/samba/global/teachers",
                        );
}




############################################################
# Modify added projects
############################################################
# --mod-admin  
if ($mod_admin==1){
    print "\nNothing to mod so far (--mod-admin), ...\n\n";
}

############################################################
#  Test modified  projects
############################################################
# --test-mod-admin  
if ($test_mod_admin==1){
    print "\nNothing to do so far (--test-mod-admin), ...\n\n";
}




############################################################
# Kill projects
############################################################
# --kill-admin  
if ($kill_admin==1){
    # schooladmin in OU=bsz und OU=abc
    &run_command("sophomorix-admin $all_options --kill admin-bsz-66");
    &run_command("sophomorix-admin $all_options --kill admin-abc-666");
    # schooladmin in OU=default-school
    &run_command("sophomorix-admin $all_options --kill admin-66");
    &run_command("sophomorix-admin $all_options --kill admin-666");
    # alladmin in OU=GLOBAL
    &run_command("sophomorix-admin $all_options --kill all-admin-66");
    &run_command("sophomorix-admin $all_options --kill all-admin-666");
    # globaladmin in OU=GLOBAL
    &run_command("sophomorix-admin $all_options --kill global-admin-66");
    &run_command("sophomorix-admin $all_options --kill global-admin-666");
}



############################################################
#  Test killed  users, groups, projects
############################################################
# --test-kill-admin  
if ($test_kill_admin==1){
    # users
    &AD_object_nonexist($ldap,$root_dse,"user","admin-bsz-66");
    &AD_object_nonexist($ldap,$root_dse,"user","admin-abc-666");
    &AD_object_nonexist($ldap,$root_dse,"user","admin-66");
    &AD_object_nonexist($ldap,$root_dse,"user","admin-666");
    &AD_object_nonexist($ldap,$root_dse,"user","all-admin-66");
    &AD_object_nonexist($ldap,$root_dse,"user","all-admin-666");

    &directory_tree_test("/srv/samba/schools",
                         "/srv/samba/schools",
                         "/srv/samba/schools/abc",
                         "/srv/samba/schools/abc/management",
                         "/srv/samba/schools/abc/projects",
                         "/srv/samba/schools/abc/students",
                         "/srv/samba/schools/abc/teachers",
                         "/srv/samba/schools/abc/teachers/share",
                         "/srv/samba/schools/abc/teachers/homes",
                         "/srv/samba/schools/bsz",
                         "/srv/samba/schools/bsz/management",
                         "/srv/samba/schools/bsz/projects",
                         "/srv/samba/schools/bsz/students",
                         "/srv/samba/schools/bsz/teachers",
                         "/srv/samba/schools/bsz/teachers/share",
                         "/srv/samba/schools/bsz/teachers/homes",
                         "/srv/samba/schools/default-school",
                         "/srv/samba/schools/default-school/management",
                         "/srv/samba/schools/default-school/projects",
                         "/srv/samba/schools/default-school/students",
                         "/srv/samba/schools/default-school/teachers",
                         "/srv/samba/schools/default-school/teachers/share",
                         "/srv/samba/schools/default-school/teachers/homes",
                        ); 
    &directory_tree_test("/srv/samba/global",
                         "/srv/samba/global",
                         "/srv/samba/global/management",
                         "/srv/samba/global/projects",
                         "/srv/samba/global/students",
                         "/srv/samba/global/teachers",
                        ); 
}


&AD_unbind_admin($ldap);
