#!/usr/bin/perl -w
# This script (sophomorix-test-4) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 time_stamp_AD 
                                 get_passwd_charlist
                                 get_plain_password
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_ou_add
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_group_create
                                 AD_group_addmember
                                 AD_user_kill
                                 AD_dns_get
                                 AD_object_search
                                 AD_debug_logdump
                                 AD_get_name_tokened
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_object_nonexist
                                 AD_test_object
                                 run_command
                                 );

$Conf::log_level=1;
my $help=0;
my $full=0;
my $add_class=0;
my $test_add_class=0;

my $mod_class=0;
my $test_mod_class=0;

my $kill_class=0;
my $test_kill_class=0;

my $verbose_options="";

my $testopt=GetOptions(
           "help|h" => \$help,
           "full|f" => \$full,
           "verbose|v+" => \$Conf::log_level,
           "add-class" => \$add_class,
           "test-add-class" => \$test_add_class,
           "mod-class" => \$mod_class,
           "test-mod-class" => \$test_mod_class,
           "kill-class" => \$kill_class,
           "test-kill-class" => \$test_kill_class,
  );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);



if ($Conf::log_level==1){
    $verbose_options="";
} elsif ($Conf::log_level==2){
    $verbose_options="-v";
} elsif ($Conf::log_level==3){
    $verbose_options="-vv";
}




my ($ldap,$root_dse) = &AD_bind_admin();
my $root_dns=&AD_dns_get($root_dse);

my $testdata="/usr/share/sophomorix-developer/testdata";


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-test-4 tests the addition of ExamAccounts and workstation accounts.

Options
  -h  / --help

  Classes:
  sophomorix-test-4 --add-class  
    add some classes
  sophomorix-test-4 --test-add-class
    test the added classes

  sophomorix-test-4 --mod-class
    modify added classes
  sophomorix-test-4 --test-mod-class
    test modified classes

  sophomorix-test-4 --kill-class
    kill all added classes
  sophomorix-test-4 --test-kill-class
    test killed classes

');
   print "\n";
   exit;
}





############################################################
# Check preliminaries
############################################################

# --full
if ($full==1){
    $add_class=1;
    $mod_class=1;
    $kill_class=1;
    $test_add_class=1;
    $test_mod_class=1;
    $test_kill_class=1;
}

my $file_add_test=$testdata."/sophomorix.add-30";
my $file_add=$DevelConf::path_result."/sophomorix.add";
my $file_kill=$DevelConf::path_result."/sophomorix.kill";
my $file_kill_test=$testdata."/sophomorix.kill-30";


############################################################
# Add classes
############################################################
# --add-class  
if ($add_class==1){
    # adding users
    &run_command("cp -v $file_add_test $file_add");
    &run_command("sophomorix-add $verbose_options");

    # groups in OU=BSZLEO
    &run_command("sophomorix-class $verbose_options --create --class class6 --ou BSZLEO --school-token bsz");
    &run_command("sophomorix-class $verbose_options --create --class class7 --ou BSZLEO --school-token bsz");
    # groups in OU=SCHOOL
    &run_command("sophomorix-class $verbose_options --create --class class12");
    &run_command("sophomorix-class $verbose_options --create --class class13");
}

############################################################
# Test added classes
############################################################
# --test-add-class  
if ($test_add_class==1){
    ##### Testing the users
    # maiersa23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=maiersa23,OU=bsz-m7ab,OU=Students,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Sarina Maier",
                   givenName=>"Sarina",
                   name=>"maiersa23",
                   sAMAccountname=>"maiersa23",
                   sn=>"Maier",
                   userPrincipalName => "maiersa23@".$root_dns,
                   sophomorixAdminClass => "bsz-m7ab",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Sarina",
                   sophomorixSurnameASCII  => "Maier",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m7ab",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m7ab,OU=bsz-m7ab,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-m7ab",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "bsz-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });


    # muellegr23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=muellegr23,OU=bsz-m7ab,OU=Students,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Gregor Müller",
                   givenName=>"Gregor",
                   name=>"muellegr23",
                   sAMAccountname=>"muellegr23",
                   sn=>"Müller",
                   userPrincipalName => "muellegr23@".$root_dns,
                   sophomorixAdminClass => "bsz-m7ab",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Gregor",
                   sophomorixSurnameASCII  => "Mueller",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m7ab",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m7ab,OU=bsz-m7ab,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-m7ab",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "bsz-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });


    # jonsonad23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=jonsonad23,OU=bsz-m8cd,OU=Students,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Aðalráður Jónsson",
                   givenName=>"Aðalráður",
                   name=>"jonsonad23",
                   sAMAccountname=>"jonsonad23",
                   sn=>"Jónsson",
                   userPrincipalName => "jonsonad23@".$root_dns,
                   sophomorixAdminClass => "bsz-m8cd",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Adalradur",
                   sophomorixSurnameASCII  => "Jonsson",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m8cd",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m8cd,OU=bsz-m8cd,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-m8cd",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "bsz-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });


    # samardze23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=samardze23,OU=bsz-m8cd,OU=Students,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Željko Samardžić",
                   givenName=>"Željko",
                   name=>"samardze23",
                   sAMAccountname=>"samardze23",
                   sn=>"Samardžić",
                   userPrincipalName => "samardze23@".$root_dns,
                   sophomorixAdminClass => "bsz-m8cd",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Zeljko",
                   sophomorixSurnameASCII  => "Samardzic",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m8cd",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m8cd,OU=bsz-m8cd,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-m8cd",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "bsz-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });


    # oe23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=oe23,OU=bsz-teachers,OU=Teachers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Gökhan Ömür",
                   givenName=>"Gökhan",
                   name=>"oe23",
                   sAMAccountname=>"oe23",
                   sn=>"Ömür",
                   userPrincipalName => "oe23@".$root_dns,
                   sophomorixAdminClass => "bsz-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Goekhan",
                   sophomorixSurnameASCII  => "Oemuer",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-teachers,OU=bsz-teachers,OU=Teachers,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-teachers",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-teachers",
                  });


    # wu23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=wu23,OU=bsz-teachers,OU=Teachers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Désirée Würth",
                   givenName=>"Désirée",
                   name=>"wu23",
                   sAMAccountname=>"wu23",
                   sn=>"Würth",
                   userPrincipalName => "wu23@".$root_dns,
                   sophomorixAdminClass => "bsz-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Desiree",
                   sophomorixSurnameASCII  => "Wuerth",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-teachers,OU=bsz-teachers,OU=Teachers,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-teachers",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-teachers",
                  });


    # blackmri23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=blackmri23,OU=uni-12abc,OU=Students,OU=UNIVERSITÄT,".$root_dse,
                   #####
                   displayName=>"Richard Blackmore",
                   givenName=>"Richard",
                   name=>"blackmri23",
                   sAMAccountname=>"blackmri23",
                   sn=>"Blackmore",
                   userPrincipalName => "blackmri23@".$root_dns,
                   sophomorixAdminClass => "uni-12abc",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Richard",
                   sophomorixSurnameASCII  => "Blackmore",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-12abc",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-12abc,OU=uni-12abc,OU=Students,OU=UNIVERSITÄT,".$root_dse,
                   sAMAccountname=>"uni-12abc",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "uni-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-students,OU=uni-students,OU=Students,OU=UNIVERSITÄT,".$root_dse,
                   sAMAccountname=>"uni-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });


    # lordjo23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=lordjo23,OU=uni-12abc,OU=Students,OU=UNIVERSITÄT,".$root_dse,
                   #####
                   displayName=>"Jon Lord",
                   givenName=>"Jon",
                   name=>"lordjo23",
                   sAMAccountname=>"lordjo23",
                   sn=>"Lord",
                   userPrincipalName => "lordjo23@".$root_dns,
                   sophomorixAdminClass => "uni-12abc",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Jon",
                   sophomorixSurnameASCII  => "Lord",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-12abc",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-12abc,OU=uni-12abc,OU=Students,OU=UNIVERSITÄT,".$root_dse,
                   sAMAccountname=>"uni-12abc",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "uni-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-students,OU=uni-students,OU=Students,OU=UNIVERSITÄT,".$root_dse,
                   sAMAccountname=>"uni-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });


    # kep23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=kep23,OU=uni-teachers,OU=Teachers,OU=UNIVERSITÄT,".$root_dse,
                   #####
                   displayName=>"Johannes Kepler",
                   givenName=>"Johannes",
                   name=>"kep23",
                   sAMAccountname=>"kep23",
                   sn=>"Kepler",
                   userPrincipalName => "kep23@".$root_dns,
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Johannes",
                   sophomorixSurnameASCII  => "Kepler",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-teachers,OU=uni-teachers,OU=Teachers,OU=UNIVERSITÄT,".$root_dse,
                   sAMAccountname=>"uni-teachers",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-teachers",
                  });


    # gal23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=gal23,OU=uni-teachers,OU=Teachers,OU=UNIVERSITÄT,".$root_dse,
                   #####
                   displayName=>"Galileo Galilei",
                   givenName=>"Galileo",
                   name=>"gal23",
                   sAMAccountname=>"gal23",
                   sn=>"Galilei",
                   userPrincipalName => "gal23@".$root_dns,
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Galileo",
                   sophomorixSurnameASCII  => "Galilei",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "UNIVERSITÄT",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-teachers,OU=uni-teachers,OU=Teachers,OU=UNIVERSITÄT,".$root_dse,
                   sAMAccountname=>"uni-teachers",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-teachers",
                  });
    # schneima23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=schneima23,OU=s6ade,OU=Students,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Marina Schneider",
                   givenName=>"Marina",
                   name=>"schneima23",
                   sAMAccountname=>"schneima23",
                   sn=>"Schneider",
                   userPrincipalName => "schneima23@".$root_dns,
                   sophomorixAdminClass => "s6ade",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Marina",
                   sophomorixSurnameASCII  => "Schneider",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "s6ade",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=s6ade,OU=s6ade,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"s6ade",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   memberOf => "students",
                  });
    ##### Testing the users ou-students group    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=students,OU=students,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   memberOf => "global-students",
                  });
    # sch23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=sch23,OU=teachers,OU=Teachers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Michael Schäfer",
                   givenName=>"Michael",
                   name=>"sch23",
                   sAMAccountname=>"sch23",
                   sn=>"Schäfer",
                   userPrincipalName => "sch23@".$root_dns,
                   sophomorixAdminClass => "teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Michael",
                   sophomorixSurnameASCII  => "Schaefer",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=teachers,OU=teachers,OU=Teachers,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"teachers",
                   memberOf => "global-teachers",
                  });

    ##### Testing the global groups
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-examaccounts,OU=Groups,OU=GLOBAL,".$root_dse,
                   sAMAccountname=>"global-examaccounts",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-students,OU=Groups,OU=GLOBAL,".$root_dse,
                   sAMAccountname=>"global-students",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-teachers,OU=Groups,OU=GLOBAL,".$root_dse,
                   sAMAccountname=>"global-teachers",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                  });

    # groups
    # bsz-class6
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-class6,OU=bsz-class6,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-class6",
                   description=>"bsz-class6",
                   sophomorixType=>"adminclass",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "bsz-students",
                  });
    # bsz-class7
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-class7,OU=bsz-class7,OU=Students,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-class7",
                   description=>"bsz-class7",
                   sophomorixType=>"adminclass",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "bsz-students",
                  });
    # class12
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"class12",
                   sophomorixType=>"adminclass",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "students",
                  });
    # class13
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class13,OU=class13,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class13",
                   description=>"class13",
                   sophomorixType=>"adminclass",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "students",
                  });
}




############################################################
# Modify added projects
############################################################
# --mod-class  
if ($mod_class==1){

    # --description
    &run_command("sophomorix-class $verbose_options -c class12 --description 'Klasse 12 TG'");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"---",
                   sophomorixMailQuota=>"0",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });
    # --quota
    &run_command("sophomorix-class $verbose_options -c class12 --quota 100+300");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"0",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --mailquota 
    &run_command("sophomorix-class $verbose_options -c class12 --mailquota 897");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --mailalias
    &run_command("sophomorix-class $verbose_options -c class12 --mailalias");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --maillist
    &run_command("sophomorix-class $verbose_options -c class12 --maillist");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --status
    &run_command("sophomorix-class $verbose_options -c class12 --status S");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --join
    &run_command("sophomorix-class $verbose_options -c class12 --nojoin");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --maxmembers
    &run_command("sophomorix-class $verbose_options -c class12 --maxmembers 16");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

    # --creationdate
    &run_command("sophomorix-class $verbose_options -c class12 --creationdate 19880529093330.0Z");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"Klasse 12 TG",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"100+300",
                   sophomorixMailQuota=>"897",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });

   #  # --admins
   #  &run_command("sophomorix-class $verbose_options -c class12 --admins maiersa23,muellegr23");

   #  # --members
   #  &run_command("sophomorix-class $verbose_options -c class12 --members kep23,wu23");

   #  # --admingroups
   #  &run_command("sophomorix-class $verbose_options -c class12 --admingroups super12,bsz-super6");

   #  # --membergroups
   #  &run_command("sophomorix-class $verbose_options -c class12 --membergroups super13,bsz-super7");


    # setting all back in one command
    &run_command("sophomorix-class $verbose_options -c class12 --join --quota --- --mailquota 0 --nomailalias --nomaillist --status P --maxmembers 0 --creationdate 20160529093330.0Z --description 'class12'");
    # checking if all is set back
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=class12,OU=class12,OU=Students,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"class12",
                   description=>"class12",
                   sophomorixType=>"adminclass",
                   sophomorixQuota=>"---",
                   sophomorixMailQuota=>"0",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   member => "",
                   memberOf => "students",
                  });
}

############################################################
#  Test modified  projects
############################################################
# --test-mod-class  
if ($test_mod_class==1){
    print "\nNothing to do so far (--test-mod-class), ...\n\n";
}




############################################################
# Kill projects
############################################################
# --kill-class  
if ($kill_class==1){
    &run_command("cp -v $file_kill_test $file_kill");
    &run_command("sophomorix-kill -i");
    &run_command("sophomorix-kill $verbose_options");
    # groups
    &run_command("sophomorix-class $verbose_options --kill --class class6 --ou BSZLEO --school-token bsz");
    &run_command("sophomorix-class $verbose_options --kill --class class7 --ou BSZLEO --school-token bsz");
    &run_command("sophomorix-class $verbose_options --kill --class class12");
    &run_command("sophomorix-class $verbose_options --kill --class class13");

}

############################################################
#  Test killed  users, groups, projects
############################################################
# --test-kill-class  
if ($test_kill_class==1){
    # users
    &AD_object_nonexist($ldap,$root_dse,"user","maiersa23");
    &AD_object_nonexist($ldap,$root_dse,"user","muellegr23");
    &AD_object_nonexist($ldap,$root_dse,"user","jonsonad23");
    &AD_object_nonexist($ldap,$root_dse,"user","samardze23");
    &AD_object_nonexist($ldap,$root_dse,"user","oe23");
    &AD_object_nonexist($ldap,$root_dse,"user","wu23");
    &AD_object_nonexist($ldap,$root_dse,"user","lordjo23");
    &AD_object_nonexist($ldap,$root_dse,"user","blackmri23");
    &AD_object_nonexist($ldap,$root_dse,"user","kep23");
    &AD_object_nonexist($ldap,$root_dse,"user","gal23");
    &AD_object_nonexist($ldap,$root_dse,"user","schneima23");
    &AD_object_nonexist($ldap,$root_dse,"user","sch23");

    # groups
    &AD_object_nonexist($ldap,$root_dse,"group","bsz-class6");
    &AD_object_nonexist($ldap,$root_dse,"group","bsz-class7");
    &AD_object_nonexist($ldap,$root_dse,"group","class12");
    &AD_object_nonexist($ldap,$root_dse,"group","class13");
}






&AD_unbind_admin($ldap);



