#!/usr/bin/perl -w
# This script (sophomorix-test-2) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# device tests
# test 1 to 2:
# OK: * add 2 computer in 2 rooms in 2 schools and 1 printer (no examaccount)
# OK: * rename a computer in the same room
# OK: * change ip of computer
# OK: * update mac adress -> no action so far



# * add another computer and another printer in each room
# * move a computer, printer in another room
# * move a computer, printer in another school (filename must change)

# * rename computer AND move it to another room, another school
# * make computer to printer and back


# Bibliotheken
use strict;
use Getopt::Long;
use Net::DNS;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 time_stamp_AD 
                                 get_passwd_charlist
                                 get_plain_password
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_ou_add
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_dns_get
                                 AD_user_create
                                 AD_computer_create
                                 AD_group_create
                                 AD_group_addmember
                                 AD_user_kill
                                 AD_computer_kill
                                 AD_object_search
                                 AD_get_name_tokened
                                 AD_login_test
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_object_nonexist
                                 AD_test_object
                                 AD_test_dns
                                 AD_test_nondns
                                 AD_computers_any
                                 AD_examaccounts_any
                                 AD_dnsnodes_any
                                 AD_rooms_any
                                 run_command
                                 );

$Conf::log_level=1;
my $help=0;

my $copy_devfile_1=0;
my $copy_devfile_2=0;
my $copy_devfile_3=0;
my $copy_devfile_4=0;
my $copy_devfile_5=0;
my $test_ws_1=0;
my $test_ws_2=0;
my $test_ws_3=0;
my $test_ws_4=0;
my $test_ws_5=0;

my $full=0;

my $ou="";
my $school_token="";
my $room="";
my $computer="";
my $role="";
# calculated

my $login="";
my $plain_password;
my $ws_count=0;
my $birthdate="1970-01-01";
my $verbose_options="";

# dns
my $res   = Net::DNS::Resolver->new;

my $testopt=GetOptions(
           "help|h" => \$help,
           "verbose|v+" => \$Conf::log_level,
           "copy-devfile-1" => \$copy_devfile_1,
           "test-dev-1" => \$test_ws_1,
           "copy-devfile-2" => \$copy_devfile_2,
           "test-dev-2" => \$test_ws_2,
           "copy-devfile-3" => \$copy_devfile_3,
           "test-dev-3" => \$test_ws_3,
           "copy-devfile-4" => \$copy_devfile_4,
           "test-dev-4" => \$test_ws_4,
           "copy-devfile-5" => \$copy_devfile_5,
           "test-dev-5" => \$test_ws_5,
           "full|f" => \$full,
  );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);

if ($Conf::log_level==1){
    $verbose_options="";
} elsif ($Conf::log_level==2){
    $verbose_options="-v";
} elsif ($Conf::log_level==3){
    $verbose_options="-vv";
}

my ($ldap,$root_dse) = &AD_bind_admin();
my $root_dns=&AD_dns_get($root_dse);


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-test-2 tests the addition of ExamAccounts and computer accounts.

Options
  -h  / --help

  --full  (run all tests automatically)

Step by step Test:
  Copy devices.csv/classrooms file (Step 1):
      sophomorix-test-2 --copy-devfile-1
  Import the file:
      sophomorix-device
  Run the tests:
      sophomorix-test-2 --test-dev-1

Step 2-4 are missing

  Copy EMPTY devices.csv/classrooms file (Step 5):
      sophomorix-test-2 --copy-devfile-5
  Import the file:
      sophomorix-device
  Run the tests:
      sophomorix-test-2 --test-dev-5
');
   print "\n";
   exit;
}




############################################################
# Check preliminaries
############################################################
# --full
if ($full==1){
    $copy_devfile_1=1;
    $copy_devfile_5=1;
    $test_ws_1=1;
    $test_ws_5=1;
}


my $host_workstation=$DevelConf::path_conf_host."/devices.csv";
my $host_classroom=$DevelConf::path_conf_host."/classrooms";
my $host_workstation_bsz=$DevelConf::path_conf_host."/bsz.devices.csv";
my $host_classroom_bsz=$DevelConf::path_conf_host."/bsz.classrooms";

my $testdata="/usr/share/sophomorix-developer/testdata";
my $wsfile_1=$testdata."/devices.csv-1";
my $wsfile_2=$testdata."/devices.csv-2";
my $wsfile_3=$testdata."/devices.csv-3";
my $wsfile_4=$testdata."/devices.csv-4";
my $wsfile_5=$testdata."/devices.csv-5";
my $wsfile_1_bsz=$testdata."/bsz.devices.csv-1";
my $wsfile_2_bsz=$testdata."/bsz.devices.csv-2";
my $wsfile_3_bsz=$testdata."/bsz.devices.csv-3";
my $wsfile_4_bsz=$testdata."/bsz.devices.csv-4";
my $wsfile_5_bsz=$testdata."/bsz.devices.csv-5";

my $crfile_1=$testdata."/classrooms-1";
my $crfile_2=$testdata."/classrooms-2";
my $crfile_3=$testdata."/classrooms-3";
my $crfile_4=$testdata."/classrooms-4";
my $crfile_5=$testdata."/classrooms-5";
my $crfile_1_bsz=$testdata."/bsz.classrooms-1";
my $crfile_2_bsz=$testdata."/bsz.classrooms-2";
my $crfile_3_bsz=$testdata."/bsz.classrooms-3";
my $crfile_4_bsz=$testdata."/bsz.classrooms-4";
my $crfile_5_bsz=$testdata."/bsz.classrooms-5";



my $time_stamp_AD=&time_stamp_AD();
my @passwort_zeichen=&get_passwd_charlist();
# ou's that have been created in this script
my %ou_created=();
$ou_created{$ou}="created";
my $room_token;
my $login_token;
my $examaccount_token;


############################################################
# Step 1
############################################################

# --copy-devfile-1
if ($copy_devfile_1==1){
    # copy devices.csv-1
    &run_command("cp -v $wsfile_1 $host_workstation");
    &run_command("cp -v $crfile_1 $host_classroom");
    &run_command("cp -v $wsfile_1_bsz $host_workstation_bsz");
    &run_command("cp -v $crfile_1_bsz $host_classroom_bsz");
}

if ($full==1){
    &run_command("sophomorix-device $verbose_options");
}

if ($test_ws_1==1){
    ############################################################
    # devices.csv
    ############################################################
    # j1008p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008p01,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1008p01",
                   sAMAccountname=>"j1008p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1008P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1008P01,OU=j1008,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1008P01",
                   name=>"J1008P01",
                   cn=>"J1008P01",
                   sAMAccountname=>"J1008P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1008P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1008P01,".
                                           "HOST/J1008P01.".$root_dns.",".
                                           "RestrictedKrbHost/J1008P01,".
                                           "RestrictedKrbHost/J1008P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1008p01","10.170.208.1");

    ############################################################
    # j1008p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008p02,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1008p02",
                   sAMAccountname=>"j1008p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1008P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1008P02,OU=j1008,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1008P02",
                   name=>"J1008P02",
                   cn=>"J1008P02",
                   sAMAccountname=>"J1008P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1008P02.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1008P02,".
                                           "HOST/J1008P02.".$root_dns.",".
                                           "RestrictedKrbHost/J1008P02,".
                                           "RestrictedKrbHost/J1008P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1008p02","10.170.208.2");

    ############################################################
    # laser1008
    &AD_object_nonexist($ldap,$root_dse,"examaccount","laser1008");
    &AD_object_nonexist($ldap,$root_dse,"computer","LASER1008\$");
    #dns 
    &AD_test_dns($res,"laser1008","10.170.208.30");

    ############################################################
    # j1010p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010p01,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1010p01",
                   sAMAccountname=>"j1010p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1010P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1010P01,OU=j1010,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1010P01",
                   name=>"J1010P01",
                   cn=>"J1010P01",
                   sAMAccountname=>"J1010P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1010P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1010P01,".
                                           "HOST/J1010P01.".$root_dns.",".
                                           "RestrictedKrbHost/J1010P01,".
                                           "RestrictedKrbHost/J1010P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1010p01","10.170.210.1");

    ############################################################
    # j1010p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010p02,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1010p02",
                   sAMAccountname=>"j1010p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1010P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1010P02,OU=j1010,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1010P02",
                   name=>"J1010P02",
                   cn=>"J1010P02",
                   sAMAccountname=>"J1010P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1010P02.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1010P02,".
                                           "HOST/J1010P02.".$root_dns.",".
                                           "RestrictedKrbHost/J1010P02,".
                                           "RestrictedKrbHost/J1010P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1010p02","10.170.210.2");

    ############################################################
    # laser1010
    &AD_object_nonexist($ldap,$root_dse,"examaccount","laser1010");
    &AD_object_nonexist($ldap,$root_dse,"computer","LASER1010\$");
    #dns 
    &AD_test_dns($res,"laser1010","10.170.210.30");

    ############################################################
    # c001p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","c001p01");
    # C001P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=C001P01,OU=c001,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer C001P01",
                   name=>"C001P01",
                   cn=>"C001P01",
                   sAMAccountname=>"C001P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "C001P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/C001P01,".
                                           "HOST/C001P01.".$root_dns.",".
                                           "RestrictedKrbHost/C001P01,".
                                           "RestrictedKrbHost/C001P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"c001p01","10.170.1.1");

    ############################################################
    # c002p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","c002p01");
    # C002P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=C002P01,OU=c002,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer C002P01",
                   name=>"C002P01",
                   cn=>"C002P01",
                   sAMAccountname=>"C002P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "C002P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/C002P01,".
                                           "HOST/C002P01.".$root_dns.",".
                                           "RestrictedKrbHost/C002P01,".
                                           "RestrictedKrbHost/C002P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"c002p01","10.170.2.1");

    ############################################################
    # bsz.devices.csv
    ############################################################
    # bsz-j1008p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008p01,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1008p01",
                   sAMAccountname=>"bsz-j1008p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1008P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1008P01,OU=bsz-j1008,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1008P01",
                   name=>"BSZ-J1008P01",
                   cn=>"BSZ-J1008P01",
                   sAMAccountname=>"BSZ-J1008P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1008P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1008P01,".
                                           "HOST/BSZ-J1008P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1008P01,".
                                           "RestrictedKrbHost/BSZ-J1008P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1008p01","10.171.208.1");

    ############################################################
    # bsz-j1008p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008p02,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1008p02",
                   sAMAccountname=>"bsz-j1008p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1008P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1008P02,OU=bsz-j1008,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1008P02",
                   name=>"BSZ-J1008P02",
                   cn=>"BSZ-J1008P02",
                   sAMAccountname=>"BSZ-J1008P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1008P02.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1008P02,".
                                           "HOST/BSZ-J1008P02.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1008P02,".
                                           "RestrictedKrbHost/BSZ-J1008P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1008p02","10.171.208.2");

    ############################################################
    # bsz-laser1008
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-laser1008");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-LASER\$");
    #dns 
    &AD_test_dns($res,"bsz-laser1008","10.171.208.30");

    ############################################################
    # bsz-j1010p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010p01,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1010p01",
                   sAMAccountname=>"bsz-j1010p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1010P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1010P01,OU=bsz-j1010,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1010P01",
                   name=>"BSZ-J1010P01",
                   cn=>"BSZ-J1010P01",
                   sAMAccountname=>"BSZ-J1010P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1010P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1010P01,".
                                           "HOST/BSZ-J1010P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1010P01,".
                                           "RestrictedKrbHost/BSZ-J1010P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1010p01","10.171.210.1");

    ############################################################
    # bsz-j1010p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010p02,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1010p02",
                   sAMAccountname=>"bsz-j1010p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1010P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1010P02,OU=bsz-j1010,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1010P02",
                   name=>"BSZ-J1010P02",
                   cn=>"BSZ-J1010P02",
                   sAMAccountname=>"BSZ-J1010P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1010P02.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1010P02,".
                                           "HOST/BSZ-J1010P02.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1010P02,".
                                           "RestrictedKrbHost/BSZ-J1010P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1010p02","10.171.210.2");

    ############################################################
    # bsz-laser1010
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-laser1010");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-LASER1010\$");
    #dns 
    &AD_test_dns($res,"bsz-laser1010","10.171.210.30");

    ############################################################
    # bsz-d001p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-d001p01");
    # BSZ-D001P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-D001P01,OU=bsz-d001,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-D001P01",
                   name=>"BSZ-D001P01",
                   cn=>"BSZ-D001P01",
                   sAMAccountname=>"BSZ-D001P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-D001P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-D001P01,".
                                           "HOST/BSZ-D001P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-D001P01,".
                                           "RestrictedKrbHost/BSZ-D001P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-d001p01","10.171.1.1");

    ############################################################
    # bsz-d002p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-d002p01");
    # BSZ-D002P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-D002P01,OU=bsz-d002,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-D002P01",
                   name=>"BSZ-D002P01",
                   cn=>"BSZ-D002P01",
                   sAMAccountname=>"BSZ-D002P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-D002P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-D002P01,".
                                           "HOST/BSZ-D002P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-D002P01,".
                                           "RestrictedKrbHost/BSZ-D002P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-d002p01","10.171.2.1");
}


############################################################
# Step 2
############################################################
# --copy-devfile-2
if ($copy_devfile_2==1){
    # copy devices.csv-2
    &run_command("cp -v $wsfile_2 $host_workstation");
    &run_command("cp -v $crfile_2 $host_classroom");
    &run_command("cp -v $wsfile_2_bsz $host_workstation_bsz");
    &run_command("cp -v $crfile_2_bsz $host_classroom_bsz");
}


if ($test_ws_2==1){
    ############################################################
    # devices.csv
    ############################################################
    # j1008p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008p01,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1008p01",
                   sAMAccountname=>"j1008p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1008P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1008P01,OU=j1008,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1008P01",
                   name=>"J1008P01",
                   cn=>"J1008P01",
                   sAMAccountname=>"J1008P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1008P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1008P01,".
                                           "HOST/J1008P01.".$root_dns.",".
                                           "RestrictedKrbHost/J1008P01,".
                                           "RestrictedKrbHost/J1008P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1008p01","10.170.208.1");

    ############################################################
    # j1008p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008p02,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1008p02",
                   sAMAccountname=>"j1008p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1008,OU=j1008,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1008P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1008P02,OU=j1008,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1008P02",
                   name=>"J1008P02",
                   cn=>"J1008P02",
                   sAMAccountname=>"J1008P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1008P02.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1008P02,".
                                           "HOST/J1008P02.".$root_dns.",".
                                           "RestrictedKrbHost/J1008P02,".
                                           "RestrictedKrbHost/J1008P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1008p02","10.170.208.2");

    ############################################################
    # laser1008
    &AD_object_nonexist($ldap,$root_dse,"examaccount","laser1008");
    &AD_object_nonexist($ldap,$root_dse,"computer","LASER1008\$");
    #dns 
    &AD_test_dns($res,"laser1008","10.170.208.30");

    ############################################################
    # j1010p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010p01,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1010p01",
                   sAMAccountname=>"j1010p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1010P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1010P01,OU=j1010,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1010P01",
                   name=>"J1010P01",
                   cn=>"J1010P01",
                   sAMAccountname=>"J1010P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1010P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1010P01,".
                                           "HOST/J1010P01.".$root_dns.",".
                                           "RestrictedKrbHost/J1010P01,".
                                           "RestrictedKrbHost/J1010P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1010p01","10.170.210.1");

    ############################################################
    # j1010p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010p02,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"j1010p02",
                   sAMAccountname=>"j1010p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   sophomorixAdminFile => "devices.csv",
                   memberOf => "j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=j1010,OU=j1010,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=examaccounts,OU=examaccounts,OU=ExamAccounts,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # J1010P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=J1010P02,OU=j1010,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer J1010P02",
                   name=>"J1010P02",
                   cn=>"J1010P02",
                   sAMAccountname=>"J1010P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "J1010P02.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/J1010P02,".
                                           "HOST/J1010P02.".$root_dns.",".
                                           "RestrictedKrbHost/J1010P02,".
                                           "RestrictedKrbHost/J1010P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"j1010p02","10.170.210.2");

    ############################################################
    # laser1010
    &AD_object_nonexist($ldap,$root_dse,"examaccount","laser1010");
    &AD_object_nonexist($ldap,$root_dse,"computer","LASER1010\$");
    #dns 
    &AD_test_dns($res,"laser1010","10.170.210.30");

    ############################################################
    # c001p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","c001p01");
    # C001P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=C001P01,OU=c001,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer C001P01",
                   name=>"C001P01",
                   cn=>"C001P01",
                   sAMAccountname=>"C001P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "C001P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/C001P01,".
                                           "HOST/C001P01.".$root_dns.",".
                                           "RestrictedKrbHost/C001P01,".
                                           "RestrictedKrbHost/C001P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"c001p01","10.170.1.1");

    ############################################################
    # c002p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","c002p01");
    # C002P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=C002P01,OU=c002,OU=Computers,OU=SCHOOL,".$root_dse,
                   #####
                   displayName=>"Computer C002P01",
                   name=>"C002P01",
                   cn=>"C002P01",
                   sAMAccountname=>"C002P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "C002P01.".$root_dns,
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "SCHOOL",
                   servicePrincipalName => "HOST/C002P01,".
                                           "HOST/C002P01.".$root_dns.",".
                                           "RestrictedKrbHost/C002P01,".
                                           "RestrictedKrbHost/C002P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"c002p01","10.170.2.1");

    ############################################################
    # bsz.devices.csv
    ############################################################
    # bsz-j1008p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008p01,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1008p01",
                   sAMAccountname=>"bsz-j1008p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1008P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1008P01,OU=bsz-j1008,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1008P01",
                   name=>"BSZ-J1008P01",
                   cn=>"BSZ-J1008P01",
                   sAMAccountname=>"BSZ-J1008P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1008P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1008P01,".
                                           "HOST/BSZ-J1008P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1008P01,".
                                           "RestrictedKrbHost/BSZ-J1008P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1008p01","10.171.208.1");

    ############################################################
    # bsz-j1008p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008p02,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1008p02",
                   sAMAccountname=>"bsz-j1008p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1008",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1008",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1008,OU=bsz-j1008,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1008",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1008P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1008P02,OU=bsz-j1008,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1008P02",
                   name=>"BSZ-J1008P02",
                   cn=>"BSZ-J1008P02",
                   sAMAccountname=>"BSZ-J1008P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1008P02.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1008P02,".
                                           "HOST/BSZ-J1008P02.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1008P02,".
                                           "RestrictedKrbHost/BSZ-J1008P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1008p02","10.171.208.2");

    ############################################################
    # bsz-laser1008
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-laser1008");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-LASER\$");
    #dns 
    &AD_test_dns($res,"bsz-laser1008","10.171.208.30");

    ############################################################
    # bsz-j1010p01
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010p01,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1010p01",
                   sAMAccountname=>"bsz-j1010p01",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1010P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1010P01,OU=bsz-j1010,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1010P01",
                   name=>"BSZ-J1010P01",
                   cn=>"BSZ-J1010P01",
                   sAMAccountname=>"BSZ-J1010P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1010P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1010P01,".
                                           "HOST/BSZ-J1010P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1010P01,".
                                           "RestrictedKrbHost/BSZ-J1010P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1010p01","10.171.210.1");

    ############################################################
    # bsz-j1010p02
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010p02,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Exam Account",
                   givenName=>"Exam",
                   name=>"bsz-j1010p02",
                   sAMAccountname=>"bsz-j1010p02",
                   uidNumber=>"-1",
                   sn=>"Account",
                   sophomorixAdminClass => "bsz-j1010",
                   sophomorixExitAdminClass => "unknown",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Exam",
                   sophomorixSurnameASCII  => "Account",
                   sophomorixRole => "examaccount",
                   sophomorixStatus=>"P",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   sophomorixAdminFile => "bsz.devices.csv",
                   memberOf => "bsz-j1010",
                  });
    ##### Testing the exam accounts room
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-j1010,OU=bsz-j1010,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-j1010",
                   gidNumber=>"-1",
                   sophomorixStatus=>"P",
                   sophomorixType=>"room",
                   memberOf => "bsz-examaccounts",
                  });
    ##### Testing the examaccounts <token>-examaccounts group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-examaccounts,OU=bsz-examaccounts,OU=ExamAccounts,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-examaccounts",
                   gidNumber=>"-1",
                   memberOf => "global-examaccounts",
                  });

    # BSZ-J1010P02$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-J1010P02,OU=bsz-j1010,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-J1010P02",
                   name=>"BSZ-J1010P02",
                   cn=>"BSZ-J1010P02",
                   sAMAccountname=>"BSZ-J1010P02\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-J1010P02.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-J1010P02,".
                                           "HOST/BSZ-J1010P02.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-J1010P02,".
                                           "RestrictedKrbHost/BSZ-J1010P02.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-j1010p02","10.171.210.2");

    ############################################################
    # bsz-laser1010
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-laser1010");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-LASER1010\$");
    #dns 
    &AD_test_dns($res,"bsz-laser1010","10.171.210.30");

    ############################################################
    # bsz-d001p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-d001p01");
    # BSZ-D001P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-D001P01,OU=bsz-d001,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-D001P01",
                   name=>"BSZ-D001P01",
                   cn=>"BSZ-D001P01",
                   sAMAccountname=>"BSZ-D001P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-D001P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-D001P01,".
                                           "HOST/BSZ-D001P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-D001P01,".
                                           "RestrictedKrbHost/BSZ-D001P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-d001p01","10.171.1.1");

    ############################################################
    # bsz-d002p01
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-d002p01");
    # BSZ-D002P01$
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=BSZ-D002P01,OU=bsz-d002,OU=Computers,OU=BSZLEO,".$root_dse,
                   #####
                   displayName=>"Computer BSZ-D002P01",
                   name=>"BSZ-D002P01",
                   cn=>"BSZ-D002P01",
                   sAMAccountname=>"BSZ-D002P01\$",
                   #sophomorixFirstPassword => "Muster!",
                   sophomorixRole => "computer",
                   sophomorixStatus=>"P",
                   accountExpires => "9223372036854775807",
                   dNSHostName => "BSZ-D002P01.".$root_dns,
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "BSZLEO",
                   servicePrincipalName => "HOST/BSZ-D002P01,".
                                           "HOST/BSZ-D002P01.".$root_dns.",".
                                           "RestrictedKrbHost/BSZ-D002P01,".
                                           "RestrictedKrbHost/BSZ-D002P01.".$root_dns.",",
                  });
    #dns 
    &AD_test_dns($res,"bsz-d002p01","10.171.2.1");
}


############################################################
# Step 3
############################################################
# --copy-devfile-3
if ($copy_devfile_3==1){
    # copy devices.csv-3
    &run_command("cp -v $wsfile_3 $host_workstation");
    &run_command("cp -v $crfile_3 $host_classroom");
    &run_command("cp -v $wsfile_3_bsz $host_workstation_bsz");
    &run_command("cp -v $crfile_3_bsz $host_classroom_bsz");
}


if ($test_ws_3==1){


}


############################################################
# Step 4
############################################################
# --copy-devfile-4
if ($copy_devfile_4==1){
    # copy devices.csv-4
    &run_command("cp -v $wsfile_4 $host_workstation");
    &run_command("cp -v $crfile_4 $host_classroom");
    &run_command("cp -v $wsfile_4_bsz $host_workstation_bsz");
    &run_command("cp -v $crfile_4_bsz $host_classroom_bsz");
}

if ($test_ws_4==1){


}


############################################################
# Step 5  empty file
############################################################
# --copy-devfile-5
if ($copy_devfile_5==1){
    # copy devices.csv-5
    &run_command("cp -v $wsfile_5 $host_workstation");
    &run_command("cp -v $crfile_5 $host_classroom");
    &run_command("cp -v $wsfile_5_bsz $host_workstation_bsz");
    &run_command("cp -v $crfile_5_bsz $host_classroom_bsz");
}

if ($full==1){
    &run_command("sophomorix-device $verbose_options");
}

if ($test_ws_5==1){
    ############################################################
    # SCHOOL
    &AD_object_nonexist($ldap,$root_dse,"examaccount","j1008p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","J1008P01\$");
    &AD_test_nondns($res,"j1008p01");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","j1008p02");
    &AD_object_nonexist($ldap,$root_dse,"computer","J1008P02\$");
    &AD_test_nondns($res,"j1008p02");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","laser1008");
    &AD_object_nonexist($ldap,$root_dse,"computer","LASER1008\$");
    &AD_test_nondns($res,"laserj1008");

    &AD_object_nonexist($ldap,$root_dse,"examaccount","j1010p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","J1010P01\$");
    &AD_test_nondns($res,"j1010p01");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","j1010p02");
    &AD_object_nonexist($ldap,$root_dse,"computer","J1010P02\$");
    &AD_test_nondns($res,"j1010p02");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","laser1010");
    &AD_object_nonexist($ldap,$root_dse,"computer","LASER1010\$");
    &AD_test_nondns($res,"laser1010");

    &AD_object_nonexist($ldap,$root_dse,"examaccount","c001p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","C001P01\$");
    &AD_test_nondns($res,"c001p01");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","c002p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","C002P01\$");
    &AD_test_nondns($res,"c002p01");

    ############################################################
    # bsz
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-j1008p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-J1008P01\$");
    &AD_test_nondns($res,"bsz-j1008p01");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-j1008p02");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-J1008P02\$");
    &AD_test_nondns($res,"bsz-j1008p02");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-laser1008");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-LASER1008\$");
    &AD_test_nondns($res,"bsz-laser1008");

    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-j1010p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-J1010P01\$");
    &AD_test_nondns($res,"bsz-j1010p01");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-j1010p02");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-J1010P02\$");
    &AD_test_nondns($res,"bsz-j1010p02");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-laser1010");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-LASER1010\$");
    &AD_test_nondns($res,"bsz-laser1010");

    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-d001p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-D001P01\$");
    &AD_test_nondns($res,"bsz-d001p01");
    &AD_object_nonexist($ldap,$root_dse,"examaccount","bsz-d002p01");
    &AD_object_nonexist($ldap,$root_dse,"computer","BSZ-D002P01\$");
    &AD_test_nondns($res,"bsz-d002p01");

    &AD_computers_any($ldap,$root_dse);
    &AD_examaccounts_any($ldap,$root_dse);
    &AD_dnsnodes_any($ldap,$root_dse);
    &AD_rooms_any($ldap,$root_dse);
}



############################################################
# Delete Accounts
############################################################


############################################################
# Check deletion
############################################################


## --test-kill-ea  
#if ($test_kill_ea==1){
#
#&AD_object_nonexist($ldap,$root_dse,"user","j1010p01");
#&AD_object_nonexist($ldap,$root_dse,"user","j1010p02");
#
#}

&AD_unbind_admin($ldap);



