#!/usr/bin/perl -w
# This script (sophomorix-test-3) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 time_stamp_AD 
                                 get_passwd_charlist
                                 get_plain_password
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_school_add
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_group_create
                                 AD_group_addmember
                                 AD_user_kill
                                 AD_dns_get
                                 AD_object_search
                                 AD_debug_logdump
                                 AD_get_name_tokened
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_object_nonexist
                                 AD_test_object
                                 run_command
                                 );

$Conf::log_level=1;
my $help=0;
my $full=0;
my $add_pro=0;
my $test_add_pro=0;

my $mod_pro=0;
my $test_mod_pro=0;

my $kill_pro=0;
my $test_kill_pro=0;

my $verbose_options="";

my $testopt=GetOptions(
           "help|h" => \$help,
           "full|f" => \$full,
           "verbose|v+" => \$Conf::log_level,
           "add-pro" => \$add_pro,
           "test-add-pro" => \$test_add_pro,
           "mod-pro" => \$mod_pro,
           "test-mod-pro" => \$test_mod_pro,
           "kill-pro" => \$kill_pro,
           "test-kill-pro" => \$test_kill_pro,
  );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);



if ($Conf::log_level==1){
    $verbose_options="";
} elsif ($Conf::log_level==2){
    $verbose_options="-v";
} elsif ($Conf::log_level==3){
    $verbose_options="-vv";
}




my ($ldap,$root_dse) = &AD_bind_admin();
my $root_dns=&AD_dns_get($root_dse);

my $testdata="/usr/share/sophomorix-developer/testdata";


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-test-3 tests the addition and modifications of projects.

Options
  -h  / --help

  Projects:
  sophomorix-test-3 --add-pro  
    add some projects
  sophomorix-test-3 --test-add-pro
    test the added projects

  sophomorix-test-3 --mod-pro
    modify added projects
  sophomorix-test-3 --test-mod-pro
    test modified projects

  sophomorix-test-3 --kill-pro
    kill all added projects
  sophomorix-test-3 --test-kill-pro
    test killed projects

');
   print "\n";
   exit;
}





############################################################
# Check preliminaries
############################################################

# --full
if ($full==1){
    $add_pro=1;
    $mod_pro=1;
    $kill_pro=1;
    $test_add_pro=1;
    $test_mod_pro=1;
    $test_kill_pro=1;
}

my $file_add_test=$testdata."/sophomorix.add-30";
my $file_add=$DevelConf::path_result."/sophomorix.add";
my $file_kill=$DevelConf::path_result."/sophomorix.kill";
my $file_kill_test=$testdata."/sophomorix.kill-30";


############################################################
# Add projects
############################################################
# --add-pro  
if ($add_pro==1){
    # adding users
    &run_command("cp -v $file_add_test $file_add");
    &run_command("sophomorix-add $verbose_options");

    # projects in OU=bsz
    &run_command("sophomorix-project $verbose_options --create -p mathe23 --school bsz");
    &run_command("sophomorix-project $verbose_options --create -p Chemie-AG23 --school bsz --description 'Chemie AG des Gymnasiums' --addquota 100+60 --addmailquota 200 --mailalias --maillist --status G --join --nohide --maxmembers 36 --admins oe23,wu23 --members maiersa23,muellegr23 --membergroups bsz-m7ab,bsz-m8cd --admingroups uni-teachers");
    # projects in OU=default-school
    &run_command("sophomorix-project $verbose_options --create -p mathe23");
    &run_command("sophomorix-project $verbose_options --create -p Chemie-AG23");

    # groups in OU=bsz
    &run_command("sophomorix-group $verbose_options --create --group super6 --school bsz");
    &run_command("sophomorix-group $verbose_options --create --group super7 --school bsz");
    # groups in OU=default-school
    &run_command("sophomorix-group $verbose_options --create --group super12");
    &run_command("sophomorix-group $verbose_options --create --group super13");
}

############################################################
# Test added projects
############################################################
# --test-add-pro  
if ($test_add_pro==1){
    ##### Testing the users
    # maiersa23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=maiersa23,OU=bsz-m7ab,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Sarina Maier",
                   givenName=>"Sarina",
                   name=>"maiersa23",
                   sAMAccountname=>"maiersa23",
                   uidNumber=>"-1",
                   sn=>"Maier",
                   userPrincipalName => "maiersa23@".$root_dns,
                   sophomorixAdminClass => "bsz-m7ab",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Sarina",
                   sophomorixSurnameASCII  => "Maier",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m7ab,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m7ab,OU=bsz-m7ab,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-m7ab",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "bsz-students,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });


    # muellegr23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=muellegr23,OU=bsz-m7ab,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Gregor Müller",
                   givenName=>"Gregor",
                   name=>"muellegr23",
                   sAMAccountname=>"muellegr23",
                   uidNumber=>"-1",
                   sn=>"Müller",
                   userPrincipalName => "muellegr23@".$root_dns,
                   sophomorixAdminClass => "bsz-m7ab",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Gregor",
                   sophomorixSurnameASCII  => "Mueller",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m7ab,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m7ab,OU=bsz-m7ab,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-m7ab",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "bsz-students,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });


    # jonsonad23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=jonsonad23,OU=bsz-m8cd,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Aðalráður Jónsson",
                   givenName=>"Aðalráður",
                   name=>"jonsonad23",
                   sAMAccountname=>"jonsonad23",
                   uidNumber=>"-1",
                   sn=>"Jónsson",
                   userPrincipalName => "jonsonad23@".$root_dns,
                   sophomorixAdminClass => "bsz-m8cd",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Adalradur",
                   sophomorixSurnameASCII  => "Jonsson",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m8cd",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m8cd,OU=bsz-m8cd,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-m8cd",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "bsz-students,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });


    # samardze23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=samardze23,OU=bsz-m8cd,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Željko Samardžić",
                   givenName=>"Željko",
                   name=>"samardze23",
                   sAMAccountname=>"samardze23",
                   uidNumber=>"-1",
                   sn=>"Samardžić",
                   userPrincipalName => "samardze23@".$root_dns,
                   sophomorixAdminClass => "bsz-m8cd",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Zeljko",
                   sophomorixSurnameASCII  => "Samardzic",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-m8cd",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-m8cd,OU=bsz-m8cd,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-m8cd",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "bsz-students,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-students,OU=bsz-students,OU=Students,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });


    # oe23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=oe23,OU=bsz-teachers,OU=Teachers,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Gökhan Ömür",
                   givenName=>"Gökhan",
                   name=>"oe23",
                   sAMAccountname=>"oe23",
                   uidNumber=>"-1",
                   sn=>"Ömür",
                   userPrincipalName => "oe23@".$root_dns,
                   sophomorixAdminClass => "bsz-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Goekhan",
                   sophomorixSurnameASCII  => "Oemuer",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-teachers,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-teachers,OU=bsz-teachers,OU=Teachers,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-teachers",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"teacherclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-teachers",
                  });


    # wu23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=wu23,OU=bsz-teachers,OU=Teachers,OU=bsz,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Désirée Würth",
                   givenName=>"Désirée",
                   name=>"wu23",
                   sAMAccountname=>"wu23",
                   uidNumber=>"-1",
                   sn=>"Würth",
                   userPrincipalName => "wu23@".$root_dns,
                   sophomorixAdminClass => "bsz-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Desiree",
                   sophomorixSurnameASCII  => "Wuerth",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "bsz",
                   sophomorixSchoolname => "bsz",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "bsz-teachers,p_bsz-Chemie-AG23",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-teachers,OU=bsz-teachers,OU=Teachers,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-teachers",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"teacherclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-teachers",
                  });


    # blackmri23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=blackmri23,OU=uni-12abc,OU=Students,OU=uni,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Richard Blackmore",
                   givenName=>"Richard",
                   name=>"blackmri23",
                   sAMAccountname=>"blackmri23",
                   uidNumber=>"-1",
                   sn=>"Blackmore",
                   userPrincipalName => "blackmri23@".$root_dns,
                   sophomorixAdminClass => "uni-12abc",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Richard",
                   sophomorixSurnameASCII  => "Blackmore",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "uni",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-12abc",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-12abc,OU=uni-12abc,OU=Students,OU=uni,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"uni-12abc",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "uni-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-students,OU=uni-students,OU=Students,OU=uni,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"uni-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });


    # lordjo23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=lordjo23,OU=uni-12abc,OU=Students,OU=uni,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Jon Lord",
                   givenName=>"Jon",
                   name=>"lordjo23",
                   sAMAccountname=>"lordjo23",
                   uidNumber=>"-1",
                   sn=>"Lord",
                   userPrincipalName => "lordjo23@".$root_dns,
                   sophomorixAdminClass => "uni-12abc",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster23!",
                   sophomorixFirstnameASCII => "Jon",
                   sophomorixSurnameASCII  => "Lord",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "uni",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-12abc",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-12abc,OU=uni-12abc,OU=Students,OU=uni,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"uni-12abc",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "uni-students",
                  });
    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-students,OU=uni-students,OU=Students,OU=uni,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"uni-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });


    # kep23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=kep23,OU=uni-teachers,OU=Teachers,OU=uni,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Johannes Kepler",
                   givenName=>"Johannes",
                   name=>"kep23",
                   sAMAccountname=>"kep23",
                   uidNumber=>"-1",
                   sn=>"Kepler",
                   userPrincipalName => "kep23@".$root_dns,
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster23!",
                   sophomorixFirstnameASCII => "Johannes",
                   sophomorixSurnameASCII  => "Kepler",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "uni",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-teachers,OU=uni-teachers,OU=Teachers,OU=uni,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"uni-teachers",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"teacherclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-teachers,p_bsz-Chemie-AG23",
                  });


    # gal23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=gal23,OU=uni-teachers,OU=Teachers,OU=uni,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Galileo Galilei",
                   givenName=>"Galileo",
                   name=>"gal23",
                   sAMAccountname=>"gal23",
                   uidNumber=>"-1",
                   sn=>"Galilei",
                   userPrincipalName => "gal23@".$root_dns,
                   sophomorixAdminClass => "uni-teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Galileo",
                   sophomorixSurnameASCII  => "Galilei",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "uni",
                   sophomorixSchoolname => "uni",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "uni-teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=uni-teachers,OU=uni-teachers,OU=Teachers,OU=uni,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"uni-teachers",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"teacherclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-teachers,p_bsz-Chemie-AG23",
                  });
    # schneima23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=schneima23,OU=s6ade,OU=Students,OU=default-school,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Marina Schneider",
                   givenName=>"Marina",
                   name=>"schneima23",
                   sAMAccountname=>"schneima23",
                   uidNumber=>"-1",
                   sn=>"Schneider",
                   userPrincipalName => "schneima23@".$root_dns,
                   sophomorixAdminClass => "s6ade",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "Muster!",
                   sophomorixFirstnameASCII => "Marina",
                   sophomorixSurnameASCII  => "Schneider",
                   sophomorixRole => "student",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "default-school",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "s6ade",
                  });
    ##### Testing the users class
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=s6ade,OU=s6ade,OU=Students,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"s6ade",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"adminclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "students",
                  });
    ##### Testing the users ou-students group    ##### Testing the users ou-students group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=students,OU=students,OU=Students,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-students",
                  });
    # sch23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=sch23,OU=teachers,OU=Teachers,OU=default-school,OU=SCHOOLS,".$root_dse,
                   #####
                   displayName=>"Michael Schäfer",
                   givenName=>"Michael",
                   name=>"sch23",
                   sAMAccountname=>"sch23",
                   uidNumber=>"-1",
                   sn=>"Schäfer",
                   userPrincipalName => "sch23@".$root_dns,
                   sophomorixAdminClass => "teachers",
                   sophomorixExitAdminClass => "unknown",
                   sophomorixFirstPassword => "LinuxMuster!",
                   sophomorixFirstnameASCII => "Michael",
                   sophomorixSurnameASCII  => "Schaefer",
                   sophomorixRole => "teacher",
                   sophomorixSchoolPrefix => "---",
                   sophomorixSchoolname => "default-school",
                   sophomorixCreationDate => "exists",
                   sophomorixTolerationDate => "default",
                   sophomorixDeactivationDate => "default",
                   memberOf => "teachers",
                  });
    ##### Testing the users ou-teachers group
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=teachers,OU=teachers,OU=Teachers,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"teachers",
                   gidNumber=>"-1",
                   sophomorixHidden=>"FALSE",
                   memberOf => "global-teachers",
                  });

    ##### Testing the global groups
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-wifi,OU=global-wifi,OU=Groups,OU=GLOBAL,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"global-wifi",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouglobalclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                   member => "bsz-wifi,uni-wifi,wifi,",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-internet,OU=global-internet,OU=Groups,OU=GLOBAL,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"global-internet",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"ouglobalclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                   member => "bsz-internet,uni-internet,internet,",
                  });
    # &AD_test_object({ldap=>$ldap,
    #                dn=>"CN=global-examaccounts,OU=global-examaccounts,OU=ExamAccounts,OU=GLOBAL,OU=SCHOOLS,".$root_dse,
    #                sAMAccountname=>"global-examaccounts",
    #                gidNumber=>"-1",
    #                sophomorixCreationDate => "exists",
    #                sophomorixStatus=>"P",
    #                sophomorixType=>"ouglobalclass",
    #                sophomorixHidden=>"FALSE",
    #                memberOf => "",
    #                member => "bsz-examaccounts,uni-examaccounts,examaccounts,",
    #               });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-students,OU=global-students,OU=Groups,OU=GLOBAL,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"global-students",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"globalclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                   member => "bsz-students,uni-students,students",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=global-teachers,OU=global-teachers,OU=Groups,OU=GLOBAL,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"global-teachers",
                   gidNumber=>"-1",
                   sophomorixCreationDate => "exists",
                   sophomorixStatus=>"P",
                   sophomorixType=>"globalclass",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                   member => "bsz-teachers,uni-teachers,teachers",
                  });


    # Projects
    # p_Chemie-AG23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_Chemie-AG23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_Chemie-AG23",
                   gidNumber=>"-1",
                   description=>"p_Chemie-AG23",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # p_bsz-Chemie-AG23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_bsz-Chemie-AG23,OU=Projects,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_bsz-Chemie-AG23",
                   gidNumber=>"-1",
                   description=>"Chemie AG des Gymnasiums",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+60",
                   sophomorixAddMailQuota=>"200",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"G",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"36",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "oe23,wu23",
                   sophomorixMembers => "maiersa23,muellegr23",
                   sophomorixAdminGroups => "uni-teachers",
                   sophomorixMemberGroups => "bsz-m7ab,bsz-m8cd",
                   member => "oe23,wu23,maiersa23,muellegr23,uni-teachers,bsz-m7ab,bsz-m8cd",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # p_mathe23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"p_mathe23",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # p_bsz-mathe23
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_bsz-mathe23,OU=Projects,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_bsz-mathe23",
                   gidNumber=>"-1",
                   description=>"p_bsz-mathe23",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # groups
    # bsz-super6
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-super6,OU=Projects,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-super6",
                   gidNumber=>"-1",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # bsz-super7
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-super7,OU=Projects,OU=bsz,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"bsz-super7",
                   gidNumber=>"-1",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # super12
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=super12,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"super12",
                   gidNumber=>"-1",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
    # super13
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=super13,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"super13",
                   gidNumber=>"-1",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixHidden=>"FALSE",
                   memberOf => "",
                  });
}




############################################################
# Modify added projects
############################################################
# --mod-pro  
if ($mod_pro==1){

    # --description
    &run_command("sophomorix-project $verbose_options -p mathe23 --description 'Mathe23 Grundschule'");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --addquota
    &run_command("sophomorix-project $verbose_options -p mathe23 --addquota 100+300");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --addmailquota 
    &run_command("sophomorix-project $verbose_options -p mathe23 --addmailquota 366");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --mailalias
    &run_command("sophomorix-project $verbose_options -p mathe23 --mailalias");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --maillist
    &run_command("sophomorix-project $verbose_options -p mathe23 --maillist");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --status
    &run_command("sophomorix-project $verbose_options -p mathe23 --status S");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --join
    &run_command("sophomorix-project $verbose_options -p mathe23 --join");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
    # --hide
    &run_command("sophomorix-project $verbose_options -p mathe23 --hide");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"TRUE",
                   member => "",
                   memberOf => "",
                  });
    # --maxmembers
    &run_command("sophomorix-project $verbose_options -p mathe23 --maxmembers 16");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"TRUE",
                   member => "",
                   memberOf => "",
                  });

    # --creationdate
    &run_command("sophomorix-project $verbose_options -p mathe23 --creationdate 19880529093330.0Z");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"TRUE",
                   member => "",
                   memberOf => "",
                  });


    # --admins
    &run_command("sophomorix-project $verbose_options -p mathe23 --admins maiersa23,muellegr23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,muellegr23",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23",
                   memberOf => "",
                  });
    # --members
    &run_command("sophomorix-project $verbose_options -p mathe23 --members kep23,wu23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,muellegr23",
                   sophomorixMembers => "kep23,wu23",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,kep23,wu23",
                   memberOf => "",
                  });
    # --admingroups
    &run_command("sophomorix-project $verbose_options -p mathe23 --admingroups super12,bsz-super6");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,muellegr23",
                   sophomorixMembers => "kep23,wu23",
                   sophomorixAdminGroups => "super12,bsz-super6",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,kep23,wu23,super12,bsz-super6",
                   memberOf => "",
                  });
    # --membergroups
    &run_command("sophomorix-project $verbose_options -p mathe23 --membergroups super13,bsz-super7");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,muellegr23",
                   sophomorixMembers => "kep23,wu23",
                   sophomorixAdminGroups => "super12,bsz-super6",
                   sophomorixMemberGroups => "super13,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,kep23,wu23,super12,bsz-super6,super13,bsz-super7",
                   memberOf => "",
                  });


    # --admins (2, delete)
    &run_command("sophomorix-project $verbose_options -p mathe23 --admins maiersa23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "kep23,wu23",
                   sophomorixAdminGroups => "super12,bsz-super6",
                   sophomorixMemberGroups => "super13,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,kep23,wu23,super12,bsz-super6,super13,bsz-super7",
                   memberOf => "",
                  });
    # --members (2, delete)
    &run_command("sophomorix-project $verbose_options -p mathe23 --members muellegr23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12,bsz-super6",
                   sophomorixMemberGroups => "super13,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super6,super13,bsz-super7",
                   memberOf => "",
                  });
    # --admingroups (2, delete)
    &run_command("sophomorix-project $verbose_options -p mathe23 --admingroups super12");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "super13,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,super13,bsz-super7",
                   memberOf => "",
                  });
    # --membergroups (2, delete)
    &run_command("sophomorix-project $verbose_options -p mathe23 --membergroups bsz-super7");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });


    # --admins (3, nonexisting user)
    &run_command("sophomorix-project $verbose_options -p mathe23 --admins maiersa23,nonexuser1");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --members (3, nonexisting user)
    &run_command("sophomorix-project $verbose_options -p mathe23 --members muellegr23,nonexuser2");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
    # --admingroups (3, nonexisting user)
    &run_command("sophomorix-project $verbose_options -p mathe23 --admingroups super12,nonexgroup1");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --membergroups (3, nonexisting user)
    &run_command("sophomorix-project $verbose_options -p mathe23 --membergroups bsz-super7,nonexgroup2");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });


   # --admins (4, group instead of user)
    &run_command("sophomorix-project $verbose_options -p mathe23 --admins maiersa23,bsz-super6");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --members (4, group instead of user)
    &run_command("sophomorix-project $verbose_options -p mathe23 --members muellegr23,super13");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --admingroups (4, user instead of group)
    &run_command("sophomorix-project $verbose_options -p mathe23 --admingroups kep23,super12");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --membergroups (4, user instead of group)
    &run_command("sophomorix-project $verbose_options -p mathe23 --membergroups wu23,bsz-super7");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });


   # --addadmins (1 adding to existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --addadmins wu23,oe23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,wu23,oe23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "wu23,oe23,maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --addmembers (1 adding to existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --addmembers samardze23,schneima23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,wu23,oe23",
                   sophomorixMembers => "muellegr23,samardze23,schneima23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "wu23,oe23,maiersa23,muellegr23,samardze23,schneima23,super12,bsz-super7",
                   memberOf => "",
                  });
   # --addadmingroups (1 adding to existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --addadmingroups super13");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,wu23,oe23",
                   sophomorixMembers => "muellegr23,samardze23,schneima23",
                   sophomorixAdminGroups => "super12,super13",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "wu23,oe23,maiersa23,muellegr23,samardze23,schneima23,super12,super13,bsz-super7",
                   memberOf => "",
                  });
   # --addmembergroups (1 adding to existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --addmembergroups bsz-super6");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23,wu23,oe23",
                   sophomorixMembers => "muellegr23,samardze23,schneima23",
                   sophomorixAdminGroups => "super12,super13",
                   sophomorixMemberGroups => "bsz-super6,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "wu23,oe23,maiersa23,muellegr23,samardze23,schneima23,super12,super13,bsz-super6,bsz-super7",
                   memberOf => "",
                  });


   # --removeadmins (1 removing from existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --removeadmins wu23,oe23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23,samardze23,schneima23",
                   sophomorixAdminGroups => "super12,super13",
                   sophomorixMemberGroups => "bsz-super6,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,samardze23,schneima23,super12,super13,bsz-super6,bsz-super7",
                   memberOf => "",
                  });
   # --removemembers (1 removing from existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --removemembers samardze23,schneima23");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12,super13",
                   sophomorixMemberGroups => "bsz-super6,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,super13,bsz-super6,bsz-super7",
                   memberOf => "",
                  });
   # --removeadmingroups (1 removing from existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --removeadmingroups super13");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super6,bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super6,bsz-super7",
                   memberOf => "",
                  });
   # --removemembergroups (1 removing from existing value)
    &run_command("sophomorix-project $verbose_options -p mathe23 --removemembergroups bsz-super6");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathe23 Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "198",
                   sophomorixAdmins => "maiersa23",
                   sophomorixMembers => "muellegr23",
                   sophomorixAdminGroups => "super12",
                   sophomorixMemberGroups => "bsz-super7",
                   sophomorixHidden=>"TRUE",
                   member => "maiersa23,muellegr23,super12,bsz-super7",
                   memberOf => "",
                  });



    # setting all back in one command
    &run_command("sophomorix-project $verbose_options -p mathe23 --nojoin --nohide --addquota --- --addmailquota --- --nomailalias --nomaillist --status P --maxmembers 0 --creationdate 20160529093330.0Z --description 'Mathematik' --admins \"\" --members \"\" --admingroups \"\" --membergroups \"\"");
    # checking if all is set back
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe23,OU=Projects,OU=default-school,OU=SCHOOLS,".$root_dse,
                   sAMAccountname=>"p_mathe23",
                   gidNumber=>"-1",
                   description=>"Mathematik",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   sophomorixAdmins => "",
                   sophomorixMembers => "",
                   sophomorixAdminGroups => "",
                   sophomorixMemberGroups => "",
                   sophomorixHidden=>"FALSE",
                   member => "",
                   memberOf => "",
                  });
}

############################################################
#  Test modified  projects
############################################################
# --test-mod-pro  
if ($test_mod_pro==1){
    print "\nNothing to do so far (--test-mod-pro), ...\n\n";
}




############################################################
# Kill projects
############################################################
# --kill-pro  
if ($kill_pro==1){
    &run_command("cp -v $file_kill_test $file_kill");
    &run_command("sophomorix-kill -i");
    &run_command("sophomorix-kill $verbose_options");
    # projects
    &run_command("sophomorix-project $verbose_options --kill -p mathe23 --school bsz");
    &run_command("sophomorix-project $verbose_options --kill -p mathe23");
    &run_command("sophomorix-project $verbose_options --kill -p Chemie-AG23 --school bsz");
    &run_command("sophomorix-project $verbose_options --kill -p Chemie-AG23");
    # groups
    &run_command("sophomorix-group $verbose_options --kill --group super6 --school bsz");
    &run_command("sophomorix-group $verbose_options --kill --group super7 --school bsz");
    &run_command("sophomorix-group $verbose_options --kill --group super12");
    &run_command("sophomorix-group $verbose_options --kill --group super13");

}

############################################################
#  Test killed  users, groups, projects
############################################################
# --test-kill-pro  
if ($test_kill_pro==1){
    # users
    &AD_object_nonexist($ldap,$root_dse,"user","maiersa23");
    &AD_object_nonexist($ldap,$root_dse,"user","muellegr23");
    &AD_object_nonexist($ldap,$root_dse,"user","jonsonad23");
    &AD_object_nonexist($ldap,$root_dse,"user","samardze23");
    &AD_object_nonexist($ldap,$root_dse,"user","oe23");
    &AD_object_nonexist($ldap,$root_dse,"user","wu23");
    &AD_object_nonexist($ldap,$root_dse,"user","lordjo23");
    &AD_object_nonexist($ldap,$root_dse,"user","blackmri23");
    &AD_object_nonexist($ldap,$root_dse,"user","kep23");
    &AD_object_nonexist($ldap,$root_dse,"user","gal23");
    &AD_object_nonexist($ldap,$root_dse,"user","schneima23");
    &AD_object_nonexist($ldap,$root_dse,"user","sch23");
    # projects
    &AD_object_nonexist($ldap,$root_dse,"group","p_bsz-mathe23");
    &AD_object_nonexist($ldap,$root_dse,"group","p_mathe23");
    &AD_object_nonexist($ldap,$root_dse,"group","p_bsz-Chemie-AG23");
    &AD_object_nonexist($ldap,$root_dse,"group","p_Chemie-AG23");
    # groups
    &AD_object_nonexist($ldap,$root_dse,"group","bsz-super6");
    &AD_object_nonexist($ldap,$root_dse,"group","bsz-super7");
    &AD_object_nonexist($ldap,$root_dse,"group","super12");
    &AD_object_nonexist($ldap,$root_dse,"group","super13");
}






&AD_unbind_admin($ldap);



