#!/usr/bin/perl -w
# This script (sophomorix-test-3) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# Bibliotheken
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 check_options
                                 time_stamp_AD 
                                 get_passwd_charlist
                                 get_plain_password
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_ou_add
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_group_create
                                 AD_group_addmember
                                 AD_user_kill
                                 AD_object_search
                                 AD_debug_logdump
                                 AD_get_name_tokened
                                    );
use Sophomorix::SophomorixTest qw(
                                 AD_object_nonexist
                                 AD_test_object
                                 );

$Conf::log_level=1;
my $help=0;
my $full=0;
my $add_pro=0;
my $test_add_pro=0;

my $mod_pro=0;
my $test_mod_pro=0;

my $kill_pro=0;
my $test_kill_pro=0;

my $verbose_options="";

my $testopt=GetOptions(
           "help|h" => \$help,
           "full|f" => \$full,
           "verbose|v+" => \$Conf::log_level,
           "add-pro" => \$add_pro,
           "test-add-pro" => \$test_add_pro,
           "mod-pro" => \$mod_pro,
           "test-mod-pro" => \$test_mod_pro,
           "kill-pro" => \$kill_pro,
           "test-kill-pro" => \$test_kill_pro,
  );


# Prüfen, ob Optionen erkannt wurden, sonst Abbruch
&check_options($testopt);



if ($Conf::log_level==1){
    $verbose_options="";
} elsif ($Conf::log_level==2){
    $verbose_options="-v";
} elsif ($Conf::log_level==3){
    $verbose_options="-vv";
}




my ($ldap,$root_dse) = &AD_bind_admin();

my $testdata="/usr/share/sophomorix-developer/testdata";


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-test-3 tests the addition of ExamAccounts and workstation accounts.

Options
  -h  / --help

  Projects:
  sophomorix-test-3 --add-pro  
    add some projects
  sophomorix-test-3 --test-add-pro
    test the added projects

  sophomorix-test-3 --mod-pro
    modify added projects
  sophomorix-test-3 --test-mod-pro
    test modified projects

  sophomorix-test-3 --kill-pro
    kill all added projects
  sophomorix-test-3 --test-kill-pro
    test killed projects

');
   print "\n";
   exit;
}





############################################################
# Check preliminaries
############################################################

# --full
if ($full==1){
    $add_pro=1;
    $mod_pro=1;
    $kill_pro=1;
    $test_add_pro=1;
    $test_mod_pro=1;
    $test_kill_pro=1;
}



############################################################
# Add projects
############################################################
# --add-pro  
if ($add_pro==1){
    # projects in OU=BSZLEO
    system("sophomorix-project $verbose_options --create -p mathe --ou BSZLEO --school-token bsz");
    system("sophomorix-project $verbose_options --create -p Chemie-AG --ou BSZLEO --school-token bsz --description 'Chemie AG des Gymnasiums' --addquota 100+60 --addmailquota 200 --mailalias --maillist --status G --join --maxmembers 36");
    # projects in OU=SCHOOL
    system("sophomorix-project $verbose_options --create -p mathe");
    system("sophomorix-project $verbose_options --create -p Chemie-AG");
    # groups in OU=BSZLEO
    system("sophomorix-group $verbose_options --create --group super6 --ou BSZLEO --school-token bsz");
    system("sophomorix-group $verbose_options --create --group super7 --ou BSZLEO --school-token bsz");
    # groups in OU=SCHOOL
    system("sophomorix-group $verbose_options --create --group super12");
    system("sophomorix-group $verbose_options --create --group super13");
}

############################################################
# Test added projects
############################################################
# --test-add-pro  
if ($test_add_pro==1){
    # Projects
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_Chemie-AG,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_Chemie-AG",
                   description=>"p_Chemie-AG",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_bsz-Chemie-AG,OU=Projects,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"p_bsz-Chemie-AG",
                   description=>"Chemie AG des Gymnasiums",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+60",
                   sophomorixAddMailQuota=>"200",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"G",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"36",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"p_mathe",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_bsz-mathe,OU=Projects,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"p_bsz-mathe",
                   description=>"p_bsz-mathe",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
    # groups
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-super6,OU=Projects,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-super6",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=bsz-super7,OU=Projects,OU=BSZLEO,".$root_dse,
                   sAMAccountname=>"bsz-super7",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=super12,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"super12",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=super13,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"super13",
                   description=>"Created by sophomorix-group",
                   sophomorixType=>"sophomorix-group",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
}




############################################################
# Modify added projects
############################################################
# --mod-pro  
if ($mod_pro==1){

    # --description
    system("sophomorix-project $verbose_options -p mathe --description 'Mathe Grundschule'");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --addquota
    system("sophomorix-project $verbose_options -p mathe --addquota 100+300");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --addmailquota 
    system("sophomorix-project $verbose_options -p mathe --addmailquota 366");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --mailalias
    system("sophomorix-project $verbose_options -p mathe --mailalias");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --maillist
    system("sophomorix-project $verbose_options -p mathe --maillist");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --status
    system("sophomorix-project $verbose_options -p mathe --status S");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --join
    system("sophomorix-project $verbose_options -p mathe --join");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });

    # --maxmembers
    system("sophomorix-project $verbose_options -p mathe --maxmembers 16");
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"Mathe Grundschule",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"100+300",
                   sophomorixAddMailQuota=>"366",
                   sophomorixMailAlias=>"TRUE",
                   sophomorixMailList=>"TRUE",
                   sophomorixStatus=>"S",
                   sophomorixJoinable=>"TRUE",
                   sophomorixMaxMembers=>"16",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });




    # setting all back in one command
    system("sophomorix-project $verbose_options -p mathe --nojoin --addquota --- --addmailquota --- --nomailalias --nomaillist --status P --maxmembers 0 --description p_mathe");
    # checking if all is set back
    &AD_test_object({ldap=>$ldap,
                   dn=>"CN=p_mathe,OU=Projects,OU=SCHOOL,".$root_dse,
                   sAMAccountname=>"p_mathe",
                   description=>"p_mathe",
                   sophomorixType=>"project",
                   sophomorixAddQuota=>"---",
                   sophomorixAddMailQuota=>"---",
                   sophomorixMailAlias=>"FALSE",
                   sophomorixMailList=>"FALSE",
                   sophomorixStatus=>"P",
                   sophomorixJoinable=>"FALSE",
                   sophomorixMaxMembers=>"0",
                   sophomorixCreationDate => "exists",
                   memberOf => "",
                   not_memberOf => "teachers",
                  });
}

############################################################
#  Test modified  projects
############################################################
# --test-mod-pro  
if ($test_mod_pro==1){
    print "\nNothing to do so far (--test-mod-pro), ...\n\n";
}




############################################################
# Kill projects
############################################################
# --kill-pro  
if ($kill_pro==1){
    # projects
    system("sophomorix-project $verbose_options --kill -p mathe --ou BSZLEO --school-token bsz");
    system("sophomorix-project $verbose_options --kill -p mathe");
    system("sophomorix-project $verbose_options --kill -p Chemie-AG --ou BSZLEO --school-token bsz");
    system("sophomorix-project $verbose_options --kill -p Chemie-AG");
    # groups
    system("sophomorix-group $verbose_options --kill --group super6 --ou BSZLEO --school-token bsz");
    system("sophomorix-group $verbose_options --kill --group super7 --ou BSZLEO --school-token bsz");
    system("sophomorix-group $verbose_options --kill --group super12");
    system("sophomorix-group $verbose_options --kill --group super13");

}

############################################################
#  Test killed  projects
############################################################
# --test-kill-pro  
if ($test_kill_pro==1){
    &AD_object_nonexist($ldap,$root_dse,"group","p_bsz-mathe");
    &AD_object_nonexist($ldap,$root_dse,"group","p_mathe");
    &AD_object_nonexist($ldap,$root_dse,"group","p_bsz-Chemie-AG");
    &AD_object_nonexist($ldap,$root_dse,"group","p_Chemie-AG");
    &AD_object_nonexist($ldap,$root_dse,"group","bsz-super6");
    &AD_object_nonexist($ldap,$root_dse,"group","bsz-super7");
    &AD_object_nonexist($ldap,$root_dse,"group","super12");
    &AD_object_nonexist($ldap,$root_dse,"group","super13");
}






&AD_unbind_admin($ldap);



