#!/usr/bin/perl -w
# This script (sophomorix-mail) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# modules
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use List::MoreUtils qw(uniq);
use HTML::TableExtract;
use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useqq = 1;
$Data::Dumper::Terse = 1; 
use Net::LDAP;
use JSON;
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 time_stamp_AD
                                 time_stamp_file
                                 unlock_sophomorix
                                 lock_sophomorix
                                 log_script_start
                                 log_script_end
                                 log_script_exit
                                 backup_auk_file
                                 get_passwd_charlist
                                 get_plain_password
                                 check_options
                                 config_sophomorix_read
                                 result_sophomorix_init
                                 result_sophomorix_add
                                 result_sophomorix_add_summary
                                 result_sophomorix_check_exit
                                 result_sophomorix_print
                                 remove_from_list    
                                 json_dump
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_school_create
                                 AD_bind_admin
                                 AD_dns_get
                                 AD_get_user
                                 AD_get_quota
                                 AD_user_kill
                                 AD_unbind_admin
                                 AD_object_search
                                 AD_user_create
                                 AD_user_update
                                 AD_user_setquota
                                 AD_group_create
                                 AD_group_kill
                                 AD_group_addmember
                                 AD_get_schoolname
                                 AD_get_name_tokened
                                 AD_group_update
                                 AD_project_sync_members
                                 AD_dn_fetch_multivalue
                                 AD_get_passwd
                                 get_forbidden_logins
                                    );
my @arguments = @ARGV;

my $time_stamp_file=&time_stamp_file();
my $time_stamp_AD=&time_stamp_AD();

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
# Variablen für Optionen
$Conf::log_level=1;

my $help=0;
my $info=0;
my $json=0;
my $school="";
my $user="";
$Conf::log_level=1;

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "info|i" => \$info,
           "json|j+" => \$json,
           "verbose|v+" => \$Conf::log_level,
           "school|share|s=s" => \$school,
           "user|u=s" => \$user,
          );

my %sophomorix_result=&result_sophomorix_init("sophomorix-mail");
# Prüfen, ob Optionen erkannt wurden
&check_options($testopt,\%sophomorix_result,$json);

# Reading Configuration
my ($ldap,$root_dse) = &AD_bind_admin(\@arguments,\%sophomorix_result,$json);
my $root_dns=&AD_dns_get($root_dse);
my %sophomorix_config=&config_sophomorix_read($ldap,$root_dse,\%sophomorix_result);
my ($smb_admin_pass)=&AD_get_passwd($DevelConf::sophomorix_file_admin,
                                     $DevelConf::secret_file_sophomorix_file_admin);


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-mail calcultes mailinglist and does  ... nothing so fal

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose


Show the mailaccounts and maillists that should be created 
  -i  / --info

Dump belwue Data only

Please see the sophomorix-mail(8) man pages for full documentation
');
   print "\n";
   exit;
}




# create sharelist from options
# --school <school>/--share <share>
my @sharelist=();
if ($school ne ""){
    if (exists $sophomorix_config{'samba'}{'net_conf_list'}{$school}){
	push @sharelist,$school;
    } else {
        print "\nERROR: $school is not a SMB-share!\n\n";
	exit;
    }
} else {
    # without option use only school shares
    @sharelist=@{ $sophomorix_config{'LISTS'}{'SCHOOLS'} };
}




# --user user1,user2
my @userlist=();
if ($user ne ""){
    @userlist=split(/,/,$user);
}



my $ref_mail=&AD_get_quota({ldap=>$ldap,
                             root_dse=>$root_dse,
                             root_dns=>$root_dns,
                             sophomorix_config=>\%sophomorix_config,
                           });

# print Dumper($ref_mail);
# print Dumper($ref_mail->{'QUOTA'}{'USERS'}{'blackmri42'});
# print Dumper($ref_mail->{'QUOTA'}{'USERS'}{'lordjo42'});


if ($info==1){
    &json_dump({json => $json,
                jsoninfo => "MAIL",
                jsoncomment => "sophomorix mail",
                object_name => $school,
                log_level => $Conf::log_level,
                hash_ref=>$ref_mail,
                sophomorix_config=>\%sophomorix_config,
              });

    exit;
}

################################################################################
# continue with the calculated mail from $ref_mail
################################################################################
my %mailconf=();

# setting up mailconf
foreach my $school (@sharelist){
    my $config;
    if (exists $sophomorix_config{'SCHOOLS'}{$school}{'MAILCONF'}){
        $config=$sophomorix_config{'SCHOOLS'}{$school}{'MAILCONF'};
    }

    if ($config eq "none"){
        print "School $school ($config) has no MAILTYPE\n";
        next;
    } elsif (not -e $config){
        print "No config found for $school ($config)\n";
        next;
    } 


    # decide which sub to use
    if ($sophomorix_config{'SCHOOLS'}{$school}{'MAILTYPE'} eq "belwue"){
        # download stuff
        $mailconf{'DOWNLOAD_FILES'}{'DOWNLOAD_DIR'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.downloads";

        $mailconf{'DOWNLOAD_FILES'}{'DATA_DIR'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.data";

        $mailconf{'DOWNLOAD_FILES'}{'MAILBOXES'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.data/".$school.".belwue.multimailboxes";
        $mailconf{'DOWNLOAD_FILES'}{'MAILLISTS'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.data/".$school.".belwue.maillists";
        $mailconf{'DOWNLOAD_FILES'}{'ALIASES'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.data/".$school.".belwue.aliases";

        $mailconf{'UPLOAD_FILES'}{'UPLOAD_DIR'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.uploads";
        $mailconf{'UPLOAD_FILES'}{'MAILBOXES_ADD'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.uploads/".
            "ADD_MAILBOXES_".$school.".belwue.multimailboxes-utf8.txt";
        $mailconf{'UPLOAD_FILES'}{'MAILBOXES_DELETE'}=$sophomorix_config{'INI'}{'PATHS'}{'MAIL'}.
            "/belwue/".$school."/".$school.".belwue.uploads/".
            "DELETE_MAILBOXES_".$school.".belwue.multimailboxes-utf8.txt";


#        &belwue_maildata_fetch($school,
#                               $sophomorix_config{'SCHOOLS'}{$school}{'MAILTYPE'},
#                               $sophomorix_config{'SCHOOLS'}{$school}{'MAILCONF'},
#                               \%mailconf,
#                               \%sophomorix_config);
       &belwue_maildata_check($school,
                              $sophomorix_config{'SCHOOLS'}{$school}{'MAILTYPE'},
                              $sophomorix_config{'SCHOOLS'}{$school}{'MAILCONF'},
                              \%mailconf,
                              $ref_mail,
                              \%sophomorix_config);
    } else {
        print "\n\nERROR: $sophomorix_config{'SCHOOLS'}{$school}{'MAILTYPE'} not known\n";
        exit;
    }

}




&result_sophomorix_check_exit(\%sophomorix_result,\%sophomorix_config,$json);
# ===========================================================================
# Start
# ===========================================================================
&log_script_start(\@arguments,\%sophomorix_result);


&AD_unbind_admin($ldap);
&log_script_end(\@arguments,\%sophomorix_result,\%sophomorix_config,$json);
############################################################
# End
############################################################



############################################################
# subs
############################################################
sub bind_belwue_admin {
    my ($ref_mailconf)=@_;
    # check connection 
    if($Conf::log_level>=3){
        print "   Checking Belwue connection ...\n";
    }

    # bind
    if($Conf::log_level>=3){
        print "HOST:      $ref_mailconf->{'CONNECT'}{HOST} \n";
        print "ADMINUSER: $ref_mailconf->{'CONNECT'}{ADMINUSER} \n";
        print "PASS:      $ref_mailconf->{'CONNECT'}{PASSWORD}\n";
    }
    my $ldap = Net::LDAP->new($ref_mailconf->{'CONNECT'}{HOST});

    my $mesg = $ldap->bind($ref_mailconf->{'CONNECT'}{ADMINUSER}, 
                      password => $ref_mailconf->{'CONNECT'}{PASSWORD});
    # show errors from bind
    $mesg->code && die $mesg->error;
    return ($ldap);
}



sub unbind_belwue_admin {
    my ($ldap) = @_;
    my $mesg = $ldap->unbind();
    #  show errors from unbind
    $mesg->code && die $mesg->error;
}



sub wget_return {
    my ($return,$object)=@_;
    if ($return==0){
        print "   * Succesfully downloded html page for $object\n";
    } else {
        print "   * ERROR downloading $object: wget returned error code $return\n";
        exit;
    }
}



sub belwue_maildata_fetch {
    my ($school,$mailtype,$mailconf,$ref_mailconf,$ref_sophomorix_config)=@_;
    my %belwue=();

    &print_title("Fetching maildata for school $school: $mailtype");
    print "   * Config: $mailconf\n";
    # read the config
    tie %{ $ref_mailconf->{'CONFIG'} }, 'Config::IniFiles',
        ( -file => $mailconf, 
          -handle_trailing_comment => 1,
        );

    # calculate connect data
    $ref_mailconf->{'CONNECT'}{BASE}="CN=".$ref_mailconf->{'CONFIG'}{'ACCOUNT'}{'BASE'};
    $ref_mailconf->{'CONNECT'}{BASESIMPLE}=$ref_mailconf->{'CONFIG'}{'ACCOUNT'}{'BASE'};
    $ref_mailconf->{'CONNECT'}{SCOPE}="sub";
    $ref_mailconf->{'CONNECT'}{FILTER}="(cn=*)";
    $ref_mailconf->{'CONNECT'}{HOST}=$ref_mailconf->{'CONFIG'}{'ACCOUNT'}{PROTOCOL}."://".
                                     $ref_mailconf->{'CONFIG'}{'ACCOUNT'}{SERVER}.":".
                                     $ref_mailconf->{'CONFIG'}{'ACCOUNT'}{PORT};

    $ref_mailconf->{'CONNECT'}{ADMINUSER}=$ref_mailconf->{'CONFIG'}{'ACCOUNT'}{ADMINUSER}.
                                          "@".
                                          $ref_mailconf->{'CONFIG'}{'ACCOUNT'}{'BASE'};
    $ref_mailconf->{'CONNECT'}{ADMINURL}="https://".
                                         $ref_mailconf->{'CONFIG'}{'ACCOUNT'}{SERVER}.
                                         ":9010/DomainAdmin";
    $ref_mailconf->{'CONNECT'}{PASSWORD}=$ref_mailconf->{'CONFIG'}{'ACCOUNT'}{PASSWORD};

    #  "ADMINURL" => "https://mbox1.belwue.de:9010/DomainAdmin",
    #  "ADMINUSER" => "admin\@bszleo.de",
    #  "BASE" => "CN=bszleo.de",
    #  "BASESIMPLE" => "bszleo.de",
    #  "FILTER" => "(cn=*)",
    #  "HOST" => "ldaps://mbox1.belwue.de:636",
    #  "PASSWORD" => "******",
    #  "SCOPE" => "sub"
    print Dumper(\%mailconf);
    
    ############################################################
    # ldap address book
    ############################################################ 

    print "Accessing Belwue addressbook via ldap\n";
    my ($ldap) = &bind_belwue_admin($ref_mailconf);
    my $mesg = $ldap->search(
                   base   => $ref_mailconf->{'CONNECT'}{BASE},
                   scope => $ref_mailconf->{'CONNECT'}{SCOPE},
                   filter => $ref_mailconf->{'CONNECT'}{FILTER},
                        );

    my $max = $mesg->count; 
    my $count = $mesg->count;
    for( my $index = 0 ; $index < $max ; $index++) {
        my $num=$index+1;
        my $entry = $mesg->entry($index);
        my $dn=$entry->dn();
        my $uid=$entry->get_value('uid');
        my $cn=$entry->get_value('cn');
        my $given=$entry->get_value('givenName');
        my $sn=$entry->get_value('sn');
        my $server=$entry->get_value('hostServer');
        my $mail=$entry->get_value('mail');

        if (not defined $given){
            $given="";
        }
        if($Conf::log_level>=2){
	    print "$num) dn: $dn\n";
	    print "   * cn:          $cn\n";
	    print "   * givenName:   $given\n";
	    print "   * hostServer:  $server\n";
	    print "   * mail:        $mail\n";
	    print "   * sn:          $sn\n";
	    print "   * uid:         $uid\n";
            print "\n";
        }

        $belwue{'OBJECTS'}{$uid}{'CN'}=$cn;
        $belwue{'OBJECTS'}{$uid}{'givenName'}=$given;
        $belwue{'OBJECTS'}{$uid}{'hostServer'}=$server;
        $belwue{'OBJECTS'}{$uid}{'mail'}=$mail;
        $belwue{'OBJECTS'}{$uid}{'sn'}=$sn;
        $belwue{'OBJECTS'}{$uid}{'uid'}=$uid;
        #print Dumper(\%belwue);
    }
    &unbind_belwue_admin($ldap); 

    ############################################################
    # downloading
    ############################################################ 
    print "Downloading Objects page:\n";
    system("mkdir -p $ref_mailconf->{'DOWNLOAD_FILES'}{'DOWNLOAD_DIR'}");
    system("mkdir -p $ref_mailconf->{'DOWNLOAD_FILES'}{'DATA_DIR'}");

    # download object list
    my $download_objects_command="wget -q --http-user=admin ".
         "--http-password=$ref_mailconf->{'CONNECT'}{PASSWORD} ".
         "--output-document=$ref_mailconf->{'DOWNLOAD_FILES'}{'DOWNLOAD_DIR'}/objects.html ".
         "\"$ref_mailconf->{'CONNECT'}{ADMINURL}/$ref_mailconf->{'CONNECT'}{BASESIMPLE}".
         "/ObjectList.html?domainName=$ref_mailconf->{'CONNECT'}{BASESIMPLE}\"";

   if($Conf::log_level>=2){
       print "\nWGET: $download_objects_command\n\n";
    }
    my $return=system($download_objects_command);
    &wget_return($return,"Objects");

    ############################################################
    # parsing
    ############################################################

    # file to parse
    my $html_doc = $ref_mailconf->{'DOWNLOAD_FILES'}{'DOWNLOAD_DIR'}."/objects.html";
    print "   * Parsing $html_doc\n";

    # list of headers
    my $table_headers = [ 'Objekt', 'Typ','Speicher','Letzter Zugriff' ];

    # constructor
    my $table_extract = HTML::TableExtract->new(headers => $table_headers);
    $table_extract->utf8_mode(1);
    $table_extract->parse_file($html_doc);
    my ($table) = $table_extract->tables;
    print "... done with Objects page:\n";

    foreach my $row ($table->rows) {
        my ($object,$type,$storage,$access)=@$row;
        print "  Object: $object\n";
        print "  Type: $type\n";
        if (not defined $storage){
            $storage="---";
        }
        if (not defined $access){
            $access="---";
        }
        print "  Storage: $storage\n";
        print "  Access: $access\n";
        if (not defined $access){
            $access="never";
        }
        # add to types
        if ($type eq "Mailingliste"){
            $belwue{'maillist'}{$object}{'type'}=$type;
            push @{ $belwue{'LISTS'}{'MAILLISTS'} }, $object;
            ############################################################
            # downloading maillist data
            ############################################################
            my $download_list_command="wget -q --http-user=admin ".
                "--http-password=$ref_mailconf->{'CONNECT'}{PASSWORD} ".
                "--output-document=$ref_mailconf->{'DOWNLOAD_FILES'}{'DOWNLOAD_DIR'}/$object.html ".
                "\"$ref_mailconf->{'CONNECT'}{ADMINURL}/$ref_mailconf->{'CONNECT'}{BASESIMPLE}".
                "/Subscribers.html?InCluster=1&domainName=$ref_mailconf->{'CONNECT'}{BASESIMPLE}".
                "&&listName=$object\"";
            if($Conf::log_level>=2){
                print "\nWGET: $download_list_command\n\n";
            }
            my $return=system($download_list_command);
            &wget_return($return,$object);

            ############################################################
            # parsing maillist data
            ############################################################
            my $html_doc = $ref_mailconf->{'DOWNLOAD_FILES'}{'DOWNLOAD_DIR'}."/".$object.".html";
            print "   * Parsing $html_doc\n";

            # list of headers
            # Umlaut in header does nor work
#            my $table_headers = [ 'Email','Zustellungsart','Anmeldezeit','Nachrichten zurückgewiesene','Angezeigter Name' ];
            my $table_headers = [ 'Email', 'Zustellungsart', 'Anmeldezeit'];

            # constructor
            my $table_extract = HTML::TableExtract->new(headers => $table_headers);
            $table_extract->utf8_mode(1);
            $table_extract->parse_file($html_doc);
            my ($table) = $table_extract->tables;
            foreach my $row ($table->rows) {
                my ($member_email,$type,$time,$bounced,$displayname)=@$row;
                if (not defined $member_email){
                    # no members
                    last;
                }
                #print "$object: $member_email  $type  $time\n";
                if ($type ne "Abonnement aufheben"){
                    $belwue{'maillist'}{$object}{'members'}{$member_email}="member";
                    push @{ $belwue{'maillist'}{$object}{'memberlist'} }, $member_email;
                }
            }
            # sort the memberlist if not empty
            if ( $#{ $belwue{'maillist'}{$object}{'memberlist'} }>0 ){
                 @{ $belwue{'maillist'}{$object}{'memberlist'} } = sort @{ $belwue{'maillist'}{$object}{'memberlist'}  };
            }
        } elsif ($type eq "Alias"){
            $belwue{'alias'}{$object}=$storage;
            $belwue{'alias_reverse'}{$storage}=$object;
            # aliases are in storage
            $belwue{'OBJECTS'}{$storage}{'alias'}=$object;
            push @{ $belwue{'LISTS'}{'ALIASES'} }, $object;
        } elsif ($type eq "Multi-Mailbox"){
            $belwue{'multimailbox'}{$object}{'type'}=$type;
            $belwue{'multimailbox'}{$object}{'storage'}=$storage;
            $belwue{'multimailbox'}{$object}{'access'}=$access;
            push @{ $belwue{'LISTS'}{'MAILBOXES'}  }, $object;
        } else {
            print "Unknown object $type\n";
        }
    }
    ############################################################
    # printout data/write data into files
    ############################################################
    open (BOX,   ">$ref_mailconf->{'DOWNLOAD_FILES'}{'MAILBOXES'}");
    open (ALIAS, ">$ref_mailconf->{'DOWNLOAD_FILES'}{'ALIASES'}");
    open (LIST,  ">$ref_mailconf->{'DOWNLOAD_FILES'}{'MAILLISTS'}");

    # MAILBOXES
    @{ $belwue{'LISTS'}{'MAILBOXES'} } = sort @{ $belwue{'LISTS'}{'MAILBOXES'} };
    print "\nMultiMailboxes:\n";
    my $num_mbox=1;
    foreach my $uid (@{ $belwue{'LISTS'}{'MAILBOXES'} }){
        print BOX $uid.";\n";
        print "   $num_mbox) $uid\n";
        $num_mbox++;
    }

    # MAILLISTS
    @{ $belwue{'LISTS'}{'MAILLISTS'} } = sort @{ $belwue{'LISTS'}{'MAILLISTS'} };
    print "\nMailing Lists:\n";
    foreach my $list ( @{ $belwue{'LISTS'}{'MAILLISTS'} } ){
        my $member_string=join(",",@{ $belwue{'maillist'}{$list}{'memberlist'} });
        print LIST "$list:$member_string\n";
        print "   * $list\n";
        my $num_list=1;
        foreach my $member ( @{ $belwue{'maillist'}{$list}{'memberlist'} } ){
            if (not defined $member){
                next;
            } 
            print "     $num_list) --> $member\n";
            $num_list++;
        }
    }

    # ALIASES
    @{ $belwue{'LISTS'}{'ALIASES'} } = sort @{ $belwue{'LISTS'}{'ALIASES'} };
    print "\nMail Aliase:\n";
    my $num=1;
    foreach my $alias ( @{ $belwue{'LISTS'}{'ALIASES'} }){
        print ALIAS "$alias:$belwue{'alias'}{$alias}\n";
        print "   $num) $alias --> $belwue{'alias'}{$alias}\n";
        $num++
    }

    close(BOX);
    close(ALIAS);
    close(LIST);

    if($Conf::log_level>=2){
        print Dumper(\%belwue);
    }
}



sub belwue_maildata_check {
    my ($school,$mailtype,$mailconf,$ref_mailconf,$ref_mail,$ref_sophomorix_config)=@_;
    my %action=();
    my @belwue_tmp=();

    # MAILBOXES
    ############################################################
    open (BOX, "<$ref_mailconf->{'DOWNLOAD_FILES'}{'MAILBOXES'}");
    while (<BOX>){
        my ($user)=split(/;/);
        $action{'MAILBOXES'}{$user}{'BELWUE'}="EXISTS";
        push @belwue_tmp, $user;
    }
    close(BOX);
    # mailaccounts
    # Walk through AD users, decide ADD/KEEP
    print "Mailaccounts for school $school:\n";
    foreach my $user (@{ $ref_mail->{'LISTS'}{'USER_by_SCHOOL'}{$school} }){
	print "USER: $user\n";
        if (exists $action{'MAILBOXES'}{$user}){
            print "  * Mailbox $user: nothing to do\n";
            $action{'MAILBOXES'}{$user}{'AD'}="EXISTS";
            $action{'MAILBOXES'}{$user}{'ACTION'}="KEEP";
        } else {
            print "  * Mailbox $user: ADD\n";
            $action{'MAILBOXES'}{$user}{'AD'}="EXISTS";
            $action{'MAILBOXES'}{$user}{'ACTION'}="ADD";
        }
    }
    
    # Walk through belwue users, decide DELETE
    foreach my $belwue_user (@belwue_tmp){
        if (not exists $ref_mail->{'QUOTA'}{'USERS'}{$belwue_user}){
            $action{'MAILBOXES'}{$belwue_user}{'ACTION'}="DELETE";
        }
    }

    # create walk through lists ADD/KEEP/DELETE
    print "\n";
    print "ACTION MAILBOXES:\n";
    foreach my $user (keys %{ $action{'MAILBOXES'} } ){
        if ($action{'MAILBOXES'}{$user}{'ACTION'} eq "KEEP"){
            #print "   KEEP:   $user\n";
            push @{ $action{'ACTIONLIST'}{'KEEP'} }, $user;
        } elsif ($action{'MAILBOXES'}{$user}{'ACTION'} eq "DELETE"){
            #print "   DELETE: $user\n";
            push @{ $action{'ACTIONLIST'}{'DELETE'} }, $user;
        } elsif ($action{'MAILBOXES'}{$user}{'ACTION'} eq "ADD"){
            #print "   ADD:    $user\n";
            push @{ $action{'ACTIONLIST'}{'ADD'} }, $user;
        } else {
            print "##########################unknown #######:    $user\n";
        }
    }

    # sort the result lists for ADD/KEEP/DELETE
    @{ $action{'ACTIONLIST'}{'KEEP'} } = sort @{ $action{'ACTIONLIST'}{'KEEP'} };
    @{ $action{'ACTIONLIST'}{'DELETE'} } = sort @{ $action{'ACTIONLIST'}{'DELETE'} };
    @{ $action{'ACTIONLIST'}{'ADD'} } = sort @{ $action{'ACTIONLIST'}{'ADD'} };

    # write the files
    # ADD
    system("mkdir -p $mailconf{'UPLOAD_FILES'}{'UPLOAD_DIR'}");
    open (ADD,">$mailconf{'UPLOAD_FILES'}{'MAILBOXES_ADD'}");
    print ADD "Name\tRealname\tType\tPassword\tStorage\tAliases\n";

    my @password_chars=&get_passwd_charlist();
    foreach my $user (@{ $action{'ACTIONLIST'}{'ADD'} }){
        my $alias="";
        if ($ref_mail->{'QUOTA'}{'USERS'}{$user}{'MAIL'}{'ALIAS'} eq "TRUE"){
            $alias=$ref_mail->{'QUOTA'}{'USERS'}{$user}{'MAIL'}{'ALIASNAME'};
        }

        my $file=$ref_mail->{'QUOTA'}{'USERS'}{$user}{'sophomorixAdminFile'};
        my $plain_password=&get_plain_password(
                           $ref_mail->{'QUOTA'}{'USERS'}{$user}{'sophomorixRole'},
                           $file,
                           $ref_sophomorix_config->{'FILES'}{'USER_FILE'}{$file}{'RANDOM_PWD'}, # yes|no
                           $ref_sophomorix_config->{'FILES'}{'USER_FILE'}{$file}{'PWD_LENGTH'}, # length of random pwd
                           @password_chars);
        my $mailquota=$ref_mail->{'QUOTA'}{'USERS'}{$user}{'MAILQUOTA'}{'CALC'};
        print ADD "$user\t".
                  "$ref_mail->{'QUOTA'}{'USERS'}{$user}{'MAIL'}{'displayName'}\t".
                  "MultiMailbox\t".
                  "$plain_password\t".
                  "${mailquota}M\t".
                  "$alias\n";
    }
    close(ADD);

    # DELETE
    system("mkdir -p $mailconf{'UPLOAD_FILES'}{'UPLOAD_DIR'}");
    open (DELETE,">$mailconf{'UPLOAD_FILES'}{'MAILBOXES_DELETE'}");
    foreach my $user (@{ $action{'ACTIONLIST'}{'DELETE'} }){
        print DELETE $user."\n";
    }
    close(DELETE);


    # MAILLISTS
    ############################################################
    my %belwue_maillist_tmp=();
    my @belwue_maillist_tmp=();    

    open (LIST, "<$ref_mailconf->{'DOWNLOAD_FILES'}{'MAILLISTS'}");
    while (<LIST>){
        #print "$_";
        chomp();
        my ($maillist,$string)=split(/:/);
        my @members=split(/,/,$string);
	#print "ML: $maillist\n";
        $action{'MAILLISTS'}{$maillist}{'BELWUE'}="EXISTS";

        push @{ $action{'MAILLISTS'}{$maillist}{'MEMBERS'} }, @members;
        push @belwue_maillist_tmp, $maillist;
    }
    close(LIST);

    # Walk through AD maillists, decide ADD/KEEP/UPDATE
    print "Maillists for school $school:\n";
    foreach my $maillist (@{ $ref_mail->{'LISTS'}{'MAILLISTS_by_SCHOOL'}{$school} }){
	print "MAILLIST: $maillist\n";
        if (exists $action{'MAILLISTS'}{$maillist}){
            print "  * Maillist $maillist: nothing to do\n";
            $action{'MAILLISTS'}{$maillist}{'AD'}="EXISTS";
            $action{'MAILLISTS'}{$maillist}{'ACTION'}="KEEP";
            # ... test for update, matching users?
            
        } else {
            print "  * Maillist: $maillist ADD\n";
            $action{'MAILLISTS'}{$maillist}{'AD'}="EXISTS";
            $action{'MAILLISTS'}{$maillist}{'ACTION'}="ADD";
        }
    }

    # Walk through belwue maillist, decide DELETE
    foreach my $belwue_maillist (@belwue_maillist_tmp){
        if (not exists $ref_mail->{'LOOKUP'}{'MAILLISTS_by_SCHOOL'}{$school}{$belwue_maillist}){
            $action{'MAILLISTS'}{$belwue_maillist}{'ACTION'}="DELETE";
            print "  * Maillist: $belwue_maillist DELETE\n";
        }
    }


    # create walk through lists ADD/KEEP/DELETE
    print "\n";
    print "ACTION MAILLISTS:\n";
    foreach my $maillist (keys %{ $action{'MAILLISTS'} } ){
        if ($action{'MAILLISTS'}{$maillist}{'ACTION'} eq "KEEP"){
            print "   KEEP:   $maillist\n";
            push @{ $action{'ACTIONLIST'}{'KEEP_MAILLIST'} }, $maillist;
        } elsif ($action{'MAILLISTS'}{$maillist}{'ACTION'} eq "DELETE"){
            print "   DELETE: $maillist\n";
            push @{ $action{'ACTIONLIST'}{'DELETE_MAILLIST'} }, $maillist;
        } elsif ($action{'MAILLISTS'}{$maillist}{'ACTION'} eq "UPDATE"){
            print "   UPDATE: $maillist\n";
            push @{ $action{'ACTIONLIST'}{'UPDATE_MAILLIST'} }, $maillist;
        } elsif ($action{'MAILLISTS'}{$maillist}{'ACTION'} eq "ADD"){
            print "   ADD:    $maillist\n";
            push @{ $action{'ACTIONLIST'}{'ADD_MAILLIST'} }, $maillist;
            # create file with users

        } else {
            print "##########################unknown #######:    $maillist\n";
        }
    }
    
    # write the files

    # ADD_MAILLIST
    foreach my $maillist (@{ $action{'ACTIONLIST'}{'ADD_MAILLIST'} }){
        # filename ADD_MAILLIST_name.txt
        my $upload_file="ADD_MAILLIST_".$school.".belwue.".$maillist.".txt";
        my $upload_file_abs=$ref_mailconf->{'UPLOAD_FILES'}{'UPLOAD_DIR'}."/".$upload_file;
	print "ADD $upload_file to upload dir\n";
        open (ADD_MAILLIST,">$upload_file_abs");
        foreach my $member ( @{ $ref_mail->{'MAILLIST'}{$maillist}{'LIST'} } ){
            print "   * $member\n";
            print ADD_MAILLIST "$member\n";
        }
        close('ADD_MAILLIST');

    }

    # KEEP_MAILLIST
    # nothing to do, maillist and members are kept as is

    # UPDATE_MAILLIST
    foreach my $maillist (@{ $action{'ACTIONLIST'}{'UPDATE_MAILLIST'} }){
         # filename UPDATE_MAILLIST_name.txt
    }

    # DELETE_MAILLIST
    foreach my $maillist (@{ $action{'ACTIONLIST'}{'DELETE_MAILLIST'} }){
         # filename DELETE_MAILLIST_name.txt
    }

    # sophomorix-gruppe sollte auch eine maillist anlegen
    # (zusammenlegen von hausmeister, teachers, zu kollegium )



    my $ref_action=\%action;
#print Dumper( $ref_action );
#print Dumper( $ref_action->{'MAILLISTS'} );
    # print "bz:\n";
    # print Dumper( $ref_action->{'MAILBOXES'}{'bz'} );
    # print "bz2:\n";
    # print Dumper( $ref_action->{'MAILBOXES'}{'bz2'} );
    # print "znk:\n";
    # print Dumper( $ref_action->{'MAILBOXES'}{'znk'} );
    # print "maiersa23:\n";
    # print Dumper( $ref_action->{'MAILBOXES'}{'maiersa23'} );

    # print Dumper( $ref_action->{'ACTIONLIST'} );

    #print Dumper( \%action{'MAILBOXES'}{'EXISTS'}{'bz'} );
    #print Dumper( \%action{'MAILBOXES'}{'EXISTS'}{'bz2'} );
}
