#!/usr/bin/perl -w
# This script (sophomorix-user) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# modules
use strict;
#use Quota;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use List::MoreUtils qw(uniq);
#use IMAP::Admin;
#use DBI;
use Net::LDAP;
use JSON;
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 time_stamp_AD
                                 time_stamp_file
                                 unlock_sophomorix
                                 lock_sophomorix
                                 log_script_start
                                 log_script_end
                                 log_script_exit
                                 backup_auk_file
                                 get_passwd_charlist
                                 get_plain_password
                                 check_options
                                 config_sophomorix_read
                                 result_sophomorix_init
                                 result_sophomorix_add
                                 result_sophomorix_check_exit
                                 result_sophomorix_print
                                 remove_from_list
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_school_create
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_user_update
                                 AD_group_create
                                 AD_group_kill
                                 AD_group_addmember
                                 AD_get_schoolname
                                 AD_get_name_tokened
                                 AD_project_fetch
                                 AD_group_update
                                 AD_project_sync_members
                                 AD_dn_fetch_multivalue
                                 AD_group_list
                                 AD_dns_get
                                 AD_debug_logdump
                                 AD_object_search
                                 get_forbidden_logins
                                    );

my @arguments = @ARGV;

my $time_stamp_file=&time_stamp_file();
my $time_stamp_AD=&time_stamp_AD();

# use strict;
# use Getopt::Long;
# Getopt::Long::Configure ("bundling");
# #use Schedule::at;
# use String::Approx 'amatch';
# use Sophomorix::SophomorixConfig;
# use Sophomorix::SophomorixBase;
# use Time::Local;
# use Time::localtime;
# use Term::ANSIColor qw(:constants); # farbiger Text RED, BLUE, ...
# # nach jedem Printbefehl wieder auf Standardfarbe zurücksetzen
# $Term::ANSIColor::AUTORESET = 1;
# use IMAP::Admin;
# use DBI;
# use Net::LDAP;
# use Date::Calc qw(check_date);
# use Sophomorix::SophomorixPgLdap qw(show_modulename
#                                     db_connect
#                                     check_connections
#                                     search_user
#                                     list_teachers_by_year
#                                     update_uid_ldap
#                                     fetchdata_from_account
#                                     forbidden_login_hash
#                                     update_user_db_entry
#                                     date_pg2perl
#                                     user_deaktivieren
#                                     user_reaktivieren     
#                                     check_sophomorix_user
#                                     set_sophomorix_passwd
#                                     fetchstudents_from_adminclass
#                                     db_connect
#                                    );
#my @arguments = @ARGV;


my $today=`date +%d.%m.%Y`;
chomp($today);

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
$Conf::log_level=1;

my $help=0;
my $info=0;
my $json=0;
my $empty_password=0;

my $webui_dashboard;
my $user_permissions;
my $add_user_permissions;
my $remove_user_permissions;

my $comment;
my $quota;
my $mailquota;


# stati
my $usable=0;
my $enable=0;
my $activate=0;
my $selfactivate=0;
my $permanent=0;
my $tolerate=0;
my $deactivate=0;
my $lock=0;
my $freeze=0;
my $killable=0;
my $removable=0;

my $kill_all_users=0;
my $teacher="";
my $sc_toleration="empty";
my $reset_user="";
my $user="";
my $old_uid="";
my $new_uid="";
my $old_mailbox="";
my $new_mailbox="";
my $new_class="";
my $list_teachers_by_year=0;
my $school="";

# Parsen der Optionen
my $testopt=GetOptions(
       "help|h" => \$help,
       "i|info" => \$info,
       "json|j+" => \$json,
       "verbose|v+" => \$Conf::log_level,
       "school=s" => \$school,
       "u|user=s" => \$user,
       "comment=s" => \$comment,
       "quota=s" => \$quota,
       "mailquota=i" => \$mailquota,
       "webui-dashboard=s" => \$webui_dashboard,
       "user-permissions=s" => \$user_permissions,
       "add-user-permissions=s" => \$add_user_permissions,
       "remove-user-permissions=s" => \$remove_user_permissions,
       "U|usable" => \$usable,
       "E|enable" => \$enable,
       "A|activate" => \$activate,
       "S|selfactivate" => \$selfactivate,
       "P|permanent" => \$permanent,
       "T|tolerate" => \$tolerate,
       "D|deactivate" => \$deactivate,
       "L|lock" => \$lock,
       "F|freeze" => \$freeze,
       "K|killable" => \$killable,
       "R|removable" => \$removable,
#       "old-uid=s" => \$old_uid,
#       "new-uid=s" => \$new_uid,
#       "old-mailbox=s" => \$old_mailbox,
#       "new-mailbox=s" => \$new_mailbox,
#       "kill-all-users" => \$kill_all_users,
#       "reset-user=s" => \$reset_user,
#       "empty-password" => \$empty_password,
#       "scheduled-toleration=s" => \$sc_toleration,
#       "t|teacher=s" => \$teacher,
#       "list-teachers-by-year" => \$list_teachers_by_year,
#       "new-class|newclass=s" => \$new_class,
          );


my %sophomorix_result=&result_sophomorix_init("sophomorix-user");
# Prüfen, ob Optionen erkannt wurden
&check_options($testopt,\%sophomorix_result,$json);
#&check_connections();

# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-user edits the sophomorix user database.

Options
  -h   /  --help
  -i   /  --info
  -v   /  --verbose
  -vv  /  --verbose --verbose

Search for a user/users in sAMAccountName:
  -u user   /   --user user
  -u \'*\'   /   --user u*se*r (option is passed to ldap filter)
Grep in the results:
 -u *user* | grep -i --text <strg>
  
Choose the school:
  --school <school>

Changing status of a user:
  -E --user <user>  /   --enable --user <user>
  -P --user <user>  /   --permanent --user <user>
  -F --user <user>  /   --freeze --user <user>
  -L --user <user>  /   --lock --user <user>
  -K --user <user>  /   --killable --user <user>

These are done by the automatic workflow, you shold not need them
  -U --user <user>  /   --usable --user <user>
  -A --user <user>  /   --activate --user <user>
  -S --user <user>  /   --selfactivate --user <user>
  -T --user <user>  /   --tolerate --user <user>
  -D --user <user>  /   --deactivate --user <user>
  -R --user <user>  /   --removable --user <user>

Updating Quota of a user:
    --quota <linuxmuster-global>:<number(MB)>,<school1>:<number(MB)>,...
    --mailquota number


Updating comment of a user:
  --user <user> --comment "This is the comment"

Updating WebuiDashboard of a user:
  --user <user> --webui-dashboard "Webui Dashboard String"
  --user <user> --user-permissions permission1,permission2,permission3, ... 
  --user <user> --add-user-permissions permission1,permission2,permission3, ...
  --user <user> --remove-user-permissions permission1,permission2,permission3, ...

-> continue here
  --list-teachers-by-year

Todo:
Changing loginname of a user:
  --old-uid oldlogin --new-uid newlogin
  (WARNING: This is Alpha!!! This will never work 100%!)
  Problems: The user has to be logged out!
            cyrus and imap will be restartet!
  --> Do this at night!
  
Todo:
Moving the mailbox of a user:
  (This is included in --old-uid oldlogin --new-uid newlogin.
  It should never be necessary to move the mailbox by itself)
  --old-mailbox oldlogin --new-mailbox newlogin
  --> Do this only when you know what to do!

Todo:
Changing class of a user (that is not in students.csv)
  -u user --newclass newclass
  (to move user, sophomorix-move must be called)

Todo:
Actions:
  --reset-user user1,user2,...
  --reset-user user1,user2,... --empty-password
  --teacher teacher --scheduled-toleration yyyy-mm-dd
  --kill-all-users

Please see the sophomorix-user(8) man pages for full documentation
');
   print "\n";

   exit;
}

my ($ldap,$root_dse) = &AD_bind_admin(\@arguments,\%sophomorix_result,$json);
my $root_dns=&AD_dns_get($root_dse);
my %sophomorix_config=&config_sophomorix_read($ldap,$root_dse,\%sophomorix_result);

# Setting the filters
my $school_filter="";
my $user_filter="";
if ($school eq $DevelConf::name_default_school){
    $school_filter="";
} elsif ($school ne ""){
    $school_filter="(sophomorixSchoolPrefix=$school)";
}
if ($user ne ""){
    $user_filter="(sAMAccountName=$user)";
}



# --info
if ($user eq "" and $info==1){
    ##################################################
    # vars for results
    my %results=();
    my @students_u=();
    my @teachers_u=();
    my @students_e=();
    my @teachers_e=();
    my @students_t=();
    my @teachers_t=();
    my @students_a=();
    my @teachers_a=();
    my @students_s=();
    my @teachers_s=();
    my @students_d=();
    my @teachers_d=();
    my @students_l=();
    my @teachers_l=();
    my @students_r=();
    my @teachers_r=();
    my @students_k=();
    my @teachers_k=();
    my @students_f=();
    my @teachers_f=();
    my @students_p=();
    my @teachers_p=();
    my @globaladmin_p=();
    my @schooladmin_p=();
    my @globalbind_p=();
    my @schoolbind_p=();
    my @computers_p=();
    my @others=();

    ##################################################
    # search for all users
    my $filter="( &(objectclass=user) (cn=*) $school_filter)"; 
    if($Conf::log_level>=2){
        print "Filter: $filter\n";
    }
    my $mesg = $ldap->search(
                      base   => $root_dse,
                      scope => 'sub',
                      filter => $filter,
                      attr => ['cn']
                            );
    &AD_debug_logdump($mesg,2,(caller(0))[3]);
    my $max = $mesg->count;

    ##################################################
    # walk through all results
    # save results in lists
    for( my $index = 0 ; $index < $max ; $index++) {
        my $entry = $mesg->entry($index);
        my $dn=$entry->dn();
        my $role=$entry->get_value('sophomorixRole');
        my $status=$entry->get_value('sophomorixStatus');
	if (not defined $role or not defined $status){
            push @others, $dn;
	} elsif ($role eq "student" and $status eq "U"){
            push @students_u, $dn;
	} elsif ($role eq "teacher" and $status eq "U"){
            push @teachers_u, $dn;
	} elsif ($role eq "student" and $status eq "E"){
            push @students_e, $dn;
	} elsif ($role eq "teacher" and $status eq "E"){
            push @teachers_e, $dn;
	} elsif ($role eq "student" and $status eq "T"){
            push @students_t, $dn;
	} elsif ($role eq "teacher" and $status eq "T"){
            push @teachers_t, $dn;
	} elsif ($role eq "student" and $status eq "A"){
            push @students_a, $dn;
	} elsif ($role eq "teacher" and $status eq "A"){
            push @teachers_a, $dn;
	} elsif ($role eq "student" and $status eq "S"){
            push @students_s, $dn;
	} elsif ($role eq "teacher" and $status eq "S"){
            push @teachers_s, $dn;
	} elsif ($role eq "student" and $status eq "D"){
            push @students_d, $dn;
	} elsif ($role eq "teacher" and $status eq "D"){
            push @teachers_d, $dn;
	} elsif ($role eq "student" and $status eq "L"){
            push @students_l, $dn;
	} elsif ($role eq "teacher" and $status eq "L"){
            push @teachers_l, $dn;
	} elsif ($role eq "student" and $status eq "R"){
            push @students_r, $dn;
	} elsif ($role eq "teacher" and $status eq "R"){
            push @teachers_r, $dn;
	} elsif ($role eq "student" and $status eq "K"){
            push @students_k, $dn;
	} elsif ($role eq "teacher" and $status eq "K"){
            push @teachers_k, $dn;
	} elsif ($role eq "student" and $status eq "F"){
            push @students_f, $dn;
	} elsif ($role eq "teacher" and $status eq "F"){
            push @teachers_f, $dn;
	} elsif ($role eq "student" and $status eq "P"){
            push @students_p, $dn;
	} elsif ($role eq "teacher" and $status eq "P"){
            push @teachers_p, $dn;
	} elsif ($role eq "globaladministrator" and $status eq "P"){
            push @globaladmin_p, $dn;
	} elsif ($role eq "schooladministrator" and $status eq "P"){
            push @schooladmin_p, $dn;
	} elsif ($role eq "globalbinduser" and $status eq "P"){
            push @globalbind_p, $dn;
	} elsif ($role eq "schoolbinduser" and $status eq "P"){
            push @schoolbind_p, $dn;
	} elsif ($role eq "computer" and $status eq "P"){
            push @computers_p, $dn;
	} else {
            print "$dn\n";
        }
    }

    ##################################################    
    # save list sums in hash
    $results{'count'}{'students'}{'U'}=$#students_u+1;
    $results{'count'}{'teachers'}{'U'}=$#teachers_u+1;
    $results{'count'}{'students'}{'E'}=$#students_e+1;
    $results{'count'}{'teachers'}{'E'}=$#teachers_e+1;
    $results{'count'}{'students'}{'T'}=$#students_t+1;
    $results{'count'}{'teachers'}{'T'}=$#teachers_t+1;
    $results{'count'}{'students'}{'A'}=$#students_a+1;
    $results{'count'}{'teachers'}{'A'}=$#teachers_a+1;
    $results{'count'}{'students'}{'S'}=$#students_s+1;
    $results{'count'}{'teachers'}{'S'}=$#teachers_s+1;
    $results{'count'}{'students'}{'D'}=$#students_d+1;
    $results{'count'}{'teachers'}{'D'}=$#teachers_d+1;
    $results{'count'}{'students'}{'L'}=$#students_l+1;
    $results{'count'}{'teachers'}{'L'}=$#teachers_l+1;
    $results{'count'}{'students'}{'R'}=$#students_r+1;
    $results{'count'}{'teachers'}{'R'}=$#teachers_r+1;
    $results{'count'}{'students'}{'K'}=$#students_k+1;
    $results{'count'}{'teachers'}{'K'}=$#teachers_k+1;
    $results{'count'}{'students'}{'F'}=$#students_f+1;
    $results{'count'}{'teachers'}{'F'}=$#teachers_f+1;
    $results{'count'}{'students'}{'P'}=$#students_p+1;
    $results{'count'}{'teachers'}{'P'}=$#teachers_p+1;
    $results{'count'}{'globaladministrators'}{'P'}=$#globaladmin_p+1;
    $results{'count'}{'schooladministrators'}{'P'}=$#schooladmin_p+1;
    $results{'count'}{'globalbindusers'}{'P'}=$#globalbind_p+1;
    $results{'count'}{'schoolbindusers'}{'P'}=$#schoolbind_p+1;
    $results{'count'}{'computers'}{'P'}=$#computers_p+1;
    $results{'count'}{'others'}=$#others+1;

    ##################################################
    # sum all together
    my $sum_student=$results{'count'}{'students'}{'U'}+
                    $results{'count'}{'students'}{'E'}+
                    $results{'count'}{'students'}{'T'}+
                    $results{'count'}{'students'}{'A'}+
                    $results{'count'}{'students'}{'S'}+
                    $results{'count'}{'students'}{'D'}+
                    $results{'count'}{'students'}{'L'}+
                    $results{'count'}{'students'}{'R'}+
                    $results{'count'}{'students'}{'K'}+
                    $results{'count'}{'students'}{'F'}+
                    $results{'count'}{'students'}{'P'};

    my $sum_teacher=$results{'count'}{'teachers'}{'U'}+
                    $results{'count'}{'teachers'}{'E'}+
                    $results{'count'}{'teachers'}{'T'}+
                    $results{'count'}{'teachers'}{'A'}+
                    $results{'count'}{'teachers'}{'S'}+
                    $results{'count'}{'teachers'}{'D'}+
                    $results{'count'}{'teachers'}{'L'}+
                    $results{'count'}{'teachers'}{'R'}+
                    $results{'count'}{'teachers'}{'K'}+
                    $results{'count'}{'teachers'}{'F'}+
                    $results{'count'}{'teachers'}{'P'};
    my $sum_globaladministrators=$results{'count'}{'globaladministrators'}{'P'};
    my $sum_schooladministrators=$results{'count'}{'schooladministrators'}{'P'};
    my $sum_globalbindusers=$results{'count'}{'globalbindusers'}{'P'};
    my $sum_schoolbindusers=$results{'count'}{'schoolbindusers'}{'P'};

    my $sum_examaccounts=$results{'count'}{'examaccounts'}{'P'};
    my $sum_computers=$results{'count'}{'computers'}{'P'};

    # # OUTPUT
    # ##################################################
    print "----------+---+------+------+------+------+------+------+------+-----+\n";
    print "status    |   | stud | teach| gadm | sadm | gbin | sbin | comp | oth |\n";
    print "----------+---+------+------+------+------+------+------+------+-----+\n";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "permanent | P",
           $results{'count'}{'students'}{'P'},
           $results{'count'}{'teachers'}{'P'},
           $results{'count'}{'globaladministrators'}{'P'},
           $results{'count'}{'schooladministrators'}{'P'},
           $results{'count'}{'globalbindusers'}{'P'},
           $results{'count'}{'schoolbindusers'}{'P'},
           $results{'count'}{'computers'}{'P'},
           "";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "usable    | U",$results{'count'}{'students'}{'U'},$results{'count'}{'teachers'}{'U'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "activated | A",$results{'count'}{'students'}{'A'},$results{'count'}{'teachers'}{'A'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "enabled   | E",$results{'count'}{'students'}{'E'},$results{'count'}{'teachers'}{'E'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "selfactiv.| S",$results{'count'}{'students'}{'S'},$results{'count'}{'teachers'}{'S'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "tolerated | T",$results{'count'}{'students'}{'T'},$results{'count'}{'teachers'}{'T'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "disabled  | D",$results{'count'}{'students'}{'D'},$results{'count'}{'teachers'}{'D'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "locked    | L",$results{'count'}{'students'}{'L'},$results{'count'}{'teachers'}{'L'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "frozen    | F",$results{'count'}{'students'}{'F'},$results{'count'}{'teachers'}{'F'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "removeable| R",$results{'count'}{'students'}{'R'},$results{'count'}{'teachers'}{'R'},"","","","","","";
    printf "%-13s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "killable  | K",$results{'count'}{'students'}{'K'},$results{'count'}{'teachers'}{'K'},"","","","","","";
    print "----------+---+------+------+------+------+------+------+------+-----+\n";
    printf "%-10s|%2s |%5s |%5s |%5s |%5s |%5s |%5s |%5s |%4s |\n",
           "sum: $max","",$sum_student,$sum_teacher,
           $sum_globaladministrators,$sum_schooladministrators,
           $sum_globalbindusers,$sum_schoolbindusers,
           $sum_computers,$results{'count'}{'others'};
    print "----------+---+------+------+------+------+------+------+------+-----+\n";
    print "(stud=student,teach=teacher,gadm=globaladministrator,\n";
    print " sadm=schooladministrator,comp=computer,oth=other)\n";

    print "\nOther (oth) user objects (objectclass=user):\n";
    foreach my $dn (@others){
        print "   * $dn\n";
    }
    exit;
}


&result_sophomorix_check_exit(\%sophomorix_result,\%sophomorix_config,$json);
&log_script_start(\@arguments,\%sophomorix_result);


# # --old-uid oldlogin --new-uid newlogin
# if ($old_uid ne "" and $new_uid ne ""){

#     my %forbidden_login_hash=&forbidden_login_hash();

#     if (exists($forbidden_login_hash{$new_uid})){
#         &log_script_exit("ERROR: New login $new_uid exists in the system",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }

#     # Fetch old data
#     my ($old_home,$old_type,$old_gecos,$old_group,$old_uidnumber,
#        $old_sambahomepath) = &fetchdata_from_account($old_uid);

#     if ($old_home eq ""){
#         &log_script_exit("Could not find old-uid $old_uid",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }
#     my $dbh=&db_connect();
#     my ($old_dn)= $dbh->selectrow_array( "SELECT dn
#                                          FROM ldap_entries 
#                                          WHERE dn LIKE 'uid=$old_uid%'
#                                         ");
#     # changing stuff
#     my $new_home_update=$old_home;
#     $new_home_update=~s/\/${old_uid}$/\/${new_uid}/;
#     my $new_dn_update=$old_dn;
#     $new_dn_update=~s/uid=${old_uid},/uid=${new_uid},/;

#     print "1) Updating $old_uid to $new_uid in the sophomorix database\n";
#     &update_user_db_entry($old_uid,"Uid=$new_uid");
#     my $sql="UPDATE ldap_entries SET dn='$new_dn_update'
#              WHERE dn='$old_dn'";
#     if($Conf::log_level>=3){
#               print "\nSQL: $sql\n";
#     }
#     $dbh->do($sql);
#     &update_uid_ldap($old_uid,$new_uid);

#     print "2) Moving homedir.\n";
#     system("mv $old_home $new_home_update");

#     print "3) Renaming mailbox: $old_uid --> $new_uid\n";
#     &move_mailbox($old_uid,$new_uid);

#     print "4) Updating Horde database not supported\n";

#     print "5) Updating lehrer.txt if $old_uid is a teacher\n";
#     if ($old_type eq "teacher"){
#         &lehrer_ordnen($old_uid,$new_uid);
#     }

#     print "6) Updating /etc/aliases:\n";

#     system("${DevelConf::path_sbin}/sophomorix-mail --skiplock");
#     # log
#     &append_login_rename_log("man-rename-login",
#                            $old_uid,
#                            $new_uid,
#                            $old_uidnumber,
#                          );
#     print "... done!\n";


#     # Fetch new data
#     my ($new_home_db,$new_type,$new_gecos,$new_group,$new_uidnumber,
#        $new_sambahomepath_db) = &fetchdata_from_account($new_uid);
#     my ($new_dn_db)= $dbh->selectrow_array( "SELECT dn
#                                          FROM ldap_entries 
#                                          WHERE dn LIKE 'uid=$new_uid%'
#                                         ");
#     my $id_result_old="";
#     if (system("id $old_uid > /dev/null 2>&1")){
#         $id_result_old="$old_uid (nonexisting,OK)";
#     } else {
#         $id_result_old="$old_uid (existing,ERROR)";
#     };
#     my $id_result_new="";
#     if (system("id $new_uid > /dev/null 2>&1")){
#         $id_result_new="$new_uid (nonexisting,ERROR)";
#     } else {
#         $id_result_new="$new_uid (existing,OK)";
#     };

#     my $old_home_result="";
#     if (-d $old_home){
# 	$old_home_result=$old_home." (exists,ERROR)";
#     } else {
# 	$old_home_result=$old_home." (nonexisting,OK)";
#     }
#     my $new_home_result="";
#     if (-d $new_home_db){
# 	$new_home_result=$new_home_db." (exists,OK)";
#     } else {
# 	$new_home_result=$new_home_db." (nonexisting,ERROR)";
#     }

#     # Path to mailbox
#     my $old_initial= substr $old_uid,0,1;
#     my $new_initial= substr $new_uid,0,1;
#     my $old_mailbox_dir="/var/spool/cyrus/mail/".$old_initial."/user/".$old_uid;
#     my $new_mailbox_dir="/var/spool/cyrus/mail/".$new_initial."/user/".$new_uid;
#     my $old_mailbox_dir_result="";
#     my $new_mailbox_dir_result="";

#     if (-d $old_mailbox_dir){
# 	$old_mailbox_dir_result=$old_mailbox_dir." (exists, ERROR)";
#     } else {
# 	$old_mailbox_dir_result=$old_mailbox_dir." (nonexisting, OK)";
#     }
#     if (-d $new_mailbox_dir){
# 	$new_mailbox_dir_result=$new_mailbox_dir." (exists, OK)";
#     } else {
# 	$new_mailbox_dir_result=$new_mailbox_dir." (nonexisting, ERROR)";
#     }

#     # ????? /var/lib/cyrus/lock/w/user/wei.lock bleibt erhalten

#     # print results
#     print "Checking success:\n";
#     print " Unix Acount:\n";
#     print "    OLD: $id_result_old\n";
#     print "    NEW: $id_result_new\n";
#     print " LDAP DN:\n";
#     print "    OLD: $old_dn\n";
#     print "    NEW: $new_dn_db\n";
#     print " UNIX home:\n";
#     print "    OLD: $old_home_result\n";
#     print "    NEW: $new_home_result\n";
#     print " SAMBA home:\n";
#     print "    OLD: $old_sambahomepath\n";
#     print "    NEW: $new_sambahomepath_db\n";
#     print " CYRUS mailbox dir:\n";
#     print "    OLD: $old_mailbox_dir_result\n";
#     print "    NEW: $new_mailbox_dir_result\n";
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }

######################################################################
# Standard: suchen nach string
######################################################################

#if ($user eq "" and $list_teachers_by_year==0){
#   print "I don't know what to search for! (searchstring is empty)\n";
#   &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
#}


# --info --user <user>
if ($user ne "" and $info==1){
    my $filter="(&(objectclass=user) $user_filter  $school_filter)"; 
    if($Conf::log_level>=2){
        print "Filter: $filter\n";
    }
    my $mesg = $ldap->search(
                      base   => $root_dse,
                      scope => 'sub',
                      filter => $filter,
                      attr => ['cn','unicodePwd']
	);
    my $number = $mesg->count;
    if ($number==0){
        print "\n";
        print "No results found in this search\n";
    } else {
        my $count=0;
        foreach my $entry ($mesg->all_entries) {
            $count++; 
            my $sam = $entry->get_value ('sAMAccountName');
            print "\n";
            &print_title("User $count: $sam");

            my $pwd = $entry->get_value ('unicodePwd');

	    print "PWD: $pwd\n";
            $entry->dump; 
        }
    }
    exit;
} elsif ($list_teachers_by_year==1){
    print "... still to do!\n";
    #&list_teachers_by_year();
    exit;
}




# get dn if user exists and continue
############################################################
my ($count,$dn,$cn)=&AD_object_search($ldap,$root_dse,"user",$user);

if ($count>1){
    print "\n$count users found. Cannot modify more than one user!\n";
    print "Dont use * and stuff like this\n\n";
    exit $count;
} elsif ($count==0){
    print "\nERROR retrieving user $user: $count users found.\n\n";
    exit $count;
}


############################################################
# -user <user> --comment "Test for comment"
if ($user ne "" and defined $comment){
    print "Updating comment for user $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     comment=>$comment,
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}



# -user <user> --quota <school1>:<number1>;<school2>:<number2>
if ($user ne "" and defined $quota){
    print "Updating quota for user $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     quota=>$quota,
                     user_count=>"1",
                     max_user_count=>"1",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}



# -user <user> --mailquota <number>
if ($user ne "" and defined $mailquota){
    print "Updating mailquota for user $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     mailquota=>$quota,
                     user_count=>"1",
                     max_user_count=>"1",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}



# -user <user> --webui-dashboard "String"
if ($user ne "" and defined $webui_dashboard){
    print "Updating webui-dashboard for user $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     webui_dashboard=>$webui_dashboard,
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}




# user-permissions
# --user-permissions permission1,permission2,permission3, ... 
if (defined $user_permissions and $user ne ""){
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     user_permissions=>$user_permissions,
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                    });
}


# --add-user-permissions permission1,permission2,permission3, ...
if (defined $add_user_permissions and $user ne ""){
    my @add_user_permissions=split(/,/,$add_user_permissions);
    my @old_user_permissions = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn,"sophomorixUserPermissions");
    my @user_permissions = uniq(@old_user_permissions,@add_user_permissions); 
    my $user_permissions=join(",",@user_permissions);
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     user_permissions=>$user_permissions,
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                    });
}


# --remove-user-permissions permission1,permission2,permission3, ...
if (defined $remove_user_permissions){
    my @old_user_permissions = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn,"sophomorixUserPermissions");
    my @user_permissions = &remove_from_list($remove_user_permissions,@old_user_permissions);
    my $user_permissions=join(",",@user_permissions);
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     user_permissions=>$user_permissions,
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                    });
}








# -D --user <user> / --deactivate --user <user>
if ($deactivate==1){
    print "Deactivating the account of $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"D",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}



# -L --user <user> / --deactivate --user <user>
if ($lock==1){
    print "Locking the account of $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"L",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}



# -F --user <user> / --freeze --user <user>
if ($freeze==1){
    print "Freezing the account of $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"F",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}


# # --freeze
# if ($freeze ne""){
#     # check if it is really an account
#     if (getpwnam("$freeze")){
#         print "Freezing the account of $freeze:\n";
# 	print "   - $freeze is a valid username.\n";
#     } else {
#         &log_script_exit("$freeze is not a valid username",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }
#     # doing the freeze
#     &update_user_db_entry($freeze, 
#                           "Status=F",
#        #                   "TolerationDate=",
#        #                   "DeactivationDate="
#                          );
#     &user_deaktivieren($freeze);
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }


# -P --user <user> / --permanent --user <user>
if ($permanent==1){
    print "Making the account of $user permanent:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"P",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}


# -T --user <user> / --tolerate --user <user>
if ($tolerate==1){
    print "Tolerating the account of $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"T",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}

# # --permanent
# if ($permanent ne""){
#     # check if it is really an account
#     if (getpwnam("$permanent")){
#         print "Making the account of $permanent permanent:\n";
# 	print "   - $permanent is a valid username.\n";
#     } else {
#         &log_script_exit("$permanent is not a valid username",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }
#     # making the account permanent
#     &update_user_db_entry($permanent, 
#                           "Status=P",
#     #                      "TolerationDate=",
#     #                      "DeactivationDate="
#                          );
#     &user_reaktivieren($permanent);
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }


# -R --user  <user> / --removable --user <user>
if ($removable==1){
    print "Making the account of $user removable by sophomorix-kill:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"R",
#                     tolerationdate=> $tolerationdate=$DevelConf::default_date,
#                     deactivationdate=> $deactivationdate=$DevelConf::default_date,
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}


# # --removable
# if ($removable ne""){
#     # check if it is really an account
#     if (getpwnam("$removable")){
#         print "Making the account of $removable removable by sophomorix-kill:\n";
# 	print "   - $removable is a valid username.\n";
#     } else {
#         &log_script_exit("$removable is not a valid username",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }
#     # doing the removable
#     &update_user_db_entry($removable, 
#                           "Status=R",
#                           "TolerationDate=01.01.1970",
#                           "DeactivationDate=01.01.1970");
#     &user_deaktivieren($removable);
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }



# -K --user <user> / --killable --user <user>
if ($killable==1){
    print "Making the account of $user killable by sophomorix-kill:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"K",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}

# # --killable
# if ($killable ne""){
#     # check if it is really an account
#     if (&check_sophomorix_user("$killable")==1){
#         print "Making the account of $killable killable by sophomorix-kill:\n";
# 	print "   - $killable is a valid username.\n";
#     } else {
#         &log_script_exit("$killable is not a valid username",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }
#     # doing the killable
#     &update_user_db_entry($killable, 
#                           "Status=K",
#  #                         "TolerationDate=01.01.1970",
#  #                         "DeactivationDate=01.01.1970"
#                          );
#     &user_deaktivieren($killable);
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }


# -A --user <user> / --activate --user <user>
if ($activate==1){
    print "Actvating the account of $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"A",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}

# -S --user <user> / --selfactivate --user <user>
if ($selfactivate==1){
    print "Selfctvating the account of $user:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"S",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}


# # --activate
# if ($activate ne""){
#     # check if it is really an account
#     if (getpwnam("$activate")){
#         print "Actvating the account of $activate:\n";
# 	print "   - $activate is a valid username.\n";
#     } else {
#         &log_script_exit("$activate is not a valid username",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     }
#     # activating the account
#     &update_user_db_entry($activate, 
#                           "Status=A",
#                           "TolerationDate=$today",
#                           "DeactivationDate=");
#     &user_reaktivieren($activate);
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }


# -U --user <user> / --usable --user <user>
if ($usable==1){
    print "Setting the account of $user to usable:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"U",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}


# -E --user <user> / --enable --user <user>
if ($enable==1){
    print "Setting the account of $user to enable:\n";
    &AD_user_update({ldap=>$ldap,
                     root_dse=>$root_dse,
                     dn=>$dn,
                     user=>$user,
                     status=>"E",
                     user_count=>"",
                     max_user_count=>"-",
                     date_now=> $time_stamp_AD,
                     json=>$json,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                   });
}



# # --old-mailbox oldlogin --new-mailbox newlogin
# if ($old_mailbox ne "" and $new_mailbox ne ""){
#     print "Renaming mailbox: $old_mailbox --> $new_mailbox\n";
#     &move_mailbox($old_mailbox,$new_mailbox);
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }




# # --kill-all-users
# if ($kill_all_users==1){
#     print "\n\n I will kill all users in 5 seconds!!\n";
#     sleep 1;
#     print "\n\n Hit Ctrl-C to abort!\n\n\n";
#     sleep 5;
#     my @teachers=&fetchstudents_from_adminclass(${DevelConf::teacher});
#     my @students=&Sophomorix::SophomorixAPI::fetchstudents_from_school();
#     my @users=(@teachers,@students);

#     my $count=0;
#     my $max=$#users;
#     foreach my $user_kill (@users){
#         $count++;
#         print "Mark $user_kill as killable. ($count/$max) \n";
#         system("sophomorix-user -K $user_kill");
#     }
#     # kein nscd_stop, da exit folgt.
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }



# # --teacher teacher --scheduled-toleration
# if ($teacher ne"" and $sc_toleration ne "empty"){
#     # check if it is really an account
#     my ($home,$type,$gecos,$group,$uidnumber)=&fetchdata_from_account($teacher);
 
#     if ($type ne "teacher"){
#         &log_script_exit("$teacher is NOT a valid username of type teacher",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#     } else {
#         print "   - $teacher is a valid username and of type 'teacher'\n";
#     }


#     # check date
#     my ($year,$month,$day)=split(/-/,$sc_toleration);
#     # define values, so that check_date does not throw errors 
#     if (not defined $year){
#         $year=9.99;
#     }
#     if (not defined $month){
#         $month=100;
#     }
#     if (not defined $day ){
#         $day=100;
#     }
#     if ($year eq ""){
#         $year=9.99;
#     }
#     if ($month eq ""){
#         $month=100;
#     }
#     if ($day eq "" ){
#         $day=100;
#     }

#     # check if date exists
#     # return 1 when valid
#     # return 0 when invalid
#     my $return=check_date($year,$month,$day);

#     # if date is completely empty, allow this to clear the date in the db
#     if ($sc_toleration eq ""){
#         $return=1;
#     }    

#     if ($return==0){
#         print "Date $sc_toleration is not a valid date ",
#               "(use this syntax: 2012-04-22)\n";
#     } else {
#         $sc_toleration=&date_pg2perl($sc_toleration);
# 	print "   - $sc_toleration is a valid date.\n";
#         # set scheduled-toletration for the account
#         if ($sc_toleration eq ""){
#             print "Removing ScheduledToleration date for $teacher \n";
#         } else {
#             print "Setting ScheduledToleration date for $teacher to $sc_toleration\n";
#         }
#         &update_user_db_entry($teacher, 
#                               "ScheduledToleration=$sc_toleration");
#     }
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }


# # --reset-user
# if ($reset_user ne""){
#     my @users=split(/,/, $reset_user);
#     # repair.directories einlesen
#     &get_alle_verzeichnis_rechte();
#     # fetch permission for all homes
#     &fetch_repairhome();
#     foreach my $user (@users){
#         # check if it is really an account
#         if (getpwnam("$user")){
#             print "Resetting the account of $user:\n";
# 	    print "   - $user is a valid username.\n";
#         } else {
#             &log_script_exit("$user is not a valid username",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#         }
#         # reset the account
#         &reset_user($user);
#         if ($empty_password==1){
#             print "   Setting empty password for $user\n";
#             &set_sophomorix_passwd($user,"");
#         }
#     }
#     &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,$json);
# }

&AD_unbind_admin($ldap);
&log_script_end(\@arguments,\%sophomorix_result,\%sophomorix_config,$json);



############################################################
# subs
############################################################

# sub move_mailbox {
#     my ($old,$new) = @_;

#     &mta_stop();
#     # stop: log out the users, start: needed for renaming
#     &mda_restart();
#     print "Waiting 4 Seconds for cyrus to accept connections ...\n";
#     sleep 4;

#     my $imap=&imap_connect("localhost",${DevelConf::imap_admin});
#     &imap_rename_mailbox($imap,$old,$new);
#     &imap_disconnect($imap);
#     # mailboxes are in 


#     &mta_start();
# }


