#!/usr/bin/perl -w
# This script (sophomorix-query) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# modules
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use Net::LDAP;
use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useqq = 1;
$Data::Dumper::Terse = 1; 
use JSON;
use Sophomorix::SophomorixBase qw(
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_bind_admin
                                 AD_unbind_admin
                                    );

############################################################
# parsing options
############################################################
my %options=();
$Conf::log_level=1; # remove later
my $testopt=GetOptions(\%options, 
                        "help|h",
                        "verbose|v+",
                        "sam|sAMAccountName=s",
                        "sn=s",
                        "gn|givenName=s",
                        "anyname=s",
                        "student",
                        "teacher",
                        "examuser",
                        "globaladministrator",
                        "schooladministrator",
                        "globalbinduser",
                        "schoolbinduser",
                        "computer",
                        "adminclass",
                        "extraclass",
                        "teacherclass",
                        "class",
                        "project",
                        "sophomorix-group",
                        "room",
                        "schoolbase=s",
                        "user-minimal",
                        "user-basic",
                        "user-full",
                        "group-minimal",
                        "group-basic",
                        "group-full",
                        "group-members",
                        "comp-minimal",
                        "comp-basic",
                        "comp-full",
    );



if ($testopt==0){
    print "Option Error\n";
    exit;
}



# option calculations
if (defined $options{'class'}){
    # find the group types
    $options{'adminclass'}=1;
    $options{'extraclass'}=1;
    $options{'teacherclass'}=1;
}



# --help
if (defined $options{'help'}) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlsbeschreibung
   print('
sophomorix-query is a performance optimised was to query AD for users, computers and groups.

Searches are case insensitive:
  --sam GasT      will find Gast,GAST, .....

If you use the following wildcardcharacters, put them in quotation marks:
  --sam "g*"       finds all sAMAccountName that beginn with g

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info
  --filter: show the filter that is used

Search attribute(s) to find a user/group/computer:
(multiple options are connected with & to narrow down the search)
--sam|sAMAccountName <string> 
--sn <string>
--gn|givenName  <string>
# Later
--anyname <string>      (All important name fields: sAMAccountName,sn,givenName, ...)

Limit the query for sophomorix users to a certain sophomorixRole:
(multiple options are connected with | to accumulate the results)
--student               (sophomorixRole=student)
--teacher               (sophomorixRole=teacher)
--examuser              (sophomorixRole=examuser)
--globaladministrator   (sophomorixRole=globaladministrator)
--schooladministrator   (sophomorixRole=schooladministrator)
--globalbinduser        (sophomorixRole=globalbinduser)
--schoolbinduser        (sophomorixRole=schoolbinduser)
--computer              (sophomorixRole=computer)

Limit the query for sophomorix groups to a certain sophomorixType:
(multiple options are connected with | to accumulate the results)
--adminclass          (sophomorixType=adminclass)
--extraclass          (sophomorixType=extraclass)
--teacherclass        (sophomorixType=teacherclass)
--class               (| (sophomorixType=adminclass)(sophomorixType=extraclass)(sophomorixType=teacherclass) )
--project             (sophomorixType=project)
--sophomorix-group    (sophomorixType=sophomorix-group)
--room                (sophomorixType=room)

Performance improvements:

Limit the searchbase (this is faster):
--schoolbase <school> (limit the searchbase to one school or global)
  # maybe later:
  --sub-projectbase (only works together with schoolbase)

What user attributes to return:
--user-minimal    (i. e. for dropdown menues)
--user-basic      (default)
--user-full       (all attributes)

What group attributes to return:
--group-minimal      (i. e. for dropdown menues)
--group-basic        (default)
--group-full         (all attributes)
--group-members      (add members if object is a group)

What computer attributes to return:
--comp-minimal    (i. e. for dropdown menues)
--comp-basic      (default)
--comp-full       (all useful attributes)

Examples:
  Search for all adminclasses and extraclassses of a school for dropdown menue:
  sophomorix-query --schoolbase <school> --extraclass --adminclass --group-minimal

  Search for all users (with data for listing) in a group with the name <7a>:
  sophomorix-query --schoolbase <school> --sam 7a --group-minimal --group-members --user-full

Please see the sophomorix-query(8) man pages for full documentation
');
   print "\n";
   exit;
}


my ($ldap,$root_dse) = &AD_bind_admin();

############################################################

my $single_attrs;
my $multi_attrs;
my $query_attrs;

my $objectclass_filter="";

my $topkey;
my $topcountkey;

my $attr_filter="";
my $role_filter="";
my $type_filter="";

# the search parameters
my $filter;
my $base;
my $scope="sub";
my $search_object="all"; # all is the default if nothing is specified

# the search results, displayed as JSON object
my %search=();
my $max;
my $mesg;



############################################################
# set the search base
############################################################
if (defined $options{'schoolbase'}){
    if ($options{'schoolbase'} eq "global"){
        $base="OU=GLOBAL,".$root_dse;
    } else {
        $base="OU=".$options{'schoolbase'}.",OU=SCHOOLS,".$root_dse;
    }
} else {
    $base=$root_dse;
}



############################################################
# set the filter: ( & (attr_filter) (role_filter) (type_filter) ) 
############################################################
$filter="(& ";

########################################
# set the attribute search filter
########################################
if (defined $options{'sam'} or 
    defined $options{'sn'} or 
    defined $options{'gn'}){
    ###
    $attr_filter=$attr_filter."(& ";
    if (defined $options{'sam'}){
        $attr_filter=$attr_filter."(sAMAccountName=".$options{'sam'}.")";
    }
    if (defined $options{'sn'}){
        $attr_filter=$attr_filter."(sn=".$options{'sn'}.")";
    }
    if (defined $options{'gn'}){
        $attr_filter=$attr_filter."(givenName=".$options{'gn'}.")";
    }
    $attr_filter=$attr_filter." )";
}

########################################
# set the role filter (combined with |)
########################################
if (defined $options{'student'} or 
    defined $options{'teacher'} or 
    defined $options{'examuser'} or 
    defined $options{'globaladministrator'} or 
    defined $options{'schooladministrator'} or 
    defined $options{'globalbinduser'} or 
    defined $options{'schoolbinduser'} or 
    defined $options{'computer'}){
    ###
    $role_filter=$role_filter."(| ";
    if (defined $options{'student'}){
        $role_filter=$role_filter."(sophomorixRole=student)";
        $search_object="user";
    }
    if (defined $options{'teacher'}){
        $role_filter=$role_filter."(sophomorixRole=teacher)";
        $search_object="user";
    }
    if (defined $options{'examuser'}){
        $role_filter=$role_filter."(sophomorixRole=examuser)";
        $search_object="user";
    }
    if (defined $options{'globaladministrator'}){
        $role_filter=$role_filter."(sophomorixRole=globaladministrator)";
        $search_object="user";
    }
    if (defined $options{'schooladministrator'}){
        $role_filter=$role_filter."(sophomorixRole=schooladministrator)";
        $search_object="user";
    }
    if (defined $options{'globalbinduser'}){
        $role_filter=$role_filter."(sophomorixRole=globalbinduser)";
        $search_object="user";
    }
    if (defined $options{'schoolbinduser'}){
        $role_filter=$role_filter."(sophomorixRole=schoolbinduser)";
        $search_object="user";
    }
    if (defined $options{'computer'}){
        $role_filter=$role_filter."(sophomorixRole=computer)";
        $search_object="computer";
    }
    $role_filter=$role_filter." )";
}


########################################
# set the type filter (combined with |)
########################################
if (defined $options{'adminclass'} or 
    defined $options{'extraclass'} or 
    defined $options{'teacherclass'} or 
    defined $options{'project'} or 
    defined $options{'sophomorix-group'} or 
    defined $options{'room'}){
     ###
    $type_filter=$type_filter."(| ";
    if (defined $options{'adminclass'}){
        $type_filter=$type_filter."(sophomorixType=adminclass)";
        $search_object="group";
    }
    if (defined $options{'extraclass'}){
        $type_filter=$type_filter."(sophomorixType=extraclass)";
        $search_object="group";
    }
    if (defined $options{'teacherclass'}){
        $type_filter=$type_filter."(sophomorixType=)";
        $search_object="group";
    }
    if (defined $options{'project'}){
        $type_filter=$type_filter."(sophomorixType=project)";
        $search_object="group";
    }
    if (defined $options{'sophomorix-group'}){
        $type_filter=$type_filter."(sophomorixType=sophomorix-group)";
        $search_object="group";
    }
    if (defined $options{'room'}){
        $type_filter=$type_filter."(sophomorixType=room)";
        $search_object="room";
    }
    $type_filter=$type_filter." )";
}



############################################################
# user attributes to display
############################################################
### default user attrs
my $single_user_attrs=[
      'sAMAccountName',
      'sophomorixRole',
    ];
my $multi_user_attrs=[
      'sophomorixQuota',
    ];
### override the user defaults
if (defined $options{'user-minimal'}){
    $single_user_attrs=[
            'sAMAccountName',
    ];
    $multi_user_attrs=[
    ];
} elsif (defined $options{'user-basic'}){
    # change nothing, use the default
} elsif (defined $options{'user-full'}){
    $single_user_attrs=[
        'sAMAccountName',
        'sophomorixRole',
        'sn',
    ];
    $multi_user_attrs=[
      'sophomorixQuota',
      'memberOf',
    ];
}



############################################################
# computer attributes to display
############################################################
### default computer attrs
my $single_comp_attrs=[
      'sAMAccountName',
      'sophomorixRole',
    ];
my $multi_comp_attrs=[
    ];
### override the computer defaults
if (defined $options{'comp-minimal'}){
    $single_comp_attrs=[
            'sAMAccountName',
    ];
    $multi_comp_attrs=[
    ];
} elsif (defined $options{'comp-basic'}){
    # change nothing, use the default
} elsif (defined $options{'comp-full'}){
    $single_comp_attrs=[
        'sAMAccountName',
        'sophomorixRole',
        'sn',
    ];
    $multi_comp_attrs=[
      'sophomorixQuota',
      'memberOf',
    ];
}


############################################################
# group attributes to display
############################################################
### default group attrs
my $single_group_attrs=[
      'sAMAccountName',
      'sophomorixType',
    ];
my $multi_group_attrs=[
      'sophomorixQuota',
    ];
### override the group defaults
if (defined $options{'group-minimal'}){
    $single_group_attrs=[
            'sAMAccountName',
    ];
    $multi_group_attrs=[
    ];
} elsif (defined $options{'group-basic'}){
    # change nothing, use the default
} elsif (defined $options{'group-full'}){
    $single_group_attrs=[
        'sAMAccountName',
        'sophomorixRole',
        'sn',
    ];
    $multi_group_attrs=[
      'sophomorixQuota',
      'memberOf',
    ];
}

# add the member attribute, if option is given
if (defined $options{'group-members'}){
    push @{ $multi_group_attrs },"member";
}



############################################################
# find out which objectclass to search for
############################################################
if ($search_object eq "user"){
    $topkey="USER";
    $topcountkey="USERCOUNT";
    $objectclass_filter="(objectclass=user)";
    $single_attrs=$single_user_attrs;
    $multi_attrs=$multi_user_attrs;
} elsif ($search_object eq "group"){
    $topkey="GROUP";
    $topcountkey="GROUPCOUNT";
    $objectclass_filter="(objectclass=group)";
    $single_attrs=$single_group_attrs;
    $multi_attrs=$multi_group_attrs;
} elsif ($search_object eq "room"){
    $topkey="ROOM";
    $topcountkey="ROOMCOUNT";
    $objectclass_filter="(objectclass=group)";
    $single_attrs=$single_group_attrs;
    $multi_attrs=$multi_group_attrs;
} elsif ($search_object eq "computer"){
    $topkey="COMPUTER";
    $topcountkey="COMPUTERCOUNT";
    $objectclass_filter="(objectclass=computer)";
    $single_attrs=$single_comp_attrs;
    $multi_attrs=$multi_comp_attrs;
} elsif ($search_object eq "all"){
    # this is the default
    $topkey="ALL";
    $topcountkey="ALLCOUNT";
    $single_attrs=[
      'sAMAccountName',
      'sophomorixRole',
      'sophomorixType',
    ];
    $multi_attrs=[
    ];
}



############################################################
# combine the search filters
############################################################
$filter="(& ".
        "".$objectclass_filter."".
        "".$attr_filter."".
        "".$role_filter."".
        "".$type_filter."".
        " )";



############################################################
# combine the attribute lists
############################################################
@{ $query_attrs }=(@{ $single_attrs },@{ $multi_attrs });



############################################################
# do the search
############################################################
# search for the object
$mesg = $ldap->search(
               base   => $base,
               scope => $scope,
               filter => $filter,
               attrs => $query_attrs,
              );

# display debugging info
if (defined $options{'verbose'} and $options{'verbose'}==1){
    print Dumper (\%options);
    print "BASE:       $base\n";
    print "SCOPE:      $scope\n";
    print "FILTER:     $filter\n";
    print "SEARCH FOR: $search_object\n";
}

# go through results
$max = $mesg->count; 
$search{$topcountkey}=$max; 
for( my $index = 0 ; $index < $max ; $index++) {
    my $entry = $mesg->entry($index);
    my $dn = $entry->dn();
    my $sam=$entry->get_value('sAMAccountName');
    push @{ $search{'LISTS'}{$topkey} }, $sam;
    # work on single value attributes 
    foreach my $attribute ( @{ $single_attrs } ){
        $search{$topkey}{$sam}{$attribute}=$entry->get_value($attribute);    
    }
    # work on multi value attributes
    foreach my $attribute ( @{ $multi_attrs } ){
        if ($attribute eq "member"){
            # member is not needed
            next;
        }
        @{ $search{$topkey}{$sam}{$attribute} }=$entry->get_value($attribute);
    }

    # find group members (users/computers), if needed
    my $topkey_members="";
    my $topcountkey_members="";
    my $toplistkey_members="";
    if (defined $options{'group-members'}){
        my @members = $entry->get_value('member');
        # decide if comuters or users are searched
        if ($search_object eq "group"){
            $topkey_members="MEMBERS";
            $topcountkey_members="MEMBERCOUNT";
            $toplistkey_members="MEMBERLIST";
        } elsif ($search_object eq "room"){
            $topkey_members="COMPUTERS";
            $topcountkey_members="COMPUTERCOUNT";
            $toplistkey_members="COMPUTERLIST";
        } else {
            exit;
        }
        foreach my $member (@members){
            my ($usersam,@rest)=split(/,/,$member);
            $usersam=~s/^CN=//;
            $search{$topkey_members}{$sam}{$usersam}{'sAMAccountName'}=$usersam;
            $search{$topkey_members}{$sam}{$usersam}{'dn'}=$member;
            push @{ $search{'LISTS'}{$toplistkey_members}{$sam} }, $usersam;
            # query the members
            my $base=$member;
            my $scope="base";
            my $filter="(sAMAccountName=".$usersam.")"; # cannot be empty

            if (defined $options{'verbose'} and $options{'verbose'}==1){
                print "\n";
                print "BASE:       $base\n";
                print "SCOPE:      $scope\n";
                print "FILTER:     $filter\n";
                print "SEARCH FOR: @{ $single_attrs }\n";
            }
            my $mesg = $ldap->search( # perform a search
                              base   => $base,
                              scope => $scope,
                              filter => $filter,
#                              attrs => $single_attrs,
                             );
            my $max = $mesg->count; 
            # only one result possible
            my $entry = $mesg->entry(0);
            #my $usam=$entry->get_value('sAMAccountName');
            my $role=$entry->get_value('sophomorixRole');
            # do this with all user attributes ????
#            $search{$topkey_members}{$sam}{$usersam}{$attribute}=$entry->get_value($attribute); 
            $search{$topkey_members}{$sam}{$usersam}{'sophomorixRole'}=$entry->get_value('sophomorixRole'); 
        }
    }
    if (exists $search{'LISTS'}{$toplistkey_members}{$sam}){
        @{ $search{'LISTS'}{$toplistkey_members}{$sam} } = sort @{ $search{'LISTS'}{$toplistkey_members}{$sam} };
    }
}

if (exists $search{'LISTS'}{$topkey}){
    @{ $search{'LISTS'}{$topkey} } = sort @{ $search{'LISTS'}{$topkey} };
}

# print JSON Object
&json_printout(\%search);



# disconnect
&AD_unbind_admin($ldap);


############################################################
# sub
############################################################
sub json_printout {
    my ($ref_search)=@_;
    #print Dumper ($ref_search);
    my $json_obj = JSON->new->allow_nonref;
    my $utf8_pretty_printed = $json_obj->pretty->encode( $ref_search );
    print STDERR "$utf8_pretty_printed";
}
