#!/usr/bin/perl -w
# This script (sophomorix-postinst) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# modules
use strict;
use Sophomorix::SophomorixConfig;
my $conf_dir="/etc/linuxmuster/sophomorix";
my $conf_file=$conf_dir."/sophomorix.conf";
my $conf_file_source="/usr/share/sophomorix/config-templates/sophomorix.conf.template.ini";

print "##### sophomorix-postinst start #####\n";

print "\n";
print "* Testing $conf_file\n";
# create directory
system "mkdir -p $conf_dir";
######################################################################
# copy the default sophomorix.conf if nonexisting
######################################################################
if (-e $conf_file){
    # do nothing
    print "   * File exists, no installation:\n";
    print "     $conf_file\n";
    # LATER: do upgrade sophomorix.conf
} else {
    # copy the template
    print "     Installing $conf_file\n";
    system("install -oroot -groot --mode=0644 $conf_file_source $conf_file");    
}


######################################################################
# copy the school.conf 
######################################################################
# defaults without options in sophomorix-postinst 
my $school="default-school";
my $school_dir=$conf_dir."/".$school;
my $school_file=$school_dir."/school.conf";

# option given, modify the schoolname
if (defined $ARGV[0] and ($ARGV[0] eq "global" or $ARGV[0] eq "linuxmuster-global")){
    print " \nERROR: You cannot create a school with the name $ARGV[0]\n\n\n";
    exit;
} elsif (defined $ARGV[0] and $ARGV[0] ne $school){
    $school=$ARGV[0];
    $school_dir=$conf_dir."/".$school;
    $school_file=$school_dir."/".$school.".school.conf";
}
my $school_file_source="/usr/share/sophomorix/config-templates/school.conf.template.ini";


print "\n";
print "* Testing for $school_file\n";
# create directory
system "mkdir -p $school_dir";
# copy the default sophomorix.conf
if (-e $school_file){
    # do nothing
    print "   * File exists, no installation:\n";
    print "     $school_file\n";
    # LATER: do upgrade sophomorix.conf
} else {
    # copy the template
    print "     Installing $school_file\n";
    system("install -oroot -groot --mode=0644 $school_file_source $school_file");    
}


######################################################################
# update the schema (If the schema is not there --> DO NOTHING)
######################################################################

# testing if schema exists 
print "\n";
print "* Testing for sophomorix schema update\n";
my $ldbsearch_command="ldbsearch -H /var/lib/samba/private/sam.ldb ".
                      "-b CN=Sophomorix-Schema-Version,CN=Schema,CN=Configuration,DC=linuxmuster,DC=local ".
                      "rangeUpper | grep rangeUpper";
#print "$ldbsearch_command\n";
my $stdout=`$ldbsearch_command`;
my $return=${^CHILD_ERROR_NATIVE}; # return of value of last command
#print "RESULT: $return   $stdout\n";
if ($return==0){
    my $version=$stdout;
    $version=~s/rangeUpper//;
    $version=~s/://;
    $version=~s/\s+$//g;# remove trailing whitespace
    $version=~s/^\s+//g;# remove leading whitespace
    print "   * Installed Sophomorix-Schema-Version: <$version>\n";
    print "   * Target    Sophomorix-Schema-Version: <$DevelConf::sophomorix_schema_version>\n";
    if ($DevelConf::sophomorix_schema_version eq $version){
        print "   * No sophomorix schema update needed\n";
    } else {
       
       for( my $number = $version+1 ; $number < $DevelConf::sophomorix_schema_version+1 ; $number++) {
           print "      * Running update to Sophomorix-Schema-Version $number\n"
           # code goes here to run update script ????????
       }
    }

} else {
    print "Something went wrong retrieving Sophomorix-Schema-Version\n";
}

print "\n";
print "##### sophomorix-postinst end #####\n";
