#!/usr/bin/perl -w
# This script (sophomorix-device) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# valid pxe options
# pxe==0 -> no pxe, accounts nach field 10
# pxe==alle anderen -> pxe, accounts nach field 10    (option ml)
#

# field 6, MS-Office-Key
# string: xxxxx-yyyyy-zzzzz-vvvvv-uuuuu


# field 7, MS-Windows-Key
# string: xxxxx-yyyyy-zzzzz-vvvvv-uuuuu

# field 8:
# unused, fuer linuxmuster.net reserviert [0-9a-zA-Z_-.,]

# field 9:
# sophomorixRole
# 

# field 10, new: account_flag (history: last bpbatch option) 
# 0         : device ohne account, mit firewall
# 1         : device ohne account, ohne firewall
# 2-6   
# 

# field 11:
# pxe option

# field 12:
# ???

# field 13:
# unused

# field 14:
# unused

# field 15:
#  sophomorixComment

# sophomorix-device macht
# - nicht: obsolete accounts und raeume entfernen
# - neue accounts und raume anlegen
# - Aufruf: sophomorix-device
# - Rueckgabewerte:
# - 0: alles OK
# - 1: Fehler Allgemein. import_workstations bricht ab



## ???? additional:
# remove workstation homes that have no matching account


## --print
# add this to doku and man page:
# 1. Die Ergebnisdatei entsteht in /etc/linuxmuster/

# 2. Formatieren Sie /etc/linuxmuster/workstations mit Kommentaren:
#      # Das wird eine Überschrift     (1 #-Zeichen)
#      ## Das bleibt unberücksichtigt  (2 #-Zeichen) 

# Todo für ML 6.0
# oneside/twoside konfigurierbar
# Unter 1 aufgeführte Variablen selber ermitteln
# Text in lang-Datei auslagern

# show italcrooms/teacherhosts and classrooms at --print

# modules
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use Term::ANSIColor qw(:constants); # farbiger Text RED, BLUE, ...
# nach jedem Printbefehl wieder auf Standardfarbe zurücksetzen
$Term::ANSIColor::AUTORESET = 1;
use Net::LDAP;
use Net::DNS;
use Net::MAC;
use Date::Calc qw(check_date);
use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useqq = 1;
$Data::Dumper::Terse = 1; 
use JSON;
use File::Basename qw( basename
                       dirname
                     ); 
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 unlock_sophomorix
                                 lock_sophomorix
                                 log_script_start
                                 log_script_end
                                 log_script_exit
                                 backup_auk_file
                                 get_passwd_charlist
                                 get_plain_password
                                 check_options
                                 config_sophomorix_read
                                 result_sophomorix_init
                                 result_sophomorix_add
                                 result_sophomorix_check_exit
                                 result_sophomorix_print
                                 dns_query_ip
                                 json_dump
                                 filelist_fetch
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_school_create
                                 AD_get_passwd
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_computer_create
                                 AD_computer_update
                                 AD_group_create
                                 AD_group_update
                                 AD_group_kill
                                 AD_group_addmember
                                 AD_group_removemember
                                 AD_get_schoolname
                                 AD_get_name_tokened
                                 AD_get_AD_for_device
                                 AD_get_full_devicedata
                                 AD_object_search
                                 AD_user_kill
                                 AD_computer_kill
                                 AD_dns_get
                                 AD_dns_create
                                 AD_dns_zonecreate
                                 AD_dns_kill
                                 AD_dns_zonekill
                                    );



my @arguments = @ARGV;

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
$Conf::log_level=1;
my $help=0;
my $info=0;
my $json=0;
my $list_files=0;
my $no_sync=0;
my $birthdate="1970-01-01";
my $add_example_line="";
my @password_chars=&get_passwd_charlist();
my $sophomorix_first_password="";

# schools that have been created in this script
my $role="";
my $school="";
my $prefix="";
my %school_created=();
$school_created{$school}="created";
# rooms that have been created while the script is running
my %room_created=();
my $dump_files=0;
my $dump_AD=0;
my $print=0;
my $pass="12345678";
my $password="";

# where data from workstation file is saved
my @domcomputers_file=(); # list ordered
my %devices_file=();
# device   -> $name     -> ACCOUNT 0/1
#                       -> FILENAME
#                       -> HWK
#                       -> IPv4
#                       -> MAC
#                       -> MS_OFFICE_KEY
#                       -> MS_WINDOWS_KEY
#                       -> OU
#                       -> PATH_ABS
#                       -> ROOM
#                       -> SCHOOL
#                       -> COMPUTER    (capitalized name)
#                       -> COMPUTER_DOLLAR (capitalized with $)
#
# room     -> $room     -> HOSTS
#                       -> IPv4
#                       -> MAC
#                       -> CLASSROOM=TRUE/FALSE 
# dnsNode  -> $dnsNode  -> $IP
# dnsZone  -> $dnsZone  -> name
# computer -> $computer -> ROOM
#                       -> OU
#                       -> SCHOOL
#                       -> COMPUTER    (capitalized name)
#                       -> COMPUTER_DOLLAR (capitalized with $)
#



# italc
# my $italc_owner="root";
# my $italc_dir="";
# my $italc_conf_dir="/etc/linuxmuster/sophomorix/italc";
# my $italc_conf=$italc_conf_dir."/italcrooms.conf";
# my $italc_key_dir=$italc_conf_dir."/private";
# my $italc_key_dir_admin=$italc_key_dir."/admin";
# my $italc_key_dir_supporter=$italc_key_dir."/supporter";
# my $italc_key_dir_teacher=$italc_key_dir."/teacher";
# # italc
# my $w_coord=169;
# my $h_coord=126;
# my $x_coord="xxxxxxxxxxxx";
# my $y_coord="yyyyyyyyyyyy";
# my @x_coord=(0,171,342,513,0,171,342,513,
#              0,171,342,513,0,171,342,513,
#              0,171,342,513,0,171,342,513,
#              0,171,342,513,0,171,342,513,
#              0,171,342,513,0,171,342,513); # max 40 hosts
# my @y_coord=(0,0,0,0,128,128,128,128,
#              256,256,256,256,384,384,384,384,
#              512,512,512,512,640,640,640,640,
#              768,768,768,768,896,896,896,896,
#              1024,1024,1024,1024,1152,1152,1152,1152); # max 40 hosts
# my %italc_rooms=();
# my @italc_rooms=();

# classrooms
my %class_rooms=();
# ?????????????ß configure classrooms from other
$class_rooms{'j1010'}="seen";
$class_rooms{'j1008'}="seen";
$class_rooms{'bsz-j1010'}="seen";
$class_rooms{'bsz-j1008'}="seen";

my $set_computer_passwords=0;
my $dns_test=0;
my $dns_show=0;
my $dns_kill=0;


my %host_seen=();
my %mac_seen=();
my %ip_seen=();

# # ExamAccounts
# my @adding_examaccounts=();
# my @killing_examaccounts=();
# my @killing_examaccount_rooms=();



# Computers
my @adding_computers=();
my @updating_computers=();
my @killing_computers=();
my @killing_computer_rooms=();

# Rooms
my @updating_rooms=();

# dnsZones
my @adding_dnszones=();
my @killing_dnszones=();

# dnsNodes
my @adding_dnsnodes=();
my @killing_dnsnodes=();

# hardwareclasses
my @adding_hardwareclasses=();
my %adding_hardwareclasses=();

my @killing_hardwareclasses=();
my %killing_hardwareclasses=();

my %addmembers_hardwareclasses=();
my %killmembers_hardwareclasses=();

my %update_computer=(); # device -> count
my %update_room=();

my %pxe = qw(ml ok
            );

my $device="";

my %ms_key_ok = ();
$ms_key_ok{"---"}="ok";
$ms_key_ok{""}="ok";



# Parsen der Optionen
my $testopt=GetOptions(
       "help|h" => \$help,
       "i|info" => \$info,
       "json|j+" => \$json,
       "verbose|v+" => \$Conf::log_level,
       "list-files" => \$list_files,
       "p|print" => \$print,
       "dump-AD" => \$dump_AD,
       "dump-files" => \$dump_files,
       "no-sync|nosync" => \$no_sync,
       "set-computer-passwords" => \$set_computer_passwords,
       "dns-test" => \$dns_test,
       "dns-kill" => \$dns_kill,
       "dns-show" => \$dns_show,
       "password=s" => \$password,
       "device|d=s" => \$device,
       "add-example-line=s" => \$add_example_line,
#       "italc-dir=s" => \$italc_dir,
          );


my %sophomorix_result=&result_sophomorix_init("sophomorix-device");
# Prüfen, ob Optionen erkannt wurden
&check_options($testopt,\%sophomorix_result,$json);

# Reading Configuration
my ($ldap,$root_dse) = &AD_bind_admin(\@arguments,\%sophomorix_result,$json);
my $root_dns=&AD_dns_get($root_dse);
my %sophomorix_config=&config_sophomorix_read($ldap,$root_dse,\%sophomorix_result);
#my $smb_pwd=&AD_get_passwd($DevelConf::sophomorix_AD_admin,$DevelConf::secret_file_sophomorix_AD_admin); # needed for using samba-tool
my ($smb_admin_pass)=&AD_get_passwd($DevelConf::sophomorix_file_admin,
                                     $DevelConf::secret_file_sophomorix_file_admin);

my @filelist=&filelist_fetch({filetype=>"devices",
                              sophomorix_config=>\%sophomorix_config,
                            });

# set linuxmuster.local as a dnsZone needed in files
$devices_file{'dnsZone'}{$root_dns}="seen";

#print Dumper(\%sophomorix_config{'FILES'});

############################################################################
# --help
############################################################################
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-device adds Devices to the system:
    DomainComputerAccount
    DNS entries 

Options:
  -h   /  --help
  -i   /  --info
  --info --device <device1>,<device2>,...  detailed view of device
  --list-files              (list processed files and exit)
  -v   /  --verbose
  -vv  /  --verbose --verbose

Synchronize the devices:
  sophomorix-device

Just show what would be done (but do not do it):
  sophomorix-device --no-sync

Show and append example device line:
  --add-example-line /path/to/devices.csv

Managing accounts:
  --set-computer-passwords  (set computer passwords to 12345678)
  --password password       (use password instead of 12345678)

Managing DNS:
  --dns-test (do DNS queries for devices in files)
  --dns-kill (remove all DNS-Nodes and DNS-Zones shown by --dns-show)
  --dns-show (show DNS-Nodes and DNS-Zones created by sophomorix)

Dumping data:                     
  --dump-files -j                  (dump contents of user files)
  --dump-AD -j                     (dump AD data)

Obsolete: Managing italc:
          --italc-dir /path/to/dir  (create italc files in /path/to/dir:
                                   italcroom/globalconfig.xml)


Please see the sophomorix-device(8) man pages for full documentation
');
   print "\n";
   exit 0;
}

############################################################################
# --add-example-line
############################################################################
if ($add_example_line ne ""){
    print "\n";
    my $source=$sophomorix_config{'INI'}{'PATHS'}{'TEMPLATES'}."/devices.csv.template";
    system("cat $source");
    system("cat $source >> $add_example_line");
    print "\n";

    exit;
}


############################################################################
# --list-files (does not modify system)
############################################################################
if ($list_files==1){
    print "\n";
    &print_title("Reading the following device files:");
    foreach my $file (@filelist){
        print "   * $file\n";
    }
    exit;
}



############################################################################
# --dns-test     (does not modify system)
############################################################################
if ($dns_test==1){
    my $res   = Net::DNS::Resolver->new;
    &print_title("Testing if DNS works for devices in these files:");
    foreach my $device_file (@filelist){
        print "   * $device_file\n";
    }
    foreach my $device_file (@filelist){
        my $filename = basename($device_file);
        $school=$sophomorix_config{'FILES'}{'DEVICE_FILE'}{$filename}{'SCHOOL'};
       open(DEVICES,"$device_file") || 
             die "ERROR: $device_file not found!";  
        while(<DEVICES>){
            &analyze_device_line($_,$device_file,$filename,$school);
        }
        close(DEVICES);
    }
    # --dump-files
    if ($dump_files==1){
        &json_dump({json => $json,
                    jsoninfo => "DEVICES_FILE",
                    jsoncomment => "All devices read from all user files",
                    log_level => $Conf::log_level,
                    hash_ref=>\%devices_file,
                    sophomorix_config=>\%sophomorix_config,
                  });
    }
    foreach my $host (@domcomputers_file){
        my $file_ip=$devices_file{'device'}{$host}{"IPv4"};
        my $reply = $res->search($host);
        if ($reply) {
            foreach my $rr ($reply->answer) {
                next unless $rr->type eq "A";
                #print $rr->address, "\n";
                if ($file_ip eq $rr->address){
                    print "OK: $host has IP: ",$rr->address,"\n";
                } else {
                    print "ERROR $host has IP: ",
                          $rr->address," (expected was $file_ip)\n";
                }
            }
        } else {
            # no reply: query failed
             warn "    * query failed: ", 
                 $res->errorstring, 
                 " ($host has expected IP $file_ip)\n";
        }
    }
    exit;
}



############################################################################
# --dns-show / --dns-kill
############################################################################

if ($dns_show==1 or $dns_kill==1){
    my $res   = Net::DNS::Resolver->new;
    my @zonelist=();
    my %zonehash=();
    my @zone_delete=(); # samba-tool command to delete node

    # Fetch dnsZones and their DN
    my $base="DC=DomainDnsZones,".$root_dse;
    my $filter="(&(objectclass=dnsZone) (name=*))";
    my $mesg = $ldap->search(
                      base   => $base,
                      scope => 'sub',
                      filter => $filter,
                      attr => ['cn']
                            );
    my $max_zone = $mesg->count;
    for( my $index = 0 ; $index < $max_zone ; $index++) {
        my $entry = $mesg->entry($index);
        my $admin_description=$entry->get_value('adminDescription');
        my $zone_name=$entry->get_value('name');
        if (defined $admin_description and # attribute is defined
           $admin_description=~m/^$DevelConf::dns_zone_prefix_string/ and # attribute starts with prefix
           $zone_name ne $root_dns # do not add $root_dns 
           ){
            # list of sophomorix dnsZones without $root_dns
            # these Zones will be deleted
            push @zonelist, $zone_name;

        }
        my ($count,$dn_dns_zone,$cn_dns_zone,$info)=
            &AD_object_search($ldap,$root_dse,"dnsZone",$zone_name);
        $zonehash{$zone_name}{'DN'}=$dn_dns_zone;
        $zonehash{$zone_name}{'CN'}=$cn_dns_zone;
        $zonehash{$zone_name}{'count'}=$count;
        $zonehash{$zone_name}{'adminDescription'}=$info;
    }
    # add the $root_dns zone (will not be deleted later)
    unshift @zonelist, $root_dns;

    # print output starts here
    my $zone_count=1;
    foreach my $zone (@zonelist){
        &Sophomorix::SophomorixBase::print_title("dnsZone $zone_count) $zone:");
        # dnsNodes in this dnsZone
        my $base=$zonehash{$zone}{'DN'};
        my $filter="(&(objectclass=dnsNode) (name=*) (adminDescription=".
                   $DevelConf::dns_node_prefix_string.
                   "*))";
        my $mesg = $ldap->search(
                      base   => $base,
                      scope => 'sub',
                      filter => $filter,
                      attr => ['cn']
                            );
        my $max_node = $mesg->count;
        for( my $index = 0 ; $index < $max_node ; $index++) {
            my $entry = $mesg->entry($index);
            my $name=$entry->get_value('name');
            my $ipv4=&Sophomorix::SophomorixBase::dns_query_ip($res,$name);
            print "   * $name  ->  $ipv4\n";
            if ($dns_kill==1){
                &AD_dns_kill({ldap=>$ldap, 
                              root_dse=>$root_dse,
                              root_dns=>$root_dns,
                              dns_zone=>$zone,
                              dns_node=>$name,
                              dns_ipv4=>$ipv4,
                              smb_pwd=>$smb_admin_pass,
                            });
           }
        }
        if ($dns_kill==1){
            if ($zone ne $root_dns){
            &AD_dns_zonekill({ldap=>$ldap, 
                              root_dse=>$root_dse,
                              dns_zone=>$zone,
                              smb_pwd=>$smb_admin_pass,
                            });
            } else {
                print "   * Skipping killing provisioned zone $zone\n";
            }
            $zone_count++;
        }
    }
    exit;
}


# ===========================================================================
# fetching data
# ===========================================================================
&print_title("Asking the system for Computers and DNS data ...");

my ($ref_AD_device) = &AD_get_AD_for_device({ldap=>$ldap,
                                             root_dse=>$root_dse,
                                             root_dns=>$root_dns,
                                             sophomorix_config=>\%sophomorix_config,
                                           });
# fetch system data (OLD)
#my ($ref_AD_device_old) = &AD_get_AD({ldap=>$ldap,
#                                  root_dse=>$root_dse,
#                                  root_dns=>$root_dns,
#                                  computers=>"TRUE",
#                                  rooms=>"TRUE",
#                                  #examaccounts=>"TRUE",
#                                  dnszones=>"TRUE",
#                                  dnsnodes=>"TRUE",
#                                  sophomorix_config=>\%sophomorix_config,
#                                });


#print Dumper( $ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{'j1008p01'} );
#print Dumper( $ref_AD_device->{'objectclassOLD'}{'dnsNode'}{$DevelConf::dns_node_prefix_string}{'j1008p01'} );


#print Dumper($ref_AD_device_old->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{'j1008p01'});
#exit;

# /etc/linuxmuster/classroom
# ?????????????????????????
#&get_classrooms();


# --dump-AD
if ($dump_AD==1){
    &json_dump({json => $json,
                jsoninfo => "SEARCH",
                jsoncomment => "AD Content",
#                hash_ref=>\%AD,
                hash_ref=>$ref_AD_device,
                sophomorix_config=>\%sophomorix_config,
               });
}


if ($print==1){
    print "--print not working\n";
    exit;
}

# # ===========================================================================
# # --print     (does not modify system)
# # ===========================================================================
# if ($print==1){
#     if (not -e ${host_workstation}){
#         print "\n$host_workstation does not exist\n\n";
#         exit 1;
#     }

#     my $admins="";
#     if (defined $Conf::admins_print){
#         if ($Conf::admins_print ne ""){
# 	    $admins=$Conf::admins_print;
#         }
#     }

#     my $out_base="/etc/linuxmuster/workstations_formatted";
#     my $out_dir="/etc/linuxmuster";
#     my $out_file="$out_base".".tex";
#     my $out_file_dvi="$out_base".".dvi";
#     my @line=();
#     my $host=0; # counter for the hosts
#     # draw a horizontal line in the table after this many lines of text
#     my $hor_lines=5; 
#     my $line_count=1;

#     print "Writing to $out_file";
#     open(TEX, ">$out_file");

#     print TEX '\documentclass[a4paper, twoside]{article}',"\n",
#           '\usepackage{longtable}',"\n",
#           '\usepackage{ngerman}',"\n",
#           '\usepackage{layout}',"\n",
#           '\usepackage{fancyhdr}',"\n",
#           '\usepackage{lastpage}',"\n",
#           '\setlength{\oddsidemargin}{-5mm}',"\n",
#           '\setlength{\evensidemargin}{-16.8mm}',"\n",
#           '\setlength{\textwidth}{180mm}',"\n",
#           '\setlength{\textheight}{255mm}',"\n",
#           '\setlength{\topmargin}{-20mm}',"\n",
#           '\pagestyle{fancy}',"\n",
#           "\\lhead{$Conf::schul_name}","\n",
#           "\\rhead{Seite \\thepage/\\pageref{LastPage}}","\n",
#           "\\cfoot{$admins}","\n",
#           '\pagestyle{fancy}',"\n",
#           '\renewcommand{\baselinestretch}{1.2}',"\n\n",

#           '\begin{document}',"\n\n",
#           # show layout of page
#           # '\layout',"\n\n",
#           '\begin{longtable}{|r|c|c|c|c|c|} ',"\n",
#           '   \caption*{\large \bfseries Rechner und ',
#           '             Drucker ',
#           "($Conf::schul_name)",
#           '}\\\\ \\hline',"\n",
#           '   \bfseries Nr. & \bfseries DNS-Name & \bfseries Raum & ',
#           '      \bfseries HW-Klasse & \bfseries IP-Adresse & ',
#           '      \bfseries MAC-Adresse \\\\ \hline \hline',"\n",
#           '   \endhead',"\n",
#           '      \hline \multicolumn{6}{r}{Fortsetzung auf der n\"{a}chsten Seite ...}',"\n",
#           '   \endfoot',"\n",
#           '      \hline ',"\n",
#           '   \endlastfoot',"\n";

#     open(IN, "<${host_workstation}");
#     while(<IN>){
#         chomp();
#         my $line=$_;
#         if ($line eq "") {
# 	    next;
#         } elsif(/^\#\#/){
# 	    print "Comment $line \n";
#         } elsif (/^\#/){
# 	    print "Header $line \n";
#             s/^\#//g;
#             if ($line eq "") {
# 	        next;
#             }
#             $line=&latexize_string($line);
#             print TEX "\\hline \\hline  ",
#                  "\\multicolumn{6}{|l|}{\\rule{0mm}{4mm}\\bfseries $line}",
#                  " \\\\ \\hline ","\n";
#         } else {
#             @line = split(/;/);
#             $host++;
#             $host=&latexize_string($host);
#             $line[1]=&latexize_string($line[1]);
#             $line[2]=&latexize_string($line[2]);
#             $line[3]=&latexize_string($line[3]);
#             $line[4]=&latexize_string($line[4]);
#             $line="$host & $line[1] & $line[0] & $line[2]".
#                   " & $line[4] & \\texttt{$line[3]} \\\\ ";
#             print TEX $line; 
#             # Horizontal lines
#              if ($line_count==$hor_lines){
#                  print TEX ' \hline',"\n";
#                  $line_count=0;
#              } else {
#                  print TEX "\n";
#              }
#              $line_count++;
#         }
#     }
#     close(IN);

#     print TEX '\end{longtable}',"\n";
#     print TEX "\\textbf{$host Rechner/Drucker sind im p\"{a}dagogischen ",
#               "Netz ($Conf::schul_name).} \n \n";
#     print TEX "Ausdruck: \\today .",
#               "\n \n",
#               "\\textbf{Die Netzwerkadministratoren:}",
#               "\n",
#               "$admins","\n";
#     print TEX "\n",'\end{document}',"\n";
#     close(TEX);

#     # latex
#     system("cd $out_dir; latex $out_file");
#     system("cd $out_dir; latex $out_file");
#     system("cd $out_dir; dvips $out_file_dvi");
#     exit;
# }


# --info (overview)
if ($info==1 and $device eq ""){
    my ($ref_devices) = &AD_get_AD_for_device({ldap=>$ldap,
                                               root_dse=>$root_dse,
                                               root_dns=>$root_dns,
                                               sophomorix_config=>\%sophomorix_config,
                                             });

    {
        my $jsoninfo="DEVICES";
        my $jsoncomment="The sophomorix devices";
        &json_dump({json => $json,
                    jsoninfo => $jsoninfo,
                    jsoncomment => $jsoncomment,
                    object_name => "",
                    log_level => $Conf::log_level,
                    hash_ref => $ref_devices,
                    sophomorix_config => \%sophomorix_config,
                   });
    }
    exit;
}


# --info --device <device>
if ($device ne "" and $info==1){
    my $ref_devices=&AD_get_full_devicedata({ldap=>$ldap,
                                             root_dse=>$root_dse,
                                             root_dns=>$root_dns,
                                             devicelist=>$device,
                                             sophomorix_config=>\%sophomorix_config,
                                            });
    #print Dumper($ref_devices);
    my $jsoninfo="DEVICE";
    my $jsoncomment="One sophomorix device";
    &json_dump({json => $json,
                jsoninfo => $jsoninfo,
                jsoncomment => $jsoncomment,
                object_name => $device,
                log_level => $Conf::log_level,
                hash_ref => $ref_devices,
                sophomorix_config => \%sophomorix_config,
               });
    exit;
}

# # ===========================================================================
# # --info (does not modify system)
# # ===========================================================================
# if ($info==1){
#     print "\n";
#     &print_title("Reading the following device files:");
#     foreach my $file (@filelist){
#         print "   * $file\n";
#     }

#     # fetch and sort rooms
#     my @rooms=();
#     while (my ($room,$v) = each %rooms_system){
#         push @rooms, $room;
#     }
#     @rooms = sort @rooms;

#     foreach my $room (@rooms){
#         my $classroom="";
#         my $italcroom="";
#         if (exists $class_rooms{$room}){
#             $classroom="(CLASSROOM) ";
#         }
#         if (exists $italc_rooms{$room}){
#             $italcroom="(ITALC ROOM) ";
#         }
# 	print "ROOM: $room ${classroom}${italcroom}\n";
#         # fetch and sort examaccounts
#         my @examaccounts=();
#         while (my ($account,$room_entry) = each %examaccounts_system){
#             #print $account , " ", $roomentry, "\n";
#             if ($room_entry eq $room){
#                 push @examaccounts,$account;
#             }
#         }
#         @examaccounts = sort @examaccounts;
#         foreach my $account (@examaccounts){
#             print "    HOST: $account\n";
#         }
#     }
#     exit 0;
# }




############################################################################
# reading and checking files
############################################################################
# reading and checking all device files
foreach my $device_file (@filelist){
    my $filename = basename($device_file);
    $school=$sophomorix_config{'FILES'}{'DEVICE_FILE'}{$filename}{'SCHOOL'};
    &print_title("Reading $device_file");
    open(DEVICES,"$device_file") || 
         die "ERROR: $device_file not found!";  
    while(<DEVICES>){
        &analyze_device_line($_,$device_file,$filename,$school);
    }
    # sort some lists
    foreach my $room (keys %{$devices_file{'room'}}) {
        @{ $devices_file{'room'}{$room}{'HOSTLIST'} } = sort @{ $devices_file{'room'}{$room}{'HOSTLIST'} };
        @{ $devices_file{'room'}{$room}{'MACLIST'} } = sort @{ $devices_file{'room'}{$room}{'MACLIST'} };
        @{ $devices_file{'room'}{$room}{'IPv4LIST'} } = sort @{ $devices_file{'room'}{$room}{'IPv4LIST'} };
    }
    close(DEVICES);
}


############################################################################
# Decide what must be done
############################################################################

# # ExamAccounts to kill
# foreach my $examaccount (keys %{$ref_AD_device->{'objectclass'}{'user'}{'examaccount'}}) {
#     if (not exists $devices_file{'device'}{$examaccount}){
#         # host is not in file anymore
#         &push_kill_examaccount($examaccount);
#     }
# }


# # ExamAccounts to add
# foreach my $examaccount (keys %{$devices_file{'device'}}) {
#     if (not exists $ref_AD_device->{'objectclass'}{'user'}{'examaccount'}{$examaccount}){
#         # host is not in system
#         # examaccounts only for classroom devices and 
#         my $room=$devices_file{'device'}{$examaccount}{'ROOM'};
#         if (exists $class_rooms{$room} and $devices_file{'device'}{$examaccount}{'ACCOUNT'} eq "TRUE"){
#             &push_add_examaccount($examaccount);
#         } else {
#             # not adding
#         }
#     } else {
#         # device is not in correct room -> update (kill and add)
#         if ($ref_AD_device->{'objectclass'}{'user'}{'examaccount'}{$examaccount}{'room'} ne 
#             $devices_file{'device'}{$examaccount}{'ROOM'}){
#             if($Conf::log_level>=2){
# 	        print "$examaccount: Changed room from ",
#                       "$ref_AD_device->{'objectclass'}{'user'}{'examaccount'}{$examaccount}{'room'}",
#                       " to $devices_file{'device'}{$examaccount}{'ROOM'}\n";
#             }
#             &push_kill_examaccount($examaccount);
#             &push_add_examaccount($examaccount);
#         }
#         # sophomorixAdminFile ist not correct
#         if ($ref_AD_device->{'objectclass'}{'user'}{'examaccount'}{$examaccount}{'sophomorixAdminFile'} ne 
#             $devices_file{'device'}{$examaccount}{'FILENAME'}){
#             if($Conf::log_level>=2){
# 	        print "$examaccount: Was moved from file ",
#                       "$ref_AD_device->{'objectclass'}{'user'}{'examaccount'}{$examaccount}{'sophomorixAdminFile'}",
#                       " to $devices_file{'device'}{$examaccount}{'FILENAME'}\n";
#             }
#             &push_kill_examaccount($examaccount);
#             &push_add_examaccount($examaccount);
#         }


#     }
# }


# # ExamAccount rooms to kill
# foreach my $room (keys %{$ref_AD_device->{'room'}}) {
#     if (not exists $devices_file{'room'}{$room}){
#         # host is not in file anymore
#         &push_kill_examaccount_room($room);
#     }
# }


# computer rooms to kill
foreach my $room (keys %{$ref_AD_device->{'room'}}) {
    if (not exists $devices_file{'room'}{$room}){
        # host is not in file anymore
        &push_kill_computer_room($room);
    }
}



# computers to kill
foreach my $device (keys %{$ref_AD_device->{'computer'}}) {
    if (not exists $devices_file{'computer'}{$device}){
        # host is not in file anymore
        &push_kill_computer($device);
    }
}



# computers to add
foreach my $device (keys %{$devices_file{'computer'}}) {
    if (not exists $ref_AD_device->{'computer'}{$device} ){
        # nonexisting --> add account
        &push_add_computer($device);
        #&push_update_computer($device); # update ????
    }
}



# computers to update
foreach my $device (keys %{$devices_file{'computer'}}) {
    if (exists $ref_AD_device->{'computer'}{$device} ){
        my $update=0;
        # update
        if($Conf::log_level>=3){
            print "\n"; 
            print "Test for update $device\n";
            print "Files  9: $devices_file{'computer'}{$device}{'sophomorixRole'}\n";
            print "AD     9: $ref_AD_device->{'compter'}{$device}{'sophomorixRole'}\n";
            print "Files 15: $devices_file{'computer'}{$device}{'sophomorixComment'}\n";
            print "AD    15: $ref_AD_device->{'computer'}{$device}{'sophomorixComment'}\n";
        }
        # sophomorixRole
        if ($devices_file{'computer'}{$device}{'sophomorixRole'} eq $ref_AD_device->{'computer'}{$device}{'sophomorixRole'}){
            # no update if equal
        } elsif ($devices_file{'computer'}{$device}{'sophomorixRole'} eq "" and
                 $ref_AD_device->{'computer'}{$device}{'sophomorixRole'} eq $sophomorix_config{'INI'}{'GLOBAL'}{'COMPUTERROLE_DEFAULT'}
	    ){
            # no update, both are on default value
        } else {
            $update_computer{$device}{'REPLACE'}{'sophomorixRole'}=$devices_file{'computer'}{$device}{'sophomorixRole'};
            $update++;
        }

        # sophomorixComputerIP
        if (defined $ref_AD_device->{'computer'}{$device}{'sophomorixComputerIP'}){
            if ($devices_file{'computer'}{$device}{'sophomorixComputerIP'} eq $ref_AD_device->{'computer'}{$device}{'sophomorixComputerIP'}){
                # no update if equal
            } else {
                $update_computer{$device}{'REPLACE'}{'sophomorixComputerIP'}=$devices_file{'computer'}{$device}{'sophomorixComputerIP'};
                $update++;
            }
        }

        # sophomorixComputerMAC
        if (defined $ref_AD_device->{'computer'}{$device}{'sophomorixComputerMAC'}){
            if ($devices_file{'computer'}{$device}{'sophomorixComputerMAC'} eq $ref_AD_device->{'computer'}{$device}{'sophomorixComputerMAC'}){
                # no update if equal
            } else {
                $update_computer{$device}{'REPLACE'}{'sophomorixComputerMAC'}=$devices_file{'computer'}{$device}{'sophomorixComputerMAC'};
                $update++;
            }
        }

        # sophomorixComputerRoom
        if (defined $ref_AD_device->{'computer'}{$device}{'sophomorixComputerRoom'}){
            if ($devices_file{'computer'}{$device}{'sophomorixComputerRoom'} eq $ref_AD_device->{'computer'}{$device}{'sophomorixComputerRoom'}){
                # no update if equal
            } else {
                $update_computer{$device}{'REPLACE'}{'sophomorixComputerRoom'}=$devices_file{'computer'}{$device}{'sophomorixComputerRoom'};
                $update++;
            }
        }

        # sophomorixComment
        if ($devices_file{'computer'}{$device}{'sophomorixComment'} eq $ref_AD_device->{'computer'}{$device}{'sophomorixComment'}){
            # no update if equal
        } elsif ($devices_file{'computer'}{$device}{'sophomorixComment'} eq "" and
                 $ref_AD_device->{'computer'}{$device}{'sophomorixComment'} eq "---"
	    ){
            # no update, both are on default value
        } else {
            $update_computer{$device}{'REPLACE'}{'sophomorixComment'}=$devices_file{'computer'}{$device}{'sophomorixComment'};
            $update++;
        }
        
        if ($update>0){
            $update_computer{$device}{'COUNT'}=$update; # count how many attributes must be updated
            &push_update_computer($device);
        }
    }
}



# rooms to update
foreach my $room (keys %{$devices_file{'room'}}) {
    print "HERE: Testing room $room\n";
    if (exists $ref_AD_device->{'room'}{$room} ){
        my $update=0;
        print "   HERE: $room is in AD\n";
        # Test if list have the same length
        my $devices_items;
        my $AD_items;
        # HOSTNAME
        $devices_items=$#{ $devices_file{'room'}{$room}{'HOSTLIST'} }+1;
        $AD_items=$#{ $ref_AD_device->{'room'}{$room}{'sophomorixRoomComputers'} }+1;
        print "$devices_items   --> $AD_items"; # ???
        if ($devices_items==$AD_items){
            # test for list entries ??????
        } else {
            $update++;
        }
        # IP
        $devices_items=$#{ $devices_file{'room'}{$room}{'MACLIST'} }+1;
        $AD_items=$#{ $ref_AD_device->{'room'}{$room}{'sophomorixRoomMACs'} }+1;
        print "$devices_items   --> $AD_items"; # ???
        if ($devices_items==$AD_items){
            # test for list entries ??????
        } else {
            $update++;
        }
        # HOSTNAME
        $devices_items=$#{ $devices_file{'room'}{$room}{'IPv4LIST'} }+1;
        $AD_items=$#{ $ref_AD_device->{'room'}{$room}{'sophomorixRoomIPs'} }+1;
        print "$devices_items   --> $AD_items"; # ???
        if ($devices_items==$AD_items){
            # test for list entries ??????
        } else {
            $update++;
        }


        if ($update>0){
            $update_room{$room}{'COUNT'}=$update; # count how many attributes must be updated
            &push_update_room($room);
        }
    }
}



# dnsNodes to kill
foreach my $dnsnode (keys %{$ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}}) {
    if (not exists $devices_file{'dnsNode'}{$dnsnode}){
        # host is not in file anymore
        &push_kill_dnsnode($dnsnode);
    }
}



# dnsNodes to add
foreach my $dnsnode (keys %{$devices_file{'dnsNode'}}) {
    if (not exists $ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{$dnsnode} ){
        # nonexisting --> add account
        &push_add_dnsnode($dnsnode);
    } elsif (exists $ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{$dnsnode} ){
        my $ip_system=$ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{$dnsnode}{'IPv4'};
        my $ip_file=$devices_file{'dnsNode'}{$dnsnode};
        if ($ip_system ne $ip_file){
            # recreate dns entry
            print "WARNING: $dnsnode exists with $ip_system, but should be $ip_file\n";
            &push_kill_dnsnode($dnsnode);
            &push_add_dnsnode($dnsnode);
        } else {
            if($Conf::log_level>=3){
                print "   OK: $dnsnode exists with $ip_system",
                      " (= $ip_file from file)\n";
            }
        }
    }
}



# dnsZones to kill
foreach my $dnszone (keys %{$ref_AD_device->{'dnsZone'}{$DevelConf::dns_zone_prefix_string}}) {
    if (not exists $devices_file{'dnsZone'}{$dnszone}){
        # dns node is not needed anymore, no host
        &push_kill_dnszone($dnszone);
    }
}



# dnsZones to add
foreach my $dnszone (keys %{$devices_file{'dnsZone'}}) {
    if (not exists $ref_AD_device->{'dnsZone'}{$DevelConf::dns_zone_prefix_string}{$dnszone} ){
        # nonexisting --> add dnszone
        &push_add_dnszone($dnszone);
    }
}



# hardwareclasses to kill
foreach my $hwk (keys %{$ref_AD_device->{'hardwareclass'}}) {
    if (not exists $devices_file{'hardwareclass'}{$hwk} ){
        # hwk is not needed anymore
        &push_kill_hardwareclass($hwk);
    }
}



# hardwareclasses to create
foreach my $hwk (keys %{$devices_file{'hardwareclass'}}) {
    if (not exists $ref_AD_device->{'hardwareclass'}{$hwk} ){
        # nonexisting --> add hwk
        &push_add_hardwareclass($hwk);
    }
}



# hardwareclass members to add
foreach my $hwk (keys %{$devices_file{'hardwareclass'}}) {
    # go through all hwk in files
    foreach my $member_file (keys %{$devices_file{'hardwareclass'}{$hwk}}) {
        # go through all members of hwk in files
        # skip if this device has no account
        # the data in $devices_file{'device'}{<device>} uses the small letter name
        my $member_smalletters=$devices_file{'hardwareclass'}{$hwk}{$member_file};
        if ($devices_file{'device'}{$member_smalletters}{'ACCOUNT'} eq "FALSE"){
            next;
        }

        if (not exists $ref_AD_device->{'hardwareclass'}{$hwk}{'member_sAMAccountName'}{$member_file}){
	    $addmembers_hardwareclasses{$member_file}=$hwk;
        }
    }
}



# hardwareclass members to kill
foreach my $hwk (keys %{$ref_AD_device->{'hardwareclass'}}) {
    # go through all hwk in AD
    # if the hwk is going to be deleted, skip removing users
    if (exists $killing_hardwareclasses{$hwk}){
        print "$hwk is going to be killed anyway, skip testing for members to be killed\n";
        next;
    }

    foreach my $member_AD (keys %{$ref_AD_device->{'hardwareclass'}{$hwk}{'member_sAMAccountName'} }) {
        # go through all members of hwk in AD
        if (not exists $devices_file{'hardwareclass'}{$hwk}{$member_AD}){
	    $killmembers_hardwareclasses{$member_AD}=$hwk;
        }
    }
}






# --dump-files
if ($dump_files==1){
    &json_dump({json => $json,
                jsoninfo => "DEVICES_FILE",
                jsoncomment => "All devices read from all user files",
                hash_ref=>\%devices_file,
                sophomorix_config=>\%sophomorix_config,
              });
}


############################################################################
if($no_sync==1){
    # show info about what will be done
    my $count=0;
    # # ExamAccounts
    # print "\n";
    # $count=$#killing_examaccounts+1;
    # &print_title("ExamAccounts that must be killed ($count):");
    # foreach my $ws (@killing_examaccounts){
    #     print "KILL: $ws\n";
    # }
    # print "\n";
    # $count=$#adding_examaccounts+1;
    # &print_title("ExamAccounts that must be added ($count):");
    # foreach my $ws (@adding_examaccounts){
    #     print "ADD: $ws\n";
    # }
    # print "\n";
    # $count=$#killing_examaccount_rooms+1;
    # &print_title("ExamAccounts rooms that must be killed ($count):");
    # foreach my $room (@killing_examaccount_rooms){
    #     print "KILL: $room\n";
    # }

    # computer rooms
    print "\n";
    $count=$#killing_computer_rooms+1;
    &print_title("Computer rooms that must be killed ($count):");
    foreach my $room (@killing_computer_rooms){
        print "KILL: $room\n";
    }

    # Computers
    print "\n";
    $count=$#killing_computers+1;
    &print_title("Computers that must be killed: ($count)");
    foreach my $ws (@killing_computers){
        print "KILL: $ws\n";
    }
    print "\n";
    $count=$#adding_computers+1;
    &print_title("Computers that must be added: ($count)");
    foreach my $ws (@adding_computers){
        print "ADD: $ws\n";
    }
    # updates of computer attributes
    print "\n";
    $count=$#updating_computers+1;
    &print_title("Computers that must be updated: ($count)");
    foreach my $ws (@updating_computers){
        print "UPDATE: $ws ($update_computer{$ws}{'COUNT'} attributes)\n";
    }

    # Rooms
    # updates of group room attributes
    print "\n";
    $count=$#updating_rooms+1;
    &print_title("Rooms that must be updated: ($count)");
    foreach my $room (@updating_rooms){
        print "UPDATE: $room ($update_room{$room}{'COUNT'} attributes)\n";
    }

    # dnsZones
    print "\n";
    $count=$#killing_dnszones+1;
    &print_title("dnsZones that must be killed: ($count)");
    foreach my $dns_zone (@killing_dnszones){
        print "KILL: $dns_zone\n";
    }
    print "\n";
    $count=$#adding_dnszones+1;
    &print_title("dnsZones that must be added: ($count)");
    foreach my $dns_zone (@adding_dnszones){
        print "ADD: $dns_zone\n";
    }

    # dnsNodes
    print "\n";
    $count=$#killing_dnsnodes+1;
    &print_title("dnsNodes that must be killed: ($count)");
    foreach my $dns_node (@killing_dnsnodes){
        print "KILL: $dns_node\n";
    }
    print "\n";
    $count=$#adding_dnsnodes+1;
    &print_title("dnsNodes that must be added: ($count)");
    foreach my $dns_node (@adding_dnsnodes){
        print "ADD: $dns_node\n";
    }

    # hardwareclasses
    print "\n";
    $count=$#killing_hardwareclasses+1;
    &print_title("Hardwareclasses that must be killed ($count):");
    foreach my $hwk (@killing_hardwareclasses){
        print "KILL: $hwk\n";
    }
    print "\n";
    $count=$#adding_hardwareclasses+1;
    &print_title("Hardwareclasses that must be added: ($count)");
    foreach my $hwk (@adding_hardwareclasses){
        print "ADD: $hwk\n";
    }
    print "\n";
    {
        my @computers=();
        foreach my $member (keys %addmembers_hardwareclasses){
            push @computers, $member
        }
	@computers=sort @computers;
        $count=$#computers+1;

        &print_title("Hardwareclass memberships to add ($count):");
        foreach my $member (@computers){
            print "ADD: $member to $addmembers_hardwareclasses{$member}\n";
        }
    }
    print "\n";
    {
        my @computers=();
        foreach my $member (keys %killmembers_hardwareclasses){
            push @computers, $member
        }
	@computers=sort @computers;
        $count=$#computers+1;
        &print_title("Hardwareclass memberships to kill ($count):");
        foreach my $member (@computers){
            print "KILL: $member from $killmembers_hardwareclasses{$member}\n";
        }
    }

    print "\n--no-sync  finished. Nothing changed!\n";
    exit;
} 



&result_sophomorix_check_exit(\%sophomorix_result,\%sophomorix_config,$json);
# ===========================================================================
# Modifying System
# ===========================================================================
&log_script_start(\@arguments,\%sophomorix_result,\%sophomorix_config);
#&get_italcrooms();


# ===========================================================================
# Synchronizing ExamAccounts and Workstations
# ===========================================================================

if ($no_sync==0){ # $no_sync==0 -> SYNC
    ############################################################
    # # kill examaccounts
    # &print_title("ExamAccounts to be killed:");
    # my $kill_count=1;
    # foreach my $exam_account (@killing_examaccounts){
    #     print "   * Killing ExamAccount $exam_account ...\n";
    #     &AD_user_kill({ldap=>$ldap,
    #                    root_dse=>$root_dse,
    #                    login=>$exam_account,
    #                    user_count=>$kill_count,
    #                    sophomorix_config=>\%sophomorix_config,
    #                  });
    #     #system("/usr/sbin/sophomorix-kill --killuser $exam_account");
    # }

    ############################################################
    # # add examaccounts
    # &print_title("ExamAccounts to be added:");
    # my $add_count=1;
    # foreach my $exam_account (@adding_examaccounts){
    #     my $role="examaccount";
    #     my $school=$devices_file{'device'}{$exam_account}{'SCHOOL'};
    #     my $filename=$devices_file{'device'}{$exam_account}{'FILENAME'};
    #     $sophomorix_first_password=&get_plain_password($role,$file,$random,$length,@password_chars);
    #     if (not exists $school_created{$school}){
    #         # create ou
    #         &AD_school_create({ldap=>$ldap,
    #                     root_dse=>$root_dse,
    #                     root_dns=>$root_dns,
    #                     school=>$school,
    #                     creationdate=>$sophomorix_config{'DATE'}{'LOCAL'}{'TIMESTAMP_AD'},
    #                     sophomorix_config=>\%sophomorix_config,
    #                     sophomorix_result=>\%sophomorix_result,
    #                  });
    #         # remember ou
    #         $school_created{$school}="already created";
    #     }
    #     &AD_user_create({ldap=>$ldap, 
    #                      root_dse=>$root_dse,
    #                      user_count=>$add_count,
    #                      login=>$exam_account,
    #                      group=>$devices_file{'device'}{$exam_account}{'ROOM'},
    #                      group_basename=>$devices_file{'device'}{$exam_account}{'ROOM'},
    #                      firstname_ascii=>"Exam",
    #                      surname_ascii=>"Account",
    #                      firstname_utf8=>"Exam",
    #                      surname_utf8=>"Account",
    #                      birthdate=>$birthdate,
    #                      sophomorix_first_password=>$sophomorix_first_password,
    #                      role=>"examaccount",
    #                      type=>"room",
    #                      school=>$school,
    #                      creationdate=>$sophomorix_config{'DATE'}{'LOCAL'}{'TIMESTAMP_AD'},
    #                      tolerationdate=>"---",
    #                      deactivationdate=>"---",
    #                      status=>"P",
    #                      file=>$filename,
    #                    });
    #     $add_count++;
    #     # make sure that the room exists
    #     # use the saved, tokened value
    #     my $room_saved=$devices_file{'device'}{$exam_account}{'ROOM'};
    #     my $examaccount_token=$school."-".$DevelConf::examaccount;
    #     &AD_group_create({ldap=>$ldap,
    #                       root_dse=>$root_dse,
    #                       group=>$room_saved,
    #                       group_basename=>$room_saved,
    #                       description=>$room_saved,
    #                       school=>$school,
    #                       status=>"P",
    #                       type=>"room",
    #                       creationdate=>$sophomorix_config{'DATE'}{'LOCAL'}{'TIMESTAMP_AD'},
    #                      });
    #     # add examaccount to its room
    #     &AD_group_addmember({ldap => $ldap,
    #                          root_dse => $root_dse, 
    #                          group => $room_saved,
    #                          addmember => $exam_account,
    #                         });   
    # }

    ############################################################
    # # Kill the rooms of examaccounts
    # &print_title("Rooms to be killed:");
    # my $kill_room_count=1;
    # foreach my $room (@killing_examaccount_rooms){
    #     print "   * Killing ExamAccount Room $room ...\n";
    #     &AD_group_kill({ldap=>$ldap,
    #                     root_dse=>$root_dse,
    #                     group=>$room,
    #                     type=>"room",
    #                     group_count=>$kill_room_count,
    #                     sophomorix_config=>\%sophomorix_config,
    #               });
    # }

    ############################################################
    # Kill the rooms of computers
    print "\n";
    &print_title("Computer rooms to be killed:");
    my $kill_computer_room_count=1;
    foreach my $room (@killing_computer_rooms){
        print "   * Killing Computer Room $room ...\n";
        &AD_group_kill({ldap=>$ldap,
                        root_dse=>$root_dse,
                        root_dns=>$root_dns,
                        group=>$room,
                        type=>"room",
                        group_count=>$kill_computer_room_count,
                        sophomorix_config=>\%sophomorix_config,
                  });
    }

    ############################################################
    # Kill computers
    print "\n";
    my $max_computer_count_kill=$#killing_computers+1;

    &print_title("Killing $max_computer_count_kill computers");
    my $computer_count_kill=1;
    foreach my $computer (@killing_computers){
        &AD_computer_kill({ldap=>$ldap,
                           root_dse=>$root_dse,
                           computer=>$computer,
                           computer_count=>$computer_count_kill,
                           max_computer_count=>$max_computer_count_kill,
                           json=>$json,
                           sophomorix_config=>\%sophomorix_config,
                           sophomorix_result=>\%sophomorix_result,
                         });
        $computer_count_kill++;
    }

    ############################################################
    # Add computers
    print "\n";
    my $max_computer_count_create=$#adding_computers+1;
    &print_title("Adding $max_computer_count_create computers:");
    my $computer_count_create=1;
    foreach my $computer (@adding_computers){
        my $school=$devices_file{'computer'}{$computer}{'SCHOOL'};
        my $room_saved=$devices_file{'computer'}{$computer}{'ROOM'};
        my $room_basename=$devices_file{'computer'}{$computer}{'ROOM_BASENAME'};
        my $ws_saved=$devices_file{'computer'}{$computer}{'COMPUTER'};
        my $filename=$devices_file{'computer'}{$computer}{'FILENAME'};
        my $ipv4=$devices_file{'computer'}{$computer}{'sophomorixComputerIP'};
        my $mac=$devices_file{'computer'}{$computer}{'sophomorixComputerMAC'};
        if (not exists $school_created{$school}){
            # create ou
            &AD_school_create({ldap=>$ldap,
                               root_dse=>$root_dse,
                               root_dns=>$root_dns,
                               school=>$school,
                               smb_admin_pass=>$smb_admin_pass,
                               sophomorix_config=>\%sophomorix_config,
                               sophomorix_result=>\%sophomorix_result,
                             });
            # remember ou
            $school_created{$school}="already created";
        } else {
            print "   * OU $school already created\n";
        }

        my $role;
        if ($devices_file{'computer'}{$computer}{'sophomorixRole'} ne ""){
            $role=$devices_file{'computer'}{$computer}{'sophomorixRole'};
        } else {
            $role=$sophomorix_config{'FILES'}{'DEVICE_FILE'}{$filename}{'sophomorixRole'};
        }
        my $sophomorix_comment;
        if ($devices_file{'computer'}{$computer}{'sophomorixComment'} ne ""){
            $sophomorix_comment=$devices_file{'computer'}{$computer}{'sophomorixComment'};
        }

        &AD_computer_create({ldap=>$ldap, 
                             root_dse=>$root_dse,
                             computer_count=>$computer_count_create,
                             max_computer_count=>$max_computer_count_create,
                             name=>$ws_saved,
                             room=>$room_saved,
                             room_basename=>$room_basename,
                             role=>$role,
                             sophomorix_comment=>$sophomorix_comment,
		             type=>$sophomorix_config{'FILES'}{'DEVICE_FILE'}{$filename}{'sophomorixType'},
                             school=>$school,
                             filename=>$filename,
                             ipv4=>$ipv4,
                             mac=>$mac,
                             json=>$json,
                             sophomorix_config=>\%sophomorix_config,
                             sophomorix_result=>\%sophomorix_result,
                           });
        $computer_count_create++;
        # make sure that the room exists
        if (not exists $room_created{$school}{$room_basename}){
            my $room_description=$room_basename." in ".$school;
            &AD_group_create({ldap=>$ldap,
                              root_dse=>$root_dse,
                              root_dns=>$root_dns,
                              group=>$room_saved,
                              group_basename=>$room_basename,
                              description=>$room_description,
                              school=>$school,
                              status=>"P",
                              type=>$sophomorix_config{'FILES'}{'DEVICE_FILE'}{$filename}{'sophomorixType'},
    	      		      sub_ou=>"OU=".$room_basename.",".$sophomorix_config{'INI'}{'OU'}{'AD_devices_ou'},
                              smb_admin_pass=>$smb_admin_pass,
                              sophomorix_config=>\%sophomorix_config,
                              sophomorix_result=>\%sophomorix_result,
                            });
            # remember group
            $room_created{$school}{$room_basename}="already created";
        } else {
            print "   * room $room_basename in school $school already created\n";
        }
        # add computer to its room
        &AD_group_addmember({ldap => $ldap,
                             root_dse => $root_dse, 
                             group => $room_saved,
                             addmember => $ws_saved,
                            });   
    }

    ############################################################
    # Updating computers
    print "\n";
    my $max_computer_count_update=$#updating_computers+1;
    &print_title("Updating $max_computer_count_update computers:");
    my $computer_count_update=1;
    foreach my $computer (@updating_computers){
        &AD_computer_update({ldap=>$ldap,
                             root_dse=>$root_dse,
                             computer=>$computer,
                             computer_count=>$computer_count_update,
                             attrs_count=>$update_computer{$computer}{'COUNT'},
                             replace=>\%update_computer,
                             max_computer_count=>$max_computer_count_update,
                             json=>$json,
                             sophomorix_config=>\%sophomorix_config,
                             sophomorix_result=>\%sophomorix_result,
                           });
        $computer_count_update++;
    }

    ############################################################
    # Updating rooms
    print "\n";
    my $max_room_count_update=$#updating_rooms+1;
    &print_title("Updating $max_room_count_update rooms:");
    my $room_count_update=1;
    foreach my $room (@updating_rooms){
	print "HERE: calling update room\n";
         &AD_group_update({ldap=>$ldap,
                           root_dse=>$root_dse,
                           dn=>$ref_AD_device->{'room'}{$room}{'DN'},
                           sophomorix_config=>\%sophomorix_config,
                            });
	print Dumper(\%update_room);

#        &AD_computer_update({ldap=>$ldap,
#                             root_dse=>$root_dse,
#                             computer=>$computer,
#                             computer_count=>$computer_count_update,
#                             attrs_count=>$update_computer{$computer}{'COUNT'},
#                             replace=>\%update_computer,
#                             max_computer_count=>$max_computer_count_update,
#                             json=>$json,
#                             sophomorix_config=>\%sophomorix_config,
#                             sophomorix_result=>\%sophomorix_result,
#                           });
        $room_count_update++;
    }

    ############################################################
    # Kill dnsNodes
    print "\n";
    &print_title("dnsNodes to be killed:");
    my $dns_node_count=1;
    foreach my $dns_node (@killing_dnsnodes){
        &AD_dns_kill({ldap=>$ldap, 
                      root_dse=>$root_dse,
                      root_dns=>$root_dns,
                      dns_zone=>$ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{$dns_node}{'dnsZone'},
                      dns_node=>$dns_node,
                      dns_ipv4=>$ref_AD_device->{'dnsNode'}{$DevelConf::dns_node_prefix_string}{$dns_node}{'IPv4'},
                      smb_pwd=>$smb_admin_pass,
                    });
        $dns_node_count++;
    }

    ############################################################
    # Kill dnsZones
    print "\n";
    &print_title("dnsZones to be killed:");
    my $dns_zone_count=1;
    foreach my $dns_zone (@killing_dnszones){
	print "        $dns_zone\n";
        &AD_dns_zonekill({ldap=>$ldap, 
                          root_dse=>$root_dse,
                          dns_server=>"localhost",
                          dns_zone=>$dns_zone,
                          smb_pwd=>$smb_admin_pass,
                        });
        $dns_zone_count++;
    }

    ############################################################
    # Add dnsZones
    print "\n";
    &print_title("dnsZones to be added:");
    $dns_zone_count=1;
    foreach my $dns_zone (@adding_dnszones){
        #my $filename="";
        my $filename=$devices_file{'dnsZone'}{$dns_zone};
        &AD_dns_zonecreate({ldap=>$ldap, 
                            root_dse=>$root_dse,
                            filename=>$filename,
                            dns_server=>$root_dns,
                            dns_zone=>$dns_zone,
                            smb_pwd=>$smb_admin_pass,
                          });
        $dns_zone_count++;
    }

    ############################################################
    # Add dnsNodes
    print "\n";
    &print_title("dnsNodes to be added:");
    $dns_node_count=1;
    foreach my $dns_node (@adding_dnsnodes){
        my $filename=$devices_file{'device'}{$dns_node}{'FILENAME'};
        &AD_dns_create({ldap=>$ldap, 
                        root_dse=>$root_dse,
                        root_dns=>$root_dns,
                        filename=>$filename,
                        dns_node=>$dns_node,
                        dns_ipv4=>$devices_file{'device'}{$dns_node}{'IPv4'},
                        smb_pwd=>$smb_admin_pass,
                           });
        $dns_node_count++;
    }

    ############################################################
    # Kill hardwareclasses
    print "\n";
    &print_title("Hardwareclasses to be killed:");
    my $kill_hwk_count=1;
    foreach my $hwk (@killing_hardwareclasses){
        print "   * Killing Hardwareclass $hwk ...\n";
        &AD_group_kill({ldap=>$ldap,
                        root_dse=>$root_dse,
                        root_dns=>$root_dns,
                        group=>$hwk,
                        type=>"hardwareclass",
                        group_count=>$kill_hwk_count,
                        sophomorix_config=>\%sophomorix_config,
                  });
    }

    ############################################################
    # Add hardwareclasses
    print "\n";
    &print_title("Hardwareclasses to be added:");
    my $hwk_count=0;
    foreach my $hwk (@adding_hardwareclasses){
        $hwk_count++;
        #my $group_token=&AD_get_name_tokened($hwk,$school,"hardwareclass");
         &AD_group_create({ldap=>$ldap,
                           root_dse=>$root_dse,
                           root_dns=>$root_dns,
                           school=>$school,
                           group=>$hwk,
                           group_basename=>$hwk,
                           description=>$hwk,
                           type=>"hardwareclass",
                           status=>"P",
                           sub_ou=>$sophomorix_config{'INI'}{'OU'}{'AD_hardwareclass_ou'},
                           smb_admin_pass=>$smb_admin_pass,
                           sophomorix_config=>\%sophomorix_config,
                           sophomorix_result=>\%sophomorix_result,
                         });
    }

    ############################################################
    # Add hardwareclass memberships
    print "\n";
    &print_title("Hardwareclass members to be added:");
    my $hwk_count_addmember=0;
    foreach my $member (keys %addmembers_hardwareclasses){
        $hwk_count_addmember++;
        print "ADD: $member to $addmembers_hardwareclasses{$member}\n";
        &AD_group_addmember({ldap => $ldap, 
                             root_dse => $root_dse, 
                             group => $addmembers_hardwareclasses{$member},
                             addmember => $member,
                           });   
    }

    ############################################################
    # Kill hardwareclass memberships
    print "\n";
    &print_title("Hardwareclass members to be killed:");
    my $hwk_count_killmember=0;
    foreach my $member (keys %killmembers_hardwareclasses){
        $hwk_count_killmember++;
        print "KILL: $member from $killmembers_hardwareclasses{$member}\n";
        &AD_group_removemember({ldap => $ldap, 
                                root_dse => $root_dse, 
                                group => $killmembers_hardwareclasses{$member},
                                removemember => $member,
                              });   
    }


    &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,\%sophomorix_config,$json);
}


# ===========================================================================
# --set-computer-passwords (setting computer passwords)
# ===========================================================================
if ($set_computer_passwords==1){
    print "Setting password for all Computer accounts:\n";
    my ($ref_AD_device) = &AD_get_AD_for_device({ldap=>$ldap,
                                                 root_dse=>$root_dse,
                                                 root_dns=>$root_dns,
                                                 sophomorix_config=>\%sophomorix_config,
                                               });
    # my ($ref_AD_device) = &AD_get_AD({ldap=>$ldap,
    #                        root_dse=>$root_dse,
    #                        root_dns=>$root_dns,
    #                        computers=>"TRUE",
    #                        #rooms=>"TRUE",
    #                        #examaccounts=>"TRUE",
    #                        dnszones=>"TRUE",
    #                        dnsnodes=>"TRUE",
    #                        sophomorix_config=>\%sophomorix_config,
    #          });
    my $count=1;

    foreach my $comp (keys %{$ref_AD_device->{'computer'}}) {
        my $pw;
        if ($password ne ""){
            # password by option
            $pw=$password;
        } else {
            # default password
            $pw=$pass;
        }
        print "\n*** $count: $comp  --> $pw\n";
        system("/usr/sbin/sophomorix-passwd --force -u $comp --pass $pw");
        $count++;
    }
    &log_script_exit("",0,1,0,\@arguments,\%sophomorix_result,\%sophomorix_config,$json);
}



# # ===========================================================================
# # --italc-dir  (create config files for italc)
# # ===========================================================================
# if ($italc_dir ne ""){
#     print "Creating italc files in $italc_dir\n";
#     system("mkdir -p $italc_dir");
#     system("chown $italc_owner.${DevelConf::teacher} $italc_dir");
#     system("chmod 0755 $italc_dir");

#     my $file_global="globalconfig.xml";
#     my $file_personal="personalconfig.xml";
#     my $dir_snapshots="snapshots";

#     foreach my $room (@italc_rooms){
#         my @teacher_hosts=();
#         my $classroom_name=$italc_rooms{$room}{'NAME'};
#         my $master_host=$italc_rooms{$room}{'MASTER'};

#         my $italc_parent=$italc_dir."/".$room;
#         my $italc_file_global=$italc_parent."/".$file_global;
#         my $italc_file_personal=$italc_parent."/".$file_personal;
#         my $italc_snapshots_dir=$italc_parent."/".$dir_snapshots;

#         system("mkdir -p $italc_parent");
#         system("chown $italc_owner.${DevelConf::teacher} $italc_parent");
#         system("chmod 0755 $italc_parent");

#         system("mkdir -p $italc_snapshots_dir");
#         system("chmod 0777 $italc_snapshots_dir");

#         print "Creating $italc_file_global for italcroom $room ...\n";
#         open(ITALCGLOBAL, ">$italc_file_global");
#         print ITALCGLOBAL '<?xml version="1.0"?>'."\n";
#         print ITALCGLOBAL '<!DOCTYPE italc-config-file>'."\n";
#         print ITALCGLOBAL '<globalclientconfig version="1.0.7" >'."\n";
#         print ITALCGLOBAL '  <body>'."\n";
#         print ITALCGLOBAL '    <classroom name="'.$classroom_name.'" >'."\n";

#         print "Creating $italc_file_personal for italcroom $room ...\n";
#         open(ITALCPERSONAL, ">$italc_file_personal");
#         print ITALCPERSONAL '<?xml version="1.0"?>'."\n";
#         print ITALCPERSONAL '<!DOCTYPE italc-config-file>'."\n";
#         print ITALCPERSONAL '<personalconfig version="1.0.7" >'."\n";
#         print ITALCPERSONAL '  <head>'."\n";

#         my @host_list_global=();
#         my @host_list_personal=();
#         my %host_lines_global=();
#         my %host_lines_personal=();
#         for my $host ( keys %{ $rooms_file{$room}{"HOSTS"} } ) {
#             my $ip=$domcomputers_file{$host}{"IP"};
#             my $mac=$domcomputers_file{$host}{"MAC"};
#             my $account_flag=$domcomputers_file{$host}{"ACCOUNT"};
#             # type? 0/1 
#             my $type=0;
#             if (exists $italc_rooms{$room}{"$host"}{'TYPE'}){
#                if ($italc_rooms{$room}{"$host"}{'TYPE'} eq "teacher host"){
# 		    $type=1;
#                     # remember teacher hosts
#                     push @teacher_hosts, $host;
#                 }
#             }

#             # visible? yes/no
#             my $visible="yes";
#             if (exists $italc_rooms{$room}{"$host"}{'INVISIBLE'}){
#                if ($italc_rooms{$room}{"$host"}{'INVISIBLE'} eq "yes"){
#                     $visible="no";
#                 }
#             }

#             # id is 6 digits of MAC-address converted to decimal
#             # more digits are not suppoorted bay italc 1.0.7
#             # perl can calculate lager hex numbers.
#             # warnings must be be disabled if you need more 
#             # -> see beginning of script: no warnings ....
#             my $hex_mac=$mac;
#             $hex_mac=~s/://g;
#             $hex_mac=substr($hex_mac,6,6);
# 	    my $dec_mac =  hex($hex_mac);
#             my $id=$dec_mac;

#             my $line_global="      <client localip=\"".$ip."\" ".
#                                               "mac=\"".$mac."\" ".
#                                              "type=\"".$type."\" ".
#                                                "id=\"".$id."\" ".
#                                              "name=\"".$host."\" ".
#                             "/>\n";
#             my $line_personal="      <client w=\"".$w_coord."\" ".
#                                             "x=\"".$x_coord."\" ".
#                                             "y=\"".$y_coord."\" ".
#                                             "h=\"".$h_coord."\" ".
#                                       "visible=\"".$visible."\" ".
#                                            "id=\"".$id."\" ".
#                               "/> <!-- $host -->\n";
#             if ($account_flag eq "1"){
#                 # for sorting
#                 push @host_list_global, $host;
#                 push @host_list_personal, $host;
#                 # save lines for later use
#                 $host_lines_global{$host}=$line_global;
#                 $host_lines_personal{$host}=$line_personal;
#             } else {
#                 # no account flag -> no italc account 
#             }
#         }

#         @host_list_global = sort @host_list_global;
#         @host_list_personal = sort @host_list_personal;

#         foreach my $host (@host_list_global){
# 		print ITALCGLOBAL "$host_lines_global{$host}";
#         }
        
#         # italc global file
#         print ITALCGLOBAL '    </classroom>'."\n";
#         print ITALCGLOBAL '  </body>'."\n";
#         print ITALCGLOBAL '</globalclientconfig>'."\n";
#         close(ITALCGLOBAL);
#         system("chown $italc_owner.${DevelConf::teacher} $italc_file_global");
#         system("chmod 0755 $italc_file_global");

#         # italc personal file
#         my $master_ip=$domcomputers_file{$master_host}{"IP"};
#         print ITALCPERSONAL '  <globalsettings '.
#                             "demo-master-ip=\"".$master_ip."\" ".
#                             'opened-tab="5" '.
#                             'demoquality="0" '.
#                             'defaultdomain="" '.
#                             'role="1" '.
#                             'demo-net-iface="eth0" '.
#                             'client-update-interval="1" '.
#                             'wincfg="AAAA/wAAAAD9AAAAAAAABAAAAAJfAAAABAAAAAQAAAAIAAAACPwAAAABAAAAAgAAAAEAAAAWAG0AYQBpAG4AdABvAG8AbABiAGEAcgEAAAAAAAAEAAAAAAAAAAAA" '.
#                             'notooltips="0" '.
#                             'win-height="663" '.
#                             'win-x="0" '.
#                             'ismaximized="1" '.
#                             'win-y="0" '.
#                             'clientdoubleclickaction="0" '.
#                             'win-width="1024" '.
#                             'showUserColumn="0" />'."\n";
#         print ITALCPERSONAL '  </head>'."\n";
#         print ITALCPERSONAL '  <body>'."\n";
#         print ITALCPERSONAL '    <classroom name="'.$classroom_name.'" >'."\n";
#         my $host_index=0; # index for array: index=0 --> first element
#         foreach my $host (@host_list_personal){
# 	    my $line_to_print=$host_lines_personal{$host};
#             # replace coordinates
#             $line_to_print=~s/$x_coord/$x_coord[$host_index]/g;
#             $line_to_print=~s/$y_coord/$y_coord[$host_index]/g;
#             print ITALCPERSONAL "$line_to_print";
#             # old: print unmodified
# 	    #print ITALCPERSONAL "$host_lines_personal{$host}";
#             $host_index++;
#         }
#         print ITALCPERSONAL '    </classroom>'."\n";
#         print ITALCPERSONAL '  </body>'."\n";
#         print ITALCPERSONAL '</personalconfig>'."\n";
#         close(ITALCPERSONAL);
#         system("chown $italc_owner.${DevelConf::teacher} $italc_file_personal");
#         system("chmod 0755 $italc_file_personal");

#         foreach my $teacher_host (@teacher_hosts){
#             # create links for teacher hosts
#             system("cd $italc_dir; ln -s $room $teacher_host");
#         }
#     }

#     # copying the keys
#     print "* Copying italc keys to $italc_dir\n";
#     system("cp -r $italc_key_dir $italc_dir");
#     system("chown -R $italc_owner.${DevelConf::teacher} $italc_dir");
#     if (-e "${italc_key_dir_admin}/key"){
#         system("chmod 440 ${italc_key_dir_admin}/key");
#     } else {
#         print "\nPlease add a key ${italc_key_dir_admin}/key!\n\n";
#     }
#     if (-e "${italc_key_dir_supporter}/key"){
#         system("chmod 440 ${italc_key_dir_supporter}/key");
#     } else {
#         print "\nPlease add a key ${italc_key_dir_supporter}/key!\n\n";
#     }
#     if (-e "${italc_key_dir_teacher}/key"){
#         system("chmod 440 ${italc_key_dir_teacher}/key");
#     } else {
#         print "\nPlease add a key ${italc_key_dir_teacher}/key!\n\n";
#     }
#     &log_script_end(\@arguments,\%sophomorix_result,$json);
# }



&AD_unbind_admin($ldap);

# syntax was OK
#&log_script_end(\@arguments,\%sophomorix_result,$json);
exit 0;






# ===========================================================================
# subs
# ===========================================================================
sub analyze_device_line {
    my ($line,$device_file,$filename,$school) = @_;
    if (/^#/ or /^\s*$/){
        return 0;
    } else {
        chomp($line);
        my ($room,
            $host,
            $hwk,
            $mac,
            $ip,
            $ms_office_key,
            $ms_windows_key,
            $unused,
            $sophomorix_role,
            $unused_2,
#            $account_flag,
            $pxe,
            $option,
            $field_13,
            $field_14,
            $sophomorix_comment)=split(/;/,$line);

        $room=&check_room($room,$line);
        $host=&check_host($host,$line);
        $hwk=&check_hwk($hwk,$line);
        $mac=&check_mac($mac,$line);
        $ip=&check_ip($ip,$line);
        $ms_office_key=&check_ms_software_key($ms_office_key,"MS-OFFICE-KEY",$host,$line);
        $ms_windows_key=&check_ms_software_key($ms_windows_key,"MS-WINDOWS-KEY",$host,$line);

        my $account_flag;
        ($sophomorix_role,$account_flag)=&check_sophomorix_role($sophomorix_role,$line,$filename);

        #$account_flag=&check_account_flag($account_flag,$line);
        $pxe=&check_pxe($pxe,$line);
        $option=&check_option($option,$line);

        # use tokened names 
        my $host_token=&AD_get_name_tokened($host,$school,"examaccount");

        my $room_token=&AD_get_name_tokened($room,$school,"roomws");
        my $ws_token=&AD_get_name_tokened($host,$school,"computer");
        my $ws_token_account=$ws_token."\$";
        if($Conf::log_level>=3){
            print "\n$line\n";
            print "ExamAccount: $host  -->  $host_token\n";
            print "Room:        $room  -->  $room_token\n";
            print "Computer:    $host  -->  $ws_token\n";
            print "Computer\$:  $host  -->  $ws_token_account\n";
            print "\n";
	}

        # save data into hash for reuse
        push @domcomputers_file, $host_token;
        $devices_file{'device'}{$host_token}{'ROOM_BASENAME'}=$room;            # 01
        $devices_file{'device'}{$host_token}{'HWK'}=$hwk;                       # 03
        $devices_file{'hardwareclass'}{$hwk}{$ws_token}=$host_token;

        $devices_file{'device'}{$host_token}{'MAC'}=$mac;                       # 04
        $devices_file{'device'}{$host_token}{'IPv4'}=$ip;                       # 05
        $devices_file{'device'}{$host_token}{'MS_OFFICE_KEY'}=$ms_office_key;   # 06
        $devices_file{'device'}{$host_token}{'MS_WINDOWS_KEY'}=$ms_windows_key; # 07
        $devices_file{'device'}{$host_token}{'ROOM'}=$room_token;
	print "HERE: $host_token :$account_flag was $unused_2\n";
        if ($account_flag==1){
            $devices_file{'device'}{$host_token}{'ACCOUNT'}="TRUE";
        } else {
            $devices_file{'device'}{$host_token}{'ACCOUNT'}="FALSE";
        }
        $devices_file{'device'}{$host_token}{'COMPUTER'}=$ws_token;
        $devices_file{'device'}{$host_token}{'COMPUTER_DOLLAR'}=$ws_token_account;
        $devices_file{'device'}{$host_token}{'SCHOOL'}=$school;
        $devices_file{'device'}{$host_token}{'PATH_ABS'}=$device_file;
        $devices_file{'device'}{$host_token}{'FILENAME'}=$filename;

        if (not defined $option){
            $option="";
        }       
        if (not defined $field_13){
            $field_13="";
        }       
        if (not defined $field_14){
            $field_14="";
        }       
        if (not defined $sophomorix_comment){
            $sophomorix_comment="";
        }       
        $devices_file{'device'}{$host_token}{'sophomorixRole'}=$sophomorix_role;       # 09
        $devices_file{'device'}{$host_token}{'OPTION'}=$option;                        # 12
        $devices_file{'device'}{$host_token}{'FIELD_13'}=$field_13;
        $devices_file{'device'}{$host_token}{'FIELD_14'}=$field_14;
        $devices_file{'device'}{$host_token}{'sophomorixComment'}=$sophomorix_comment; # 15

        # dnsZone
        my @octets=split(/\./,$ip);
        my $dns_zone=$octets[2].".".$octets[1].".".$octets[0].".in-addr.arpa";
        $devices_file{'dnsZone'}{$dns_zone}=$filename;

#???	print "   * Zone: $dns_zone needed\n";

        # dnsNode
        $devices_file{'dnsNode'}{$host_token}=$ip;

        $devices_file{'room'}{$room_token}{'HOSTS'}{$host_token}="seen";
        $devices_file{'room'}{$room_token}{'MAC'}{$mac}="seen";
        $devices_file{'room'}{$room_token}{'IPv4'}{$ip}="seen";

        # lists at room
        push @{ $devices_file{'room'}{$room_token}{'HOSTLIST'} }, $host_token;
        push @{ $devices_file{'room'}{$room_token}{'MACLIST'} }, $mac;
        push @{ $devices_file{'room'}{$room_token}{'IPv4LIST'} }, $ip;

        # field 10 decides 
        # $account_flag==0 (no account)
        # $account_flag==1 (create account) 1and all other values
        if ($account_flag==1){
            $devices_file{'computer'}{$ws_token_account}{'SCHOOL'}=$school;
            $devices_file{'computer'}{$ws_token_account}{'ROOM'}=$room_token;
            $devices_file{'computer'}{$ws_token_account}{'ROOM_BASENAME'}=$room;
            $devices_file{'computer'}{$ws_token_account}{'COMPUTER'}=$ws_token;
            $devices_file{'computer'}{$ws_token_account}{'COMPUTER_DOLLAR'}=$ws_token_account;
            $devices_file{'computer'}{$ws_token_account}{'FILENAME'}=$filename;
            $devices_file{'computer'}{$ws_token_account}{'sophomorixRole'}=$sophomorix_role;
            $devices_file{'computer'}{$ws_token_account}{'sophomorixComment'}=$sophomorix_comment;
            $devices_file{'computer'}{$ws_token_account}{'sophomorixComputerIP'}=$ip;
            $devices_file{'computer'}{$ws_token_account}{'sophomorixComputerMAC'}=$mac;
            $devices_file{'computer'}{$ws_token_account}{'sophomorixComputerRoom'}=$room_token;
        }
    }
}



sub check_room {
    my ($room,$line,$filename) = @_;
    if($Conf::log_level>=3){
        print "   ROOM:    $room\n";
    }
    # allow a-z0-9-_ lowercase
    if ( $room=~/[^A-Za-z0-9\-]/ ) {
        print "\n";
        print "LINE: $line\n";
        print "  ERROR: $room contains invalid characters in $filename\n\n";
        exit 88;
    } else {

    }
    return $room;
}



sub check_host {
    my ($host,$line,$filename) = @_;
    if($Conf::log_level>=3){
        print "   HOST:    $host\n";
    }
    # allow a-z0-9-  , convert to lowercase later
    if ( $host=~/[^A-Za-z0-9\-]/ ) {
        print "\n";
        print "LINE: $line\n";
        print "  ERROR: $host contains invalid characters in $filename\n\n";
        exit 88;
    } else {
        $host=~tr/A-Z/a-z/; # in Kleinbuchstaben umwandeln
        # correct
        $host_seen{$host}="seen";
    }
    return $host;
}



sub check_hwk {
    my ($hwk,$line,$filename) = @_;
    if($Conf::log_level>=3){
        print "   HWK:     $hwk\n";
    }
    # allow A-Za-z0-9   
    if ( $hwk=~/[^A-Za-z0-9\-_]/ ) {
        print "\n";
        print "LINE: $line\n";
        print "ERROR: $hwk contains invalid characters in $filename\n\n";
        exit 88;
    } else {

    }
    return $hwk;
}



sub check_mac {
    my ($old_mac,$line,$filename) = @_;
    if($Conf::log_level>=3){
       print "   MAC:     $old_mac\n";
    }
    my $mac = Net::MAC->new('mac' => $old_mac , base => 16); 
    my $new_mac = $mac->convert(
          'base'      => 16,   # convert to base 16, if necessary
          'bit_group' => 8,    # 16 bit grouping
          'delimiter' => ':',  # dot-delimited
          'die'       => 1     # die if conversion fails
	);
    # should die when mac is wrong

    # convert to uppercase
    $new_mac=~tr/a-z/A-Z/; # in Grossbuchstaben umwandeln

    # correct
    if (exists $mac_seen{$new_mac}){
        print "\n";
        print "LINE: $line\n";
        print "  ERROR: MAC >$new_mac< is double in $filename!\n\n";
        exit 88;
    } else {
        $mac_seen{$new_mac}="seen";
    }
    if($Conf::log_level>=3){
        print "      OLD: $old_mac\n";
        print "      NEW: $new_mac\n";
    }
    return $new_mac;
}



sub check_ip {
    my ($ip,$line,$filename) = @_;
    if($Conf::log_level>=3){
        print "   IP:      $ip";
    }
    # check for 3 .
    my $dots_in_string=$ip=~tr/\.//;
    if($Conf::log_level>=3){
        print " ($dots_in_string dots)\n";
    }
    if ($dots_in_string!=3){
        print "\n";
        print "LINE: $line\n";
        print "  ERROR: >$ip< does not contain 3 dots $filename\n\n";
        exit 88;        
    }
    
    # check for correct octets    
    my @octets = split(/\./,$ip);
    foreach my $octet (@octets){
        if($Conf::log_level>=3){
            print "      Octet:    $octet\n";
        }
        if ( int($octet) < 0 or int($octet) > 255) {
            print "\nERROR: ->$ip<- is invalid Option in ip octet $filename\n\n";
            exit 88;
        } else {

        }
    }

    # check for double ip
    if (exists $ip_seen{$ip}){
        print "\nERROR: IP $ip is double!\n\n";
        exit 88;
    } else {
        $ip_seen{$ip}="seen";
    }
    return $ip;
}



sub check_ms_software_key {
    my ($ms_software_key,$name,$host,$line,$filename) = @_;
    if (exists $ms_key_ok{$ms_software_key}){
        # skip tests, when tagged as 'no key'
        return $ms_software_key;
    }
    if($Conf::log_level>=3){
        print "   $name: $ms_software_key";
    }

    my $minus_in_string=$ms_software_key=~tr/-//;
    if($Conf::log_level>=3){
        print " ($minus_in_string minus signs)\n";
    }
    if ($minus_in_string!=4){
        if($Conf::log_level>=2){
            print "\n";
            print "LINE: $line\n";
            print "  WARNING $host: <$ms_software_key> $name: Not containing 4 minus signs\n\n";
        }
    }

    my @parts = split(/-/,$ms_software_key);
    foreach my $part (@parts){
        if($Conf::log_level>=3){
            print "      Part: <$part> (Length ".length($part).")\n";
        }
        if (length($part)!=5 ) {
            if($Conf::log_level>=2){
                print "\n";
                print "LINE: $line\n";
                print "  WARNING $host: <$ms_software_key> Not a $name:\n";
                print "   * Part: $part (Length ".length($part)." : Not 5 chacters long)\n\n";
            }
        } 
    }
    return $ms_software_key;
}



sub check_sophomorix_role {
    my ($role,$line,$filename) = @_;
    if ($role eq ""){
        $role=$sophomorix_config{'INI'}{'GLOBAL'}{'COMPUTERROLE_DEFAULT'};
    } elsif (not exists $sophomorix_config{'LOOKUP'}{'ROLES_DEVICE'}{$role}) {
        print "\n";
        print "LINE: $line\n";
        print "  ERROR: >$role< is not a valid role in $filename\n";
        print "     Valid sophomorixRole for devices are:\n";
        foreach my $keyname (keys %{$sophomorix_config{'LOOKUP'}{'ROLES_DEVICE'}} ) {
            print "        $keyname\n";
        }
        print "\n";
        exit 88;
    }
    # calculate account flag
    my $account_flag;
    my $key="computerrole.".$role;
    if ($sophomorix_config{'INI'}{$key}{'COMPUTER_ACCOUNT'} eq "TRUE"){
        $account_flag=1;
    } elsif ($sophomorix_config{'INI'}{$key}{'COMPUTER_ACCOUNT'} eq "FALSE"){
        $account_flag=0;
    } else {
        print "\n";
        print "ERROR: Cold not determine account flag by role $role";
        print "\n";
        exit 88;
    }

    return ($role,$account_flag);
}



# sub check_account_flag {
#     my ($account_flag,$line,$filename) = @_;
#     if ($account_flag eq 0){
#         # ok
#         $account_flag="0";
#     } else {
#         $account_flag="1";
#     }
#     if($Conf::log_level>=3){
#         print "   ACCOUNT FLAG:     $account_flag\n";
#     }
#     return $account_flag;
# }



sub check_pxe {
    my ($pxe,$line,$filename) = @_;
    if($Conf::log_level>=3){
        print "   PXE:     $pxe\n";
    }
    if ( $pxe=~/[0-9]/ ) {
        # this is correct
        return $pxe;
    }
    if ( not exists $pxe{$pxe} ) {
        print "\n";
        print "LINE: $line\n";
        print "  ERROR: >$pxe< is invalid Option in pxe field in $filename\n\n";
        exit 88;
    }
    return $pxe;
}



sub check_option {
    my ($option,$line,$filename) = @_;
    if (not defined $option){
        $option="";
        # ??? warning ???
    }
    if($Conf::log_level>=3){
        print "\n";
        print "LINE: $line\n";
        print "  OPTION: >$option<\n";
    }
    return $option;
}



# sub push_add_examaccount {
#     my ($add) = @_;
#     push @adding_examaccounts, $add;
# }



# sub push_kill_examaccount {
#     my ($kill) = @_;
#     push @killing_examaccounts, $kill;
# }



# sub push_kill_examaccount_room {
#     my ($kill) = @_;
#     push @killing_examaccount_rooms, $kill;
# }


sub push_kill_computer_room {
    my ($kill) = @_;
    push @killing_computer_rooms, $kill;
}



sub push_add_computer {
    my ($add) = @_;
    push @adding_computers, $add;
}



sub push_update_computer {
    my ($update) = @_;
    push @updating_computers, $update;
}



sub push_kill_computer {
    my ($kill) = @_;
    push @killing_computers, $kill;
}



sub push_update_room {
    my ($update) = @_;
    push @updating_rooms, $update;
}



sub push_add_dnsnode {
    my ($add) = @_;
    push @adding_dnsnodes, $add;
}



sub push_kill_dnsnode {
    my ($kill) = @_;
    push @killing_dnsnodes, $kill;
}



sub push_add_dnszone {
    my ($add) = @_;
    push @adding_dnszones, $add;
}



sub push_kill_dnszone {
    my ($kill) = @_;
    push @killing_dnszones, $kill;
}


sub push_add_hardwareclass {
    my ($add) = @_;
    push @adding_hardwareclasses, $add;
    $adding_hardwareclasses{$add}="add";
}


sub push_kill_hardwareclass {
    my ($kill) = @_;
    push @killing_hardwareclasses, $kill;
    $killing_hardwareclasses{$kill}="kill";
}




# sub get_classrooms {
#     &print_title("Fetching classrooms from $host_classrooms:");
#     if (not -e $host_classrooms){
#         print "   * File $host_classrooms does not exist!\n";
#         return;
#     } else {
#         print "   * File $host_classrooms exists\n";
#     }
#     open(CLASSROOM, "<$host_classrooms");
#     while(<CLASSROOM>){
#         chomp();
#         s/ //g;
#         if(/^\#/){ # # am Anfang bedeutet Kommentarzeile
#             next;
#         }
#         my $line=$_;
#         if($Conf::log_level>=2){
#             print "   * $line\n";
#         }
# 	print "CLASS <$line>\n";
#         push @class_rooms, $line;
#         $class_rooms{$line}="seen";
#     }
#     close(CLASSROOM);
# }



# sub get_italcrooms {
#     print "* Fetching italc rooms from $italc_conf:\n";
#     #if (not -e $italc_conf_dir){
#     #    system("mkdir -p $italc_conf_dir");
#     #}
#     if (not -e $italc_conf){
#         &log_script_exit("$italc_conf is missing",1,1,0,\@arguments,\%sophomorix_result,$json);
#         exit;
#     } 
#     if (not -e $italc_key_dir_admin){
#         system("mkdir -p $italc_key_dir_admin");
#     }
#     if (not -e $italc_key_dir_supporter){
#         system("mkdir -p $italc_key_dir_supporter");
#     }
#     if (not -e $italc_key_dir_teacher){
#         system("mkdir -p $italc_key_dir_teacher");
#     }
#     open(ITALCROOM, "<$italc_conf");
#     while(<ITALCROOM>){
#         chomp();
#         s/ //g;
#         if(/^\#/){ # # am Anfang bedeutet Kommentarzeile
#             next;
#         }
#         if($_ eq ""){ 
#             next;
#         }

#         my $line=$_;
#         my ($room,$italc_classroom_name,
#             $host_string,$invisible_host_string) = split(/:/,$line);
#         if($Conf::log_level>=2){
#             print "   * $room\n";
#         }

#         # room
#         push @italc_rooms, $room;

#         # classroom name
#         if ($italc_classroom_name eq ""){
#             $italc_classroom_name=$room;
#         } 
#         $italc_rooms{$room}{'NAME'}=$italc_classroom_name;

#         # hosts that can use italc
#         if (not defined $host_string or $host_string eq ""){
#             $italc_rooms{$room}="seen";
#             # ERROR: italc rooms must have a master
#             &log_script_exit("$room without master (italc)",1,1,0,\@arguments,\%sophomorix_result,$json);
#         } else {
#             my @teacher_hosts = split(/,/,$host_string);
#             my $i=1;
#             foreach my $host (@teacher_hosts){
#                 if($Conf::log_level>=2){
#                     print "      * $host is teacher host (type=1)\n";
#                 }
#                 $italc_rooms{$room}{"$host"}{'TYPE'}="teacher host";
#                 if ($i==1){
#                     #remember first entry
#                     $italc_rooms{$room}{'MASTER'}="$host";
#                 }
#                 $i++;
#             }
#         }

#         # invisible hosts
#         if (not defined $invisible_host_string or 
#                         $invisible_host_string eq ""){
#             # do nothing
#         } else {
#             my @invisible_hosts = split(/,/,$invisible_host_string);
#             foreach my $host (@invisible_hosts){
#                 if($Conf::log_level>=2){
#                     print "      * $host is an invisible host (visible=no)\n";
#                 }
#                 $italc_rooms{$room}{"$host"}{'INVISIBLE'}="yes";
#             }
#         }
#     }
#     close(ITALCROOM);
# }

