#!/usr/bin/perl -w
# $Id$
# This script (sophomorix-class) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# ===========================================================================
# Bibliotheken
# ===========================================================================
use strict;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use List::MoreUtils qw(uniq);

#use Sophomorix::SophomorixConfig;
#use Sophomorix::SophomorixBase;
#use Sophomorix::SophomorixAPI;
#use Sophomorix::SophomorixPgLdap;
#use DBI;
#use Net::LDAP;
use Net::LDAP;
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 time_stamp_AD
                                 time_stamp_file
                                 unlock_sophomorix
                                 lock_sophomorix
                                 log_script_start
                                 log_script_end
                                 log_script_exit
                                 backup_amku_file
                                 get_passwd_charlist
                                 get_plain_password
                                 check_options
                                 remove_from_list
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_ou_add
                                 AD_bind_admin
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_group_create
                                 AD_group_kill
                                 AD_group_addmember
                                 AD_get_ou_tokened
                                 AD_get_name_tokened
                                 AD_class_fetch
                                 AD_project_fetch
                                 AD_group_update
                                 AD_project_sync_members
                                 AD_dn_fetch_multivalue
                                 AD_group_list
                                 get_forbidden_logins
                                    );
my @arguments = @ARGV;

my $time_stamp_file=&time_stamp_file();
my $time_stamp_AD=&time_stamp_AD();

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================
# Variablen für Optionen
$Conf::log_level=1;
my $help=0;
my $info=0;
my $class="";
my $create=0;
my $kill=0;
my $ou="---";
my $school_token="---";

my $description;
my $quota;
my $mailquota;
my $mailalias;
my $maillist;
my $status;
my $join;
my $maxmembers;
my $creationdate;

my $admins;
my $addadmins;
my $removeadmins;



my $hide="";


my $reset_class="";
$Conf::log_level=1;

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "info|i" => \$info,
           "class|c=s" => \$class,
           "create" => \$create,
           "kill" => \$kill,
           "ou=s" => \$ou,
           "school-token=s" => \$school_token,
           "description=s" => \$description,
           "quota=s" => \$quota,
           "mailquota=i" => \$mailquota,
           "status=s" => \$status,
           "maxmembers=s" => \$maxmembers,
           "creationdate=s" => \$creationdate,
           "mailalias!" => \$mailalias,
           "maillist!" => \$maillist,
           "join!" => \$join,
           "admins=s" => \$admins,
           "addadmins=s" => \$addadmins,
           "removeadmins=s" => \$removeadmins,
#           "reset-class=s" => \$reset_class,
#           "hide!" => \$hide,
           "verbose|v+" => \$Conf::log_level,
          );

# Prüfen, ob Optionen erkannt wurden
&check_options($testopt);

# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-class sets properties of a class in the database

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose
  -i  / --info

Changing an adminclass:
  -c adminclass, / --class adminclass 
  (can set values also for the group teachers with --class teachers)
    --description \'multiple words possible\'
    --quota quotastring
    --mailquota number
    --mailalias, --nomailalias
    --maillist, --nomaillist 
    --status <letter>
    --join,  --nojoin
    --maxmembers number

    --admins user1,user2,user3, ... 
    --addadmins user1,user2,user3, ...
    --removeadmins user1,user2,user3, ...


  ??? --hide --class adminclass, --nohide --class hiddenclass 


This is for migration only:
  --create --class <adminclass>
  --creationdate <20150529093330.0Z> (only for migration)

Be careful with this command:
  --kill --class <adminclass>


Please see the sophomorix-class(8) man pages for full documentation
');
   print "\n";
   exit;
}


############################################################
# config values
############################################################

my ($ldap,$root_dse) = &AD_bind_admin();


# --info
# show all class when no specific class is given
if ($info==1 and $class eq ""){
   &AD_group_list($ldap,$root_dse,"adminclass",1);
   exit;
}

# --info --class name
# list class(es) and exit
if ($class ne "" and $info==1){
    my ($dn_class,$count)=&AD_class_fetch($ldap,$root_dse,$class,$ou,$school_token,$info);
    exit;
}

&log_script_start(@arguments);


# ===========================================================================
# Programmbeginn
# ===========================================================================

# --create --class <name>
############################################################
if ($create==1 and $class ne ""){
  &AD_ou_add({ldap=>$ldap,
              root_dse=>$root_dse,
              ou=>$ou,
              school_token=>$school_token,
              creationdate=>$time_stamp_AD,
            });
  my $group_token=&AD_get_name_tokened($class,$school_token,"adminclass");
  &AD_group_create({ldap=>$ldap,
                    root_dse=>$root_dse,
                    ou=>$ou,
                    school_token=>$school_token,
                    group=>$group_token,
                    description=>$group_token,
                    type=>"adminclass",
                    status=>"P",
                    creationdate=>$time_stamp_AD,
                    joinable=>"TRUE",
                  });
}

# --kill --class <name>
############################################################
if ($kill==1 and $class ne ""){
  my $group_token=&AD_get_name_tokened($class,$school_token,"adminclass");
  &AD_group_kill({ldap=>$ldap,
                  root_dse=>$root_dse,
                  group=>$group_token,
                  ou=>$ou,
                  school_token=>$school_token,
                  type=>"adminclass",
                  });
}


# get dn if class exists and continue ($info=0)
############################################################
my ($dn_class,$count)=&AD_class_fetch($ldap,$root_dse,$class,$ou,$school_token,$info);

if ($count>1){
    print "\n$count Projects found.\n";
    print "Specify the school-token to choose a project\n\n";
    exit $count;
}

##################################################
# ??? --sync_all_memberships for classes? ???



# --description <strg>
if (defined $description){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      description=>$description,
                    });
}

# --quota <strg>
if (defined $quota){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      quota=>$quota,
                    });
}

# --mailquota <strg>
if (defined $mailquota){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      mailquota=>$mailquota,
                    });
}

# --mailalias/nomailalias
if (defined $mailalias){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      mailalias=>$mailalias,
                    });
}

# --maillist/--nomaillist
if (defined $maillist){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      maillist=>$maillist,
                    });
}

# --status <P>
if (defined $status){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      status=>$status,
                    });
}

# --join/--nojoin
if (defined $join){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      join=>$join,
                    });
}

# --maxmembers <strg>
if (defined $maxmembers){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      maxmembers=>$maxmembers,
                    });
}

# --creationdate <strg>
if (defined $creationdate){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      creationdate=>$creationdate,
                    });
}

# # --hide
# if ($hide ne "" and $class ne ""){
#     if ($hide==0){
#         print "Unhiding class $class\n";
#         &update_class_db_entry($class,"Type=adminclass");
#     }
#     if ($hide==1){
#         print "Hiding class $class\n";
#         &update_class_db_entry($class,"Type=hiddenclass");
#     }
# }



##################################################
# admins

# --admins <user1,user2>
if (defined $admins){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      admins=>$admins,
                    });
}

# --addadmins <user1,user2>
if (defined $addadmins){
    my @addadmins=split(/,/,$addadmins);
    my @old_admins = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_class,"sophomorixAdmins");
    my @admins = uniq(@old_admins,@addadmins); 
    my $admins=join(",",@admins);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      admins=>$admins,
                    });
}

# --removeadmins <user1,user2>
if (defined $removeadmins){
    my @old_admins = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_class,"sophomorixAdmins");
    my @admins = &remove_from_list($removeadmins,@old_admins);
    my $admins=join(",",@admins);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_class,
                      type=>"adminclass",
                      admins=>$admins,
                    });
}


# # --reset-class
# if ($reset_class ne ""){
#     if ($reset_class eq ${DevelConf::teacher}){
#         &log_script_exit("ERROR: This option cannot be used with $reset_class",
#                          1,1,0,@arguments);
#     }

#     my ($group_type)=&pg_get_group_type($reset_class);

#     if ($group_type ne "adminclass"
#         and $group_type ne "hiddenclass"){
#         print "\nWARNING: Type of ${reset_class}: $group_type\n";
#         print   "         The option --reset-class can only be used\n",
#                 "         with type adminclass/hiddenclass\n\n";
#         &log_script_exit("ERROR: option works only with admin/hiddenclass",
#                          1,1,0,@arguments);
#     }

#     print "Type: $group_type\n";

#     my @students=&fetchstudents_from_adminclass($reset_class);

#     # repair.directories einlesen
#     &get_alle_verzeichnis_rechte();
#     # fetch permission for all homes
#     &fetch_repairhome();

#     # remove data from __vorlagen ($tasks_rooms)
#     my $command_1="rm -rf ${DevelConf::tasks_classes}/${reset_class}/*";
#     my $command_2="rm -rf ${DevelConf::share_classes}/${reset_class}/*";

#     if ($info==0){
#         print "Removing common stuff:\n";
#         print "   $command_1\n";
#         system("$command_1");
#         print "   $command_2\n";
#         system("$command_2");
#     } else {
#         print "   I would: $command_1\n";
#         print "   I would: $command_2\n";
#     }

#     print "Resetting all users of class $reset_class:\n";
#     foreach my $user (@students){
#         if ($info==0){
#             &reset_user($user);
#         } else {
#             print "   I would reset $user\n";
#         }
#     }
#     if ($info==1){
#         print "\nWARNING: To actually reset a class remove the --info/-i\n\n";
#     }
# }

# # Setting Quota if necessary
# if ($Conf::use_quota eq "yes" 
#     and $class ne "" 
#     and (defined $quota or defined $mailquota)
#     ) {
#     system("${DevelConf::path_sbin}/sophomorix-quota --class $class  --noninteractive");
#     &nscd_stop();
# } else {
#     &titel("NOT setting quota (nothing quota related changed)");
# }

# # Creating Mailing Aliases and Lists
# if ($class ne ""
#     and (defined $mailalias or defined $maillist)
#    ) {
#     system("${DevelConf::path_sbin}/sophomorix-mail");
#     &nscd_stop();
# } else {
#     &titel("NOT creating mailaliases/lists (nothing mail related changed)");
# }

# ===========================================================================
# Ende des Scripts
# ===========================================================================
&AD_unbind_admin($ldap);
&log_script_end(@arguments);







