#!/usr/bin/perl -w
# This script (sophomorix-project) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or jeffbeck@linuxmuster.net

# modules
use strict;
#use Quota;
use Getopt::Long;
Getopt::Long::Configure ("bundling");
use Sophomorix::SophomorixConfig;
use List::MoreUtils qw(uniq);
#use IMAP::Admin;
#use DBI;
use Net::LDAP;
use Data::Dumper;
$Data::Dumper::Indent = 1;
$Data::Dumper::Sortkeys = 1;
$Data::Dumper::Useqq = 1;
$Data::Dumper::Terse = 1; 
use JSON;
use Sophomorix::SophomorixBase qw(
                                 print_line
                                 print_title
                                 time_stamp_AD
                                 time_stamp_file
                                 unlock_sophomorix
                                 lock_sophomorix
                                 log_script_start
                                 log_script_end
                                 log_script_exit
                                 backup_auk_file
                                 get_passwd_charlist
                                 get_plain_password
                                 check_options
                                 config_sophomorix_read
                                 result_sophomorix_init
                                 result_sophomorix_add
                                 result_sophomorix_check_exit
                                 result_sophomorix_print
                                 remove_from_list
                                 json_dump
                                 );
use Sophomorix::SophomorixSambaAD qw(
                                 AD_school_create
                                 AD_bind_admin
                                 AD_dns_get
                                 AD_unbind_admin
                                 AD_user_create
                                 AD_group_create
                                 AD_group_kill
                                 AD_group_addmember
                                 AD_get_schoolname
                                 AD_get_name_tokened
                                 AD_project_fetch
                                 AD_group_update
                                 AD_project_sync_members
                                 AD_dn_fetch_multivalue
                                 AD_group_list
                                 AD_get_passwd
                                 AD_get_groups_v
                                 get_forbidden_logins
                                 next_free_gidnumber_get
                                 next_free_gidnumber_set
                                 AD_get_full_groupdata
                                    );

my @arguments = @ARGV;

my $time_stamp_file=&time_stamp_file();
my $time_stamp_AD=&time_stamp_AD();

# ===========================================================================
# Optionen verarbeiten
# ==========================================================================

# Variablen für Optionen
$Conf::log_level=1;
my $help=0;
my $tree=0;
my $info=0;
my $json=0;

my $user_info=0;
my $admininfo=0;

$Conf::log_level=1;

my $project="";
my $create=0;
my $gidnumber=-1;
my $gidnumber_wish;
my $kill=0;
my $school="---";

my $description;
my $addquota;
my $addmailquota;
my $mailalias;
my $maillist;
my $status;
my $join;
my $hide;
my $maxmembers;
my $creationdate;

my $members;
my $addmembers;
my $removemembers;

my $admins;
my $addadmins;
my $removeadmins;

my $membergroups;
my $addmembergroups;
my $removemembergroups;

my $admingroups;
my $addadmingroups;
my $removeadmingroups;

my $sync_all_memberships;

my $caller="";
my $curr_member="";
my $new_member="";

my $dump_all_projects=""; 
my $create_from_file="";
my $update_from_file="";

my $update=0;

my %all_projects=(); # hash with projects and their options

my %seen_projects=();   # projects sorted into @addorder_list
my %unseen_projects=(); # projects still to sort in @addorder_list
my @addorder_list=();   # order in which projects have to be added

# Parsen der Optionen
my $testopt=GetOptions(
           "help|h" => \$help,
           "info|i" => \$info,
           "json|j+" => \$json,
           "verbose|v+" => \$Conf::log_level,
#           "user|user-info|u" => \$user_info,
#           "admininfo" => \$admininfo,
           "create" => \$create,
           "gidnumber=i" => \$gidnumber,
           "kill" => \$kill,
           "join!" => \$join,
           "hide!" => \$hide,
#           "tree" => \$tree,
           "school=s" => \$school,
           "description=s" => \$description,
           "status=s" => \$status,
#           "caller=s" => \$caller,
           "members=s" => \$members,
           "addmembers=s" => \$addmembers,
           "removemembers=s" => \$removemembers,
           "admins=s" => \$admins,
           "addadmins=s" => \$addadmins,
           "removeadmins=s" => \$removeadmins,
           "membergroups=s" => \$membergroups,
           "addmembergroups=s" => \$addmembergroups,
           "removemembergroups=s" => \$removemembergroups,
           "admingroups=s" => \$admingroups,
           "addadmingroups=s" => \$addadmingroups,
           "removeadmingroups=s" => \$removeadmingroups,
           "sync-all-memberships" => \$sync_all_memberships,
           "name|project|p=s" => \$project,
           "addquota=s" => \$addquota,
           "addmailquota=s" => \$addmailquota,
           "maxmembers=s" => \$maxmembers,
           "creationdate=s" => \$creationdate,
           "mailalias!" => \$mailalias,
           "maillist!" => \$maillist,
#           "dump=s" => \$dump_all_projects,
#           "create-from-file=s" => \$create_from_file,
#           "update-from-file=s" => \$update_from_file,
#           "update" => \$update,
#           "curr-member|current-member=s" => \$curr_member,
#           "new-member|newmember=s" => \$new_member,
         );

my %sophomorix_result=&result_sophomorix_init("sophomorix-project");
# Prüfen, ob Optionen erkannt wurden
&check_options($testopt,\%sophomorix_result,$json);

# Reading Configuration
my ($ldap,$root_dse) = &AD_bind_admin(\@arguments,\%sophomorix_result,$json);
my $root_dns=&AD_dns_get($root_dse);
my %sophomorix_config=&config_sophomorix_read($ldap,$root_dse,\%sophomorix_result);
my ($smb_admin_pass)=&AD_get_passwd($DevelConf::sophomorix_file_admin,
                                     $DevelConf::secret_file_sophomorix_file_admin);


# --help
if ($help==1) {
   # Scriptname ermitteln
   my @list = split(/\//,$0);
   my $scriptname = pop @list;
   # Befehlbeschreibung
   print('
sophomorix-project adds projects to the sophomorix database and adds users
   or groups as members to the project

Options
  -h  / --help
  -v  / --verbose
  -vv / --verbose --verbose

Choose the school:
  --school <school>

Getting information:
  --admininfo
  --tree
  -i / --info
  -i -p projectname
  -u  / --user / --user-info -p project

Changing/creating/killing a project:
  --create -p projectname
  --create -p projectname --gidnumber num  (for migration only)
  --kill -p projectname

  -p <project>, / --project <project> 
    --description \'multiple words possible\'
    --addquota <share1>:<quota1 in MiB>:<comment1>,<share2>:<quota2 in MiB>:<comment2>,...
    --addmailquota <mailquota in MiB>:<Comment>
    --mailalias, --nomailalias
    --maillist, --nomaillist 
    --status <letter>
    --join,  --nojoin
    --hide,  --nohide
    --maxmembers number
    --creationdate <20150529093330.0Z> (only for migration)

    --admins user1,user2,user3, ... 
    --addadmins user1,user2,user3, ...
    --removeadmins user1,user2,user3, ...

    --members user1,user2,user3, ... 
    --addmembers user1,user2,user3, ...
    --removemembers user1,user2,user3, ...

    --admingroups group1,group2,group3, ... 
    --addadmingroups group1,group2,group3, ...
    --removeadmingroups group1,group2,group3, ...

    --membergroups group1,group2,group3, ... 
    --addmembergroups group1,group2,group3, ...
    --removemembergroups group1,group2,group3, ...

Dumping data into a file:
  --dump file
  --create-from-file file
  --update-from-file file

Syncing memberships of all projects (sophomorix* -> members):
  --sync-all-memberships

Listing or replacing a users memberships:
  --current-member user  (List meberships (admin,member) of user)
  --current-member user --new-member newuser   
    (replace membeships of user with newuser interactively)

Please see the sophomorix-project(8) man pages for full documentation
');
   print "\n";
   exit;
}





# --info
# show all projects when no specific projects is given
if ($info==1 and $project eq "" ){
    my $ref_group_v=&AD_get_groups_v({ldap=>$ldap,
                                   root_dse=>$root_dse,
                                   root_dns=>$root_dns,
                                   school=>$school,
                                   sophomorix_config=>\%sophomorix_config,
                                 });
    #print Dumper($ref_group_v);
    #print Dumper($ref_group_v->{'GROUPS'}{'p_Chemie-AG23'});
    my $jsoninfo="PROJECTS_OVERVIEW";
    my $jsoncomment="All Groups";
    &json_dump({json => $json,
                jsoninfo => $jsoninfo,
                jsoncomment => $jsoncomment,
                object_name => $school,
                log_level => $Conf::log_level,
                hash_ref => $ref_group_v,
                sophomorix_config => \%sophomorix_config,
               });
   exit;
}



# --info --project <project>
# list project(s) and exit
if ($info==1 and $project ne ""){
    my $ref_groups=&AD_get_full_groupdata({ldap=>$ldap,
                                           root_dse=>$root_dse,
                                           root_dns=>$root_dns,
                                           grouplist=>$project,
                                           sophomorix_config=>\%sophomorix_config,
                                      });
    #print Dumper($ref_groups);
    my $jsoninfo="PROJECT";
    my $jsoncomment="Project";
    &json_dump({json => $json,
                jsoninfo => $jsoninfo,
                jsoncomment => $jsoncomment,
                object_name => $school,
                log_level => $Conf::log_level,
                hash_ref => $ref_groups,
                sophomorix_config => \%sophomorix_config,
               });
    exit;
}


# --admininfo
if ($admininfo==1){
#    if ($project eq ""){
#        &show_project_admin_list();
#        exit;
#    } else {
#        print "\n   Option --admininfo cannot be used together with a project\n\n";
#        exit;
#    }
}


# --user-info --project name
if ($user_info==1){
#    if ($project ne ""){
#        &show_project_userinfo($project);
#        exit;
#        #&log_script_exit("Project $project showed!",
#        #                  1,1,0,\@arguments,\%sophomorix_result,$json);
#    } else {
#        print "\n   Option --userinfo has be used together with a project\n\n";
#        exit;
#    }
}


&result_sophomorix_check_exit(\%sophomorix_result,\%sophomorix_config,$json);
&log_script_start(\@arguments,\%sophomorix_result);

# --current-member
# --new-member
if ($curr_member ne ""){
    # # fetch all projects
    # my @projects=&fetchprojects_from_school();
    #     foreach my $pro (@projects){
    # 	    #print "checking $pro\n"; 
    #         # check if curr_menber is admin
    #         # list or replace replace
    #         my @admins=&fetchadmins_from_project($pro);
    #         foreach my $adm (@admins){
    # 		if ($adm eq $curr_member){
    #                 print " *** $curr_member is admin in $pro\n";
    #                 &replace_membership("admin",$pro,$curr_member,$new_member);
    #             }
    #         }
    #         # check if curr_menber is member
    #         # list or replace replace
    #         my @users=&fetchmembers_by_option_from_project($pro);
    #         foreach my $user (@users){
    # 		if ($user eq $curr_member){
    #                 print "   * $curr_member is member in $pro\n";
    #                 &replace_membership("member",$pro,$curr_member,$new_member);
    #             }
    #         }
    # }
    exit;
}


# --caller and --nojoin
# if ($project ne "" and $create==0
#     and 
#     ($addmembers ne ""
#      or $removemembers ne ""
#      or $addadmins ne ""
#      or $removeadmins ne ""
#      or $addmembergroups ne ""
#      or $removemembergroups ne ""
#      or $addmemberprojects ne ""
#      or $removememberprojects ne ""
#      or defined $p_admins
#      or defined $p_members
#      or defined $p_groups
#      or defined $p_projects
#      or defined $join)
#     ){
#     # print "Changing something, eh ----\n";
#     # my ($a1,$a2,$a3,$a4,$join_val) = &fetchinfo_from_project($project);
#     # if ($join_val==0){
#     #     print "Project is NOT joinable $join_val\n";
#     #     if ($caller eq ""){
#     #        print "You must use --caller name to modify such a project!\n";
#     #        &Sophomorix::SophomorixBase::log_script_exit(
#     #            "Request to modify nojoin project without --caller!",
#     #            1,1,0,\@arguments,\%sophomorix_result,$json);

#     #     } else {
#     #        print "I must check if $caller is allowed\n";
#     #        my @admins_val=&fetchadmins_from_project($project);
#     #        my $go_on=0;
#     #        if ($caller eq "root"){
#     # 	       $go_on=1;
#     #            print "$caller is root!\n";
#     #        } else {
#     #            foreach my $admin_val (@admins_val){
#     #                #print "Checking ---$admin_val--- and ---$caller---\n";
#     #                if ($caller eq $admin_val){
#     #                    $go_on=1;
#     #                    print "$caller is admin!\n";
#     #                    last;
#     #                }
#     #            }
#     #        }
#     #        if ($go_on==0){
#     #            print "$caller is NOT admin of $project\n";
#     #            print "$caller is NOT allowed to change userlist\n";
#     #            &Sophomorix::SophomorixBase::log_script_exit(
#     #            "Nonadmin tried to change nojoin project!",
#     #            1,1,0,\@arguments,\%sophomorix_result,$json);
#     #        }
#     #     }
#     # }
# }






# writing/reading to/from a file

# --dump filename
if ($project eq "" and $dump_all_projects ne ""){
#    &dump_all_projects("$dump_all_projects",@arguments);
#    &Sophomorix::SophomorixBase::log_script_exit(
#    "All projects dumped!",
#    0,1,0,\@arguments,\%sophomorix_result,$json);
}


# --create-from-file filename
if ($project eq "" and $create_from_file ne ""){
#    &project_from_file($create_from_file,"--create",@arguments);
#    &Sophomorix::SophomorixBase::log_script_exit(
#    "All projects created!",
#    0,1,0,\@arguments,\%sophomorix_result,$json);
}


# --update-from-file filename
if ($project eq "" and $update_from_file ne ""){
#    &project_from_file($update_from_file,"",@arguments);
#    &Sophomorix::SophomorixBase::log_script_exit(
#    "All projects updated!",
#    0,1,0,\@arguments,\%sophomorix_result,$json);
}




# parse arguments
#if (defined $p_long_name) {
#   unless ($p_long_name =~ m/^([\w-]{6,32})$/) { 
#       print "\nArgument of --longname\n";
#       print "   contains invalid characters. \n";
#       print "   or is too short or too long (6-32 characters). \n\n";
#       &log_script_exit("Invalid characters in argument!",
#                         1,1,0,\@arguments,\%sophomorix_result,$json);
#   }
#}

# if (defined $project) {
#    # append p_
#    unless ($project =~ m/^p\_/) { 
#        $project="p_".$project;
#    }
#    # parse name WITH p_ in the beginning
#    unless ($project =~ m/^([\w-]{3,16})$/) { 
#        print "\nArgument of --project\n";
#        print "   contains invalid characters. \n";
#        print "   or is too short or too long (3-14 characters after p_). \n\n";
#        &log_script_exit("Invalid characters in argument!",
#                          1,1,0,\@arguments,\%sophomorix_result,$json);
#    }
# }








# ===========================================================================
# Programmbeginn
# ===========================================================================




# --create --project <name>
############################################################
if ($create==1 and $project ne ""){
    # --gidnumber
    ############################################################
    if ($gidnumber==-1){
       $gidnumber_wish=&next_free_gidnumber_get($ldap,$root_dse);
    } else {
	$gidnumber_wish=$gidnumber;
    }
   &AD_school_create({ldap=>$ldap,
                      root_dse=>$root_dse,
                      root_dns=>$root_dns,
                      school=>$school,
                      creationdate=>$time_stamp_AD, 
                      smb_admin_pass=>$smb_admin_pass,
                      sophomorix_config=>\%sophomorix_config,
                      sophomorix_result=>\%sophomorix_result,
                    });
   my $group_token=&AD_get_name_tokened($project,$school,"project");
   &AD_group_create({ldap=>$ldap,
                     root_dse=>$root_dse,
                     root_dns=>$root_dns,
                     school=>$school,
                     group=>$group_token,
                     group_basename=>$project,
                     description=>$group_token,
                     type=>"project",
                     status=>"P",
                     creationdate=>$time_stamp_AD,
                     sub_ou=>$sophomorix_config{'INI'}{'OU'}{'AD_project_ou'},
                     gidnumber_wish=>$gidnumber_wish,
                     smb_admin_pass=>$smb_admin_pass,
                     sophomorix_config=>\%sophomorix_config,
                     sophomorix_result=>\%sophomorix_result,
                  });
}



# --kill --project <name>
############################################################
if ($kill==1 and $project ne ""){
    my $group_token=&AD_get_name_tokened($project,$school,"project");
    &AD_group_kill({ldap=>$ldap,
                    root_dse=>$root_dse,
                    root_dns=>$root_dns,
                    group=>$group_token,
                    smb_admin_pass=>$smb_admin_pass,
                    type=>"project",
                    sophomorix_config=>\%sophomorix_config,
                  });
    &log_script_end(\@arguments,\%sophomorix_result,\%sophomorix_config,$json);
    exit;
}


##################################################
# --sync_all_memberships
if (defined $sync_all_memberships){
   #my $ref_group_v=&AD_get_groups_v({ldap=>$ldap,
   #                                root_dse=>$root_dse,
   #                                root_dns=>$root_dns,
   #                                school=>$school,
   #                                sophomorix_config=>\%sophomorix_config,
   #                              });
   # print Dumper($ref_group_v);
   #my @school_list;
   # if ($school eq "" or $school_opt eq "---"){
   #     @school_list=@{ $ref_sophomorix_config->{'LISTS'}{'SCHOOLS'} };
   # } else {
   #     @school_list=($school_opt);
   # }

    print "Syncing memberships of the following projects:\n";
    my @projects_dn=&AD_group_list($ldap,$root_dse,"project",0);



    foreach my $pro_dn (@projects_dn){
        &AD_project_sync_members($ldap,$root_dse,$pro_dn);
    }
    exit;
}





# get dn if project exists and continue
############################################################
my ($dn_pro,$count,$school_AD)=&AD_project_fetch($ldap,$root_dse,$project,$school,$info);

if ($count>1){
    print "\n$count Projects found.\n";
    print "Specify the school-token to choose a project\n\n";
    &log_script_exit("Specify the school-token to choose a project",$count,1,0,
                     \@arguments,\%sophomorix_result,\%sophomorix_config,$json);
} elsif ($count==0){
    print "\nERROR retrieving project $project: $count project found.\n\n";
    &log_script_exit("ERROR retrieving project $project: $count project found.",$count,1,0,
                     \@arguments,\%sophomorix_result,\%sophomorix_config,$json);
}




# all actions from now on work on the dn retrieved
############################################################

# --description <strg>
if (defined $description){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      description=>$description,
                      sophomorix_config=>\%sophomorix_config,
                    });
}


# --addquota <strg>
if (defined $addquota){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      addquota=>$addquota,
                      sophomorix_config=>\%sophomorix_config,
                    });
}


# --addmailquota <strg>
if (defined $addmailquota){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      addmailquota=>$addmailquota,
                      sophomorix_config=>\%sophomorix_config,
                    });
}


# --mailalias/nomailalias
if (defined $mailalias){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      mailalias=>$mailalias,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --maillist/--nomaillist
if (defined $maillist){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      maillist=>$maillist,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --status <P>
if (defined $status){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      status=>$status,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --join/--nojoin
if (defined $join){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      join=>$join,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --hide/--nohide
if (defined $hide){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      hide=>$hide,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --maxmembers <strg>
if (defined $maxmembers){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      maxmembers=>$maxmembers,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --creationdate <strg>
if (defined $creationdate){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      creationdate=>$creationdate,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

##################################################
# members
# --members <user1,user2>
if (defined $members){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      members=>$members,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --addmembers <user1,user2>
if (defined $addmembers){
    my @addmembers=split(/,/,$addmembers);
    my @old_members = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixMembers");
    my @members = uniq(@old_members,@addmembers); 
    my $members=join(",",@members);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      members=>$members,
                      sophomorix_config=>\%sophomorix_config,
                    });
}
 
# --removemembers <user1,user2>
if (defined $removemembers){
    my @old_members = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixMembers");
    my @members = &remove_from_list($removemembers,@old_members);
    my $members=join(",",@members);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      members=>$members,
                      sophomorix_config=>\%sophomorix_config,
                    });
}



##################################################
# admins
# --admins <user1,user2>
if (defined $admins){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      admins=>$admins,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --addadmins <user1,user2>
if (defined $addadmins){
    my @addadmins=split(/,/,$addadmins);
    my @old_admins = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixAdmins");
    my @admins = uniq(@old_admins,@addadmins); 
    my $admins=join(",",@admins);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      admins=>$admins,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --removeadmins <user1,user2>
if (defined $removeadmins){
    my @old_admins = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixAdmins");
    my @admins = &remove_from_list($removeadmins,@old_admins);
    my $admins=join(",",@admins);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      admins=>$admins,
                      sophomorix_config=>\%sophomorix_config,
                    });
}



##################################################
# membergroups
# --membergroups <group1,group2>
if (defined $membergroups){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      membergroups=>$membergroups,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --addmembergroups <group1,group2>
if (defined $addmembergroups){
    my @addmembergroups=split(/,/,$addmembergroups);
    my @old_membergroups = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixMemberGroups");
    my @membergroups = uniq(@old_membergroups,@addmembergroups); 
    my $membergroups=join(",",@membergroups);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      membergroups=>$membergroups,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --removemembergroups <user1,user2>
if (defined $removemembergroups){
    my @old_membergroups = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixMemberGroups");
    my @membergroups = &remove_from_list($removemembergroups,@old_membergroups);
    my $membergroups=join(",",@membergroups);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      membergroups=>$membergroups,
                      sophomorix_config=>\%sophomorix_config,
                    });
}



##################################################
# admingroups
# --admingroups <group1,group2>
if (defined $admingroups){
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      admingroups=>$admingroups,
                    });
}

# --addadmingroups <group1,group2>
if (defined $addadmingroups){
    my @addadmingroups=split(/,/,$addadmingroups);
    my @old_admingroups = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixAdminGroups");
    my @admingroups = uniq(@old_admingroups,@addadmingroups); 
    my $admingroups=join(",",@admingroups);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      admingroups=>$admingroups,
                      sophomorix_config=>\%sophomorix_config,
                    });
}

# --removeadmingroups <user1,user2>
if (defined $removeadmingroups){
    my @old_admingroups = &AD_dn_fetch_multivalue($ldap,$root_dse,$dn_pro,"sophomorixAdminGroups");
    my @admingroups = &remove_from_list($removeadmingroups,@old_admingroups);
    my $admingroups=join(",",@admingroups);
    &AD_group_update({ldap=>$ldap,
                      root_dse=>$root_dse,
                      dn=>$dn_pro,
		      school=>$school_AD,
                      type=>"project",
                      admingroups=>$admingroups,
                      sophomorix_config=>\%sophomorix_config,
                    });
}







# # repair.directories einlesen
# &get_alle_verzeichnis_rechte();

# # fetch permission for all homes
# &fetch_repairhome();

# # create/update project
# if ($kill==0 and $update==0){
#     &create_project($project,$create,$p_long_name,
#                     $p_add_quota,$p_add_mail_quota,
#                     $p_status,$p_join,$time_stamp_AD,
#                     $p_max_members,$p_members,$p_admins,
#                     $p_groups,$p_projects,
#                     $p_mailalias,$p_maillist);
# } elsif  ($kill==1 and $update==0){
#     # remove all users from project
#     # (BEFORE removing project)
#     print "Preparing Project $project to kill (remove users)!\n";
#     &create_project($project,0,$p_long_name,
#                     0,0,
#                     "K","FALSE",$time_stamp_AD,
#                     0,"","",
#                     "","",
#                     0,0);

#     # project_details: Eintrag löschen
#     # und files loeschen 
#     # (BEFORE removing group)
#     &remove_project($project);

#     # gruppe entfernen
#     &remove_class_db_entry($project);
# }

# if ($update==1 and $project ne ""){
#     print "updating project $project:\n";
#     &update_project($project,$time_stamp_AD);
# }


# # Setting Quota if necessary
# if ($Conf::quota_use eq "yes" 
#       and (
#          defined $p_admins
#          or defined $p_groups
#          or defined $p_members
#          or defined $p_projects
#          or defined $p_add_quota
#          or defined $p_add_mail_quota
#          or $kill==1
#         ) 
#     ) {
#     # system("sophomorix-quota --students --teachers --noninteractive");
#     system("${DevelConf::executable_pfad}/sophomorix-quota --project $project --noninteractive");
#     &nscd_stop();
# } else {
#     &titel("NOT setting quota (nothing quota related changed)");
# }


# # Creating Mailing Aliases and Lists
# if (defined $p_admins
#     or defined $p_groups
#     or defined $p_members
#     or defined $p_projects
#     or defined $p_long_name
#     or defined $mailalias
#     or defined $maillist
#     or $kill==1
#    ) {
#     system("${DevelConf::executable_pfad}/sophomorix-mail");
#     &nscd_stop();
# } else {
#     &titel("NOT creating mailaliases/lists (nothing mail related changed)");
# }

&AD_unbind_admin($ldap);
&log_script_end(\@arguments,\%sophomorix_result,\%sophomorix_config,$json);
