#!/usr/bin/perl -w
# This script (sophomorix-postinst) is maintained by Rüdiger Beck
# It is Free Software (License GPLv3)
# If you find errors, contact the author
# jeffbeck@web.de  or  jeffbeck@linuxmuster.net

# modules
use strict;

my $conf_dir="/etc/linuxmuster/sophomorix";
my $conf_file=$conf_dir."/sophomorix.conf";
my $conf_file_source="/usr/share/sophomorix/config-templates/sophomorix.conf.template.ini";

print "##### sophomorix-postinst start #####\n";

print "\n";
print "* Testing $conf_file\n";
# create directory
system "mkdir -p $conf_dir";
# copy the default sophomorix.conf
if (-e $conf_file){
    # do nothing
    print "   * File exists, no installation:\n";
    print "     $conf_file\n";
    # LATER: do upgrade sophomorix.conf
} else {
    # copy the template
    print "     Installing $conf_file\n";
    system("install -oroot -groot --mode=0644 $conf_file_source $conf_file");    
}

# without option
my $school="default-school";
my $school_dir=$conf_dir."/".$school;
my $school_file=$school_dir."/school.conf";

# option given, modify 
if (defined $ARGV[0] and ($ARGV[0] eq "global" or $ARGV[0] eq "linuxmuster-global")){
    print " \nERROR: You cannot create a school with the name $ARGV[0]\n\n\n";
    exit;
} elsif (defined $ARGV[0] and $ARGV[0] ne $school){
    $school=$ARGV[0];
    $school_dir=$conf_dir."/".$school;
    $school_file=$school_dir."/".$school.".school.conf";
}
my $school_file_source="/usr/share/sophomorix/config-templates/school.conf.template.ini";


print "\n";
print "* Testing for $school_file\n";
# create directory
system "mkdir -p $school_dir";
# copy the default sophomorix.conf
if (-e $school_file){
    # do nothing
    print "   * File exists, no installation:\n";
    print "     $school_file\n";
    # LATER: do upgrade sophomorix.conf
} else {
    # copy the template
    print "     Installing $school_file\n";
    system("install -oroot -groot --mode=0644 $school_file_source $school_file");    
}




print "\n";
print "##### sophomorix-postinst end #####\n";
