#!/bin/sh

# clean up with: 
#     rm -rf /srv/samba/schools
#     rm -rf /srv/samba/global

mkdir -p /srv/samba/global

mkdir -p /srv/samba/schools/abc
mkdir -p /srv/samba/schools/bsz
mkdir -p /srv/samba/schools/default-school
mkdir -p /srv/samba/schools/ghs
mkdir -p /srv/samba/schools/lin
mkdir -p /srv/samba/schools/ltg
mkdir -p /srv/samba/schools/test
mkdir -p /srv/samba/schools/uni


net conf addshare linuxmuster-global /srv/samba/global writeable=y guest_ok=y "Share for school global"

net conf addshare abc /srv/samba/schools/abc writeable=y guest_ok=y "Share for school abc"
net conf addshare bsz /srv/samba/schools/bsz writeable=y guest_ok=y "Share for school bsz"
net conf addshare default-school /srv/samba/schools/default-school writeable=y guest_ok=y "Share for school default-school"
net conf addshare ghs /srv/samba/schools/ghs writeable=y guest_ok=y "Share for school ghs"
net conf addshare lin /srv/samba/schools/lin writeable=y guest_ok=y "Share for school lin"
net conf addshare ltg /srv/samba/schools/ltg writeable=y guest_ok=y "Share for school ltg"
net conf addshare test /srv/samba/schools/test writeable=y guest_ok=y "Share for school test"
net conf addshare uni /srv/samba/schools/uni writeable=y guest_ok=y "Share for school uni"

#
echo "The shares:"
net conf listshares
