#!/bin/sh

sophomorix-user -u $1 --custom1 "Test custom1"
sophomorix-user -u $1 --custom2 "Test custom2"
sophomorix-user -u $1 --custom3 "Test custom3"
sophomorix-user -u $1 --custom4 "Test custom4"
sophomorix-user -u $1 --custom5 "Test custom5"

sophomorix-user -u $1 --intrinsic1 "Test intrinsic1"
sophomorix-user -u $1 --intrinsic2 "Test intrinsic2"
sophomorix-user -u $1 --intrinsic3 "Test intrinsic3"
sophomorix-user -u $1 --intrinsic4 "Test intrinsic4"
sophomorix-user -u $1 --intrinsic5 "Test intrinsic5"
