#!/bin/sh

# clean up with: 
#     rm -rf /home/schools
#     rm -rf /home/global

mkdir -p /home/global

mkdir -p /home/schools/abc
mkdir -p /home/schools/bsz
mkdir -p /home/schools/default-school
mkdir -p /home/schools/ghs
mkdir -p /home/schools/lin
mkdir -p /home/schools/ltg
mkdir -p /home/schools/test
mkdir -p /home/schools/uni


net conf addshare default-global /home/global writeable=y guest_ok=y "Share for school global"

net conf addshare abc /home/schools/abc writeable=y guest_ok=y "Share for school abc"
net conf addshare bsz /home/schools/bsz writeable=y guest_ok=y "Share for school bsz"
net conf addshare default-school /home/schools/default-school writeable=y guest_ok=y "Share for school default-school"
net conf addshare ghs /home/schools/ghs writeable=y guest_ok=y "Share for school ghs"
net conf addshare lin /home/schools/lin writeable=y guest_ok=y "Share for school lin"
net conf addshare ltg /home/schools/ltg writeable=y guest_ok=y "Share for school ltg"
net conf addshare test /home/schools/test writeable=y guest_ok=y "Share for school test"
net conf addshare uni /home/schools/uni writeable=y guest_ok=y "Share for school uni"

#
echo "The shares:"
net conf listshares