#!/bin/sh

samba-tool user create sophomorix-admin 'Muster!'
echo 'Muster!' > /etc/linuxmuster/.secret/sophomorix-admin
samba-tool user setexpiry sophomorix-admin --noexpiry
samba-tool group addmembers Administrators  sophomorix-admin
