#!/bin/bash
sophomorix-samba --restore-samba ohne-user --schema-load

rm -rf /srv/samba

sleep 4

#./tools/add-sophomorix-admin

#sshpass -p "Muster!" samba-tool user setpassword Administrator
samba-tool user setpassword Administrator

sophomorix-test-$1 --full
