#!/bin/sh
#ldbsearch -H ldaps://localhost "sAMAccountName=$1" -Uadministrator $2 $3 $4 $5 $6 $7 $8 $9

# WORKS: --user=administrator
# WORKS: --simple-bind-dn="cn=Administrator,cn=Users,dc=linuxmuster,dc=local"

ldbsearch -H ldap://localhost --sign --encrypt --simple-bind-dn="cn=Administrator,cn=Users,dc=linuxmuster,dc=local"  --password=`cat /etc/linuxmuster/.secret/administrator` -b "OU=SCHOOLS,DC=linuxmuster,DC=local" "sAMAccountName=$1" dn givenName sn sAMAccountName sophomorixAdminclass sophomorixFirstnameASCII sn sophomorixSurnameASCII
