#!/bin/sh
sophomorix-vampire --datadir ../sophomorix-dump --analyze

sophomorix-vampire --datadir ../sophomorix-dump --create-class-script

/root/sophomorix-vampire-classes.sh

samba-tool domain passwordsettings set --complexity=off
samba-tool domain passwordsettings set --min-pwd-length=2

sophomorix-vampire --datadir ../sophomorix-dump --create-add-file
cp /root/sophomorix.add /var/lib/sophomorix/check-result/sophomorix.add

sophomorix-add 

sophomorix-vampire --datadir ../sophomorix-dump --import-user-password-hashes

samba-tool domain passwordsettings set --complexity=default
samba-tool domain passwordsettings set --min-pwd-length=default


sophomorix-vampire --datadir ../sophomorix-dump --create-class-adminadd-script
/root/sophomorix-vampire-classes-adminadd.sh

sophomorix-vampire --datadir ../sophomorix-dump --create-project-script

/root/sophomorix-vampire-projects.sh
